<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-18">
<meta name="description" content="A structured reading of the hypotheses for the 2026 Basque Physics result against the assembled evidence, the institutional narrative after 6 July, and a prioritised list of data requests and design choices for PAU 2027.">

<title>Interpretation and the 2027 question – PAU Física 2026</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/11-exam-content.html" rel="next">
<link href="../chapters/05-subjects-sittings.html" rel="prev">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-34ccee47bae06f2332eb94a15df79591.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0c8081985eeeb50794d30fa8d31fc890.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-34ccee47bae06f2332eb94a15df79591.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-29e5ce9c295aebebc96a6ba847e0be6c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-e0926ce36429a4f6419cf7f43c044cdd.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-29e5ce9c295aebebc96a6ba847e0be6c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css?family=Inter:400,400i,500,600,700%7CJetBrains+Mono:400,700&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/favicon.svg" alt="PAU Física 2026" class="navbar-logo light-content">
    <img src="../assets/favicon.svg" alt="PAU Física 2026" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PAU Física</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/02-euskadi.html"> 
<span class="menu-text">The Euskadi break</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/03-spain-2026.html"> 
<span class="menu-text">Spain 2026</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/08-sources.html"> 
<span class="menu-text">Sources &amp; methods</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-euskadi.html">Evidence and results</a></li><li class="breadcrumb-item"><a href="../chapters/06-interpretation.html">Interpretation &amp; 2027</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><i class="bi bi-house" role="img">
</i> 
 <span class="menu-text">Findings</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence and results</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-euskadi.html" class="sidebar-item-text sidebar-link"><i class="bi bi-bar-chart-line" role="img">
</i> 
 <span class="menu-text">Euskadi 2010–2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-spain-2026.html" class="sidebar-item-text sidebar-link"><i class="bi bi-globe-europe-africa" role="img">
</i> 
 <span class="menu-text">Spain 2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-distributions.html" class="sidebar-item-text sidebar-link"><i class="bi bi-graph-up" role="img">
</i> 
 <span class="menu-text">Shape of the collapse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-subjects-sittings.html" class="sidebar-item-text sidebar-link"><i class="bi bi-people" role="img">
</i> 
 <span class="menu-text">Subjects &amp; participation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-interpretation.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-compass" role="img">
</i> 
 <span class="menu-text">Interpretation &amp; 2027</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">The papers</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-exam-content.html" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-text" role="img">
</i> 
 <span class="menu-text">The papers themselves</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-ehu-paper-history.html" class="sidebar-item-text sidebar-link"><i class="bi bi-clock-history" role="img">
</i> 
 <span class="menu-text">Sixteen years of one paper</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Research context</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-data-hunt.html" class="sidebar-item-text sidebar-link"><i class="bi bi-search" role="img">
</i> 
 <span class="menu-text">The data hunt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-literature.html" class="sidebar-item-text sidebar-link"><i class="bi bi-journal-text" role="img">
</i> 
 <span class="menu-text">Literature &amp; regulation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Sources and reproducibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-sources.html" class="sidebar-item-text sidebar-link"><i class="bi bi-archive" role="img">
</i> 
 <span class="menu-text">Sources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-log.html" class="sidebar-item-text sidebar-link"><i class="bi bi-list-check" role="img">
</i> 
 <span class="menu-text">Work log</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-reproduce.html" class="sidebar-item-text sidebar-link"><i class="bi bi-code-slash" role="img">
</i> 
 <span class="menu-text">Reproduce the study</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-hypotheses-one-by-one" id="toc-the-hypotheses-one-by-one" class="nav-link active" data-scroll-target="#the-hypotheses-one-by-one">The hypotheses, one by one</a></li>
  <li><a href="#was-2026-a-shift-or-a-change-of-shape" id="toc-was-2026-a-shift-or-a-change-of-shape" class="nav-link" data-scroll-target="#was-2026-a-shift-or-a-change-of-shape">Was 2026 a shift or a change of shape?</a></li>
  <li><a href="#what-you-compare-against-decides-what-you-find" id="toc-what-you-compare-against-decides-what-you-find" class="nav-link" data-scroll-target="#what-you-compare-against-decides-what-you-find">What you compare against decides what you find</a></li>
  <li><a href="#how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one" id="toc-how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one" class="nav-link" data-scroll-target="#how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one">How this reading was arrived at, and what it cost each earlier one</a></li>
  <li><a href="#the-institutional-record-since-6-july" id="toc-the-institutional-record-since-6-july" class="nav-link" data-scroll-target="#the-institutional-record-since-6-july">The institutional record since 6 July</a></li>
  <li><a href="#what-to-ask-for-in-order-of-value" id="toc-what-to-ask-for-in-order-of-value" class="nav-link" data-scroll-target="#what-to-ask-for-in-order-of-value">What to ask for, in order of value</a></li>
  <li><a href="#design-questions-for-2027-that-the-data-already-inform" id="toc-design-questions-for-2027-that-the-data-already-inform" class="nav-link" data-scroll-target="#design-questions-for-2027-that-the-data-already-inform">Design questions for 2027 that the data already inform</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-euskadi.html">Evidence and results</a></li><li class="breadcrumb-item"><a href="../chapters/06-interpretation.html">Interpretation &amp; 2027</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Interpretation and the 2027 question</h1>
<p class="subtitle lead">Which explanations survive the evidence, what would decide between the rest, and what to ask for</p>
  <div class="quarto-categories">
    <div class="quarto-category">findings</div>
    <div class="quarto-category">interpretation</div>
    <div class="quarto-category">2027</div>
  </div>
  </div>

<div>
  <div class="description">
    A structured reading of the hypotheses for the 2026 Basque Physics result against the assembled evidence, the institutional narrative after 6 July, and a prioritised list of data requests and design choices for PAU 2027.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-hypotheses-one-by-one" class="level2">
<h2 class="anchored" data-anchor-id="the-hypotheses-one-by-one">The hypotheses, one by one</h2>
<p>The evidence assembled in Chapters 2–5 is observational and the exam changes every year, so nothing below is a causal estimate. But the hypotheses that circulated in July can be sorted by what the data allow.</p>
<p><strong>H1 — “The competency model (RD 534/2024) is to blame.”</strong> <em>Explains 2025, not 2026.</em> The model was applied in all seventeen communities in both years. In 2025 the Física mean fell in 14 of 17, by <span class="math inline">\(-0.81\)</span> on average — Euskadi’s <span class="math inline">\(-0.62\)</span> was below the national move. In 2026 at least six of nine reporting communities rose by <span class="math inline">\(+0.5\)</span> to <span class="math inline">\(+1.1\)</span> under the same model; Euskadi fell <span class="math inline">\(-1.48\)</span>. A national cause cannot produce opposite signs in the same year. The Basque institutions’ July framing (“el nuevo enfoque competencial pasa factura”) is therefore at most a description of 2025. There is a further difficulty with it: the only systematic rating of PAU papers’ competency orientation, covering six communities over 2015–2025 <span class="citation" data-cites="sancheztarazaga2026pau">(<a href="#ref-sancheztarazaga2026pau" role="doc-biblioref">Sánchez-Tarazaga &amp; Gimeno Rovira, 2026</a>)</span>, places País Vasco and Cataluña at the <em>top</em> of the range before the reform, so the Basque papers did not “become competency-based” in 2025 — they were already the most competency-oriented in Spain, and Cataluña, rated alongside them, rose in 2026.</p>
<p><strong>H2 — “The 2026 Basque Física paper was harder, or differently pitched, than its own 2025 paper and than other communities’ 2026 papers.”</strong> <em>Consistent with everything.</em> The cohort-wide displacement of the distribution (<a href="../chapters/04-distributions.html">Chapter 4</a>), the confinement of the damage to Física and Matemáticas II with Química, Biología and Lengua unaffected (<a href="../chapters/05-subjects-sittings.html">Chapter 5</a>), the Catalan mirror image (Física up, Matemàtiques down, same authority, same cohort) and the Canarian coordinators’ own reading of their milder 2025 all point to the paper — its problems, its optionality (two of four problems with no choice in 2026), its marking scheme — as the first-order variable. The July package already noted that the 2026 ordinary paper’s gravitational problem contains a validity issue in its energy comparison. A structured content audit of the 2025 and 2026 papers of the nine communities with a 2026 result was carried out on 19 September and is reported in <a href="../chapters/11-exam-content.html">The papers themselves</a>: none of the six rising communities increased the competency content of its paper (five stayed at zero or fell; Castilla-La Mancha added one obligatory contextualised item), while the Basque paper moved from one competency exercise to half the marks, halved its optionality and changed format at the same time — it is the only paper in the set that changed genre between the two years. The comparison with the 2010–2024 Basque papers is in <a href="../chapters/12-ehu-paper-history.html">Sixteen years of one paper</a>: the 2025 break (no theory questions, new structure, first numerical penalties) was absorbed better than the national average; the 2026 step (competencial half, choice halved, −0.1 list and symbolic-first, syllabus opened) is the one the grades react to. An item-level analysis of the 2026 scripts is the natural continuation.</p>
<p><strong>H3 — “Tribunals marked more severely.”</strong> <em>Possible, unmeasured, and acknowledged by EHU.</em> The rector’s press conference reported “significant variation between evaluation panels” in Física among other subjects <span class="citation" data-cites="argia2026ehu">(<a href="#ref-argia2026ehu" role="doc-biblioref">Argia, 2026</a>)</span>, and the 6 July deck published tribunal-mean ranges for Euskara (2.88–4.43), Lengua (5.80–6.92) and Inglés (6.65–7.56) but not for Física. Rater-severity effects of the size needed to move a subject mean by more than a point are not unknown in Spanish PAU marking <span class="citation" data-cites="veas2025consistency">(<a href="#ref-veas2025consistency" role="doc-biblioref">Veas &amp; López-Pina, 2025</a>)</span>, but the cohort-wide shape of the 2026 distribution says severity, if present, was general rather than confined to a few panels. Only the tribunal-level Física table settles this.</p>
<p><strong>H4 — “The cohort was weaker or differently composed.”</strong> <em>Weak for 2026.</em> Presentation fell 6 % from 2025 and enrolment is unpublished, so a small compositional component cannot be excluded, but the school marks of the preceding cohort were 7.09 with 98 % passing, and the same students’ Química and Biología marks did not move. A weaker cohort does not fail Física and Matemáticas by 1.5 points while holding Química.</p>
<p><strong>H5 — “Students under-prepare Física because the weighting rules make it dispensable.”</strong> <em>Plausible as a slow driver, not as a 2026 trigger.</em> This is the Canarian coordinators’ hypothesis for their own decline (few degrees need a high Física mark; Matemáticas II carries the weighting; Física is examined last on a long day). It fits the ten-year erosion of the top decile better than a one-year fall of 1.5 points, and it is the hypothesis most directly addressable by the Basque ponderación table and the exam timetable for 2027.</p>
<p><strong>H6 — “Language or network bias.”</strong> <em>No evidence either way for Física.</em> The 2010–2022 series shows euskera/castellano differences of a few tenths in both directions and no sign that either network fails Física differentially; EHU’s 2026 bias analysis was run for Euskara II. Nothing published for Física 2026 speaks to this.</p>
<p>The ranking that emerges is H2 first, H3 unresolved and testable, H5 as background, H1 as a description of 2025 only, and H4 and H6 unsupported.</p>
</section>
<section id="was-2026-a-shift-or-a-change-of-shape" class="level2">
<h2 class="anchored" data-anchor-id="was-2026-a-shift-or-a-change-of-shape">Was 2026 a shift or a change of shape?</h2>
<p>The hypotheses above divide along a line the published aggregates can be made to test. A harder paper or a uniformly stricter marking scheme moves the whole distribution down together. A change in who sits the exam, or a marking change that bites only at the bottom, changes its <em>shape</em> — it thins the pass region without touching the top, or the reverse. The published data carry three summaries of the same distribution — the mean, the pass rate, and the share in the 8–10 band — and the second and third are near-deterministic functions of the first: across seventeen communities and eleven years the correlations are <span class="math inline">\(r = 0.974\)</span> and <span class="math inline">\(r = 0.961\)</span>. A scatter of pass rate against mean therefore mostly redraws arithmetic. What carries information is the <em>residual</em>: a cohort sitting off the common locus has a differently shaped distribution, not merely a lower one.</p>
<div id="fig-locus" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-locus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig16_shape_locus.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-locus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <strong>a, b</strong> — Pass rate and the 8–10 band share against the mean Física mark, ordinary sitting, specific phase, seventeen communities 2015–2025 (n = 187 region-years, Ministry EPAU). The line is a quadratic fit; the pale band is ±2 residual standard deviations (1.9 pp left, 2.7 pp right) and the darker band the 95 % confidence interval of the fit itself, which widens where the region-years thin out. Hollow grey markers are 2015–16, the years in which Física could still be sat in the general phase; from 2017 LOMCE left it in the voluntary phase only and the presented cohort grew from 30,839 to 49,010. The Euskadi trajectory is drawn as a connected path. ULL and ULPGC 2026 are observed histograms, on a denominator of exams sat rather than presented. The EHU 2026 marker is hollow because its band share is a Beta fitted to the published mean, pass rate and zero count, so on these axes it can only restate them. The tinted strip marks the part of the mean axis where only two of the 187 region-years lie, and where all three 2026 cohorts sit. <strong>c, d</strong> — the distribution of each joint panel’s own vertical variable, with a normal of the same mean and standard deviation drawn for comparison and the 2026 values marked as vertical rules. These are deliberately not the distribution of the mean, which is the same variable on both horizontal axes: the pass rate is symmetric and normality cannot be rejected, whereas the 8–10 share is strongly right-skewed, as a tail quantity bounded at zero must be.
</figcaption>
</figure>
</div>
<p>Two things follow, and the first is a precondition for the second.</p>
<p><strong>The locus is a property of the marking scale, not of the cohort.</strong> Física’s examined population changed substantially inside this window: until 2016 it could be taken in the general phase, from 2017 LOMCE left it voluntary only, and the number presented grew by 59 % — from 30,839 to 49,010. If the mapping from mean to pass rate depended on who sits the paper, it should step at that boundary. It does not: comparing residuals before and after 2017, the pass panel gives <span class="math inline">\(p = 0.40\)</span> and the top-band panel <span class="math inline">\(p = 0.12\)</span> once the two COVID sittings are excluded. On the full series the top-band difference does reach <span class="math inline">\(p = 0.008\)</span>, but that result is carried by 2020, whose residual of <span class="math inline">\(+3.6\)</span> pp is the largest in the panel, and it is the COVID year — so the honest reading is the conservative one. In <a href="#fig-locus" class="quarto-xref">Figure&nbsp;1</a> the hollow 2015–16 markers interleave with the later ones along the same curve. That stability is what licenses reading a 2026 point off the locus at all.</p>
<p><strong>Where 2026 can be observed, it is a location shift — but the test is weaker than it looks.</strong> The only 2026 cohorts with a published histogram are the two Canarian universities, and both land on the locus: ULL at <span class="math inline">\(-0.08\)</span> SD on the pass panel and <span class="math inline">\(+0.65\)</span> SD on the top band, ULPGC at <span class="math inline">\(-1.04\)</span> and <span class="math inline">\(+0.24\)</span>, against a historical scatter that reaches <span class="math inline">\(\pm 3.5\)</span> SD. Their distributions are the same shape as everyone else’s at that mean — simply further down it. Nothing was thinned selectively: the top of the Canarian cohort fell with the rest.</p>
<p>How much that settles depends on how much evidence sits where these cohorts fall, and the answer is honestly very little. The 187 region-year means pile up between 5.0 and 6.5 — they are themselves right-skewed and heavy-tailed rather than normal (skew <span class="math inline">\(+0.60\)</span>, excess kurtosis <span class="math inline">\(+0.88\)</span>; Shapiro–Wilk <span class="math inline">\(p = 0.00017\)</span>, Anderson–Darling <span class="math inline">\(A^2 = 2.06\)</span> against a 5 % critical value of <span class="math inline">\(0.77\)</span>). Only <strong>2 of 187</strong> sit below 4.5 — the tinted strip in panels a and b of <a href="#fig-locus" class="quarto-xref">Figure&nbsp;1</a> — and none within <span class="math inline">\(\pm 0.25\)</span> of where ULL (4.08) and the Basque cohort (3.99) fall. The curve there is therefore an extrapolation from the body of the data, and its own 95 % interval is <span class="math inline">\(\pm 1.41\)</span> pp at mean 4.08 against <span class="math inline">\(\pm 0.32\)</span> pp at mean 6.0, which is why the figure draws that interval as well as the flat scatter band. ULL’s residual of <span class="math inline">\(-0.16\)</span> pp sits comfortably inside the uncertainty of the very curve it is measured against.</p>
<p>The two panels are also not equally well-behaved, and panels c and d of <a href="#fig-locus" class="quarto-xref">Figure&nbsp;1</a> separate them because they give opposite answers. The pass rate is symmetric and close to normal (skew <span class="math inline">\(+0.01\)</span>, excess kurtosis <span class="math inline">\(+0.39\)</span>; Shapiro–Wilk <span class="math inline">\(p = 0.096\)</span>, Anderson–Darling <span class="math inline">\(A^2 = 0.58\)</span>, below the critical value — normality cannot be rejected). The 8–10 share is not (skew <span class="math inline">\(+1.29\)</span>, excess kurtosis <span class="math inline">\(+1.83\)</span>; <span class="math inline">\(p = 8 \times 10^{-10}\)</span>, <span class="math inline">\(A^2 = 5.80\)</span>). That is what one should expect of a tail quantity pressed against zero, but it has a practical consequence: a residual quoted “in standard deviations” assumes roughly symmetric scatter, so the SD units are trustworthy on the pass panel and only indicative on the top-band panel. The top-band residuals quoted above should be read as directional, not as calibrated probabilities.</p>
<p>The consequence is a limit on power, not a reversal of sign. Nothing in the 2026 data indicates a change of shape, and a <em>large</em> one would still have shown: a cohort that had thinned only at the bottom would sit several points off the curve, far outside even the widened interval. But a modest reshaping at mean 4 could not be detected with two historical neighbours, so “consistent with a pure location shift” is the correct reading, and “demonstrated to be one” is not.</p>
<p>That bears on the ranking above in one direction and one only. It is evidence against <strong>H4</strong>: a cohort that had become differently composed would be expected to sit off the locus, and Canarias does not. It does not discriminate between <strong>H2</strong> and <strong>H3</strong>, because a harder paper and a uniformly severer marking scheme produce the same signature here — both move the distribution without reshaping it. What it weighs against is any mechanism acting <em>strongly</em> and selectively on one part of the range.</p>
<p>The Basque case cannot be put to this test with what is published. The 2026 band shares shown in <a href="../chapters/04-distributions.html">Chapter 4</a> are output of the Beta fitted to the mean, the pass rate and the zero count; plotting them here as evidence would be circular, which is why the EHU 2026 marker in <a href="#fig-locus" class="quarto-xref">Figure&nbsp;1</a> is drawn hollow. Its apparent residual of <span class="math inline">\(-0.05\)</span> SD on the top band is the model agreeing with itself and should not be read as a result. Resolving the Basque case the same way needs one thing: the observed 2026 grade histogram, which is item 2 of the data requests below.</p>
<p>One data caveat surfaced in building this. The Ministry’s own cube is internally inconsistent for two of the 187 region-years — Galicia 2015 and 2016 — where the published pass rate and the published <span class="math inline">\([0,5)\)</span> share disagree by 5.64 and 4.48 pp; these are the two years in which Física appeared in both phases, so the cells are carried on different bases. Every band row sums to 100.0 and the remaining 185 agree to rounding, so the two points are kept rather than discarded, and they are recorded in <code>data/analysis/shape_locus.json</code>.</p>
</section>
<section id="what-you-compare-against-decides-what-you-find" class="level2">
<h2 class="anchored" data-anchor-id="what-you-compare-against-decides-what-you-find">What you compare against decides what you find</h2>
<p>Every number in this report is a change measured from some reference point, and the reference point is almost never argued for. It is usually the previous year, because that is what the sources publish and what the press quotes. Reading the same series against a different baseline does not merely adjust the size of the effect — in this case it reverses the sign of the national story.</p>
<div id="fig-frames" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig17_reference_frames.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: <strong>a</strong> — mean Física mark, ordinary sitting, for the nine communities that have published a 2026 result (the same nine in every year, so nothing here depends on which regions reported) and for Euskadi separately, against their own 2015–2019 baselines. The shaded years are the COVID-era plateau. Dotted segments carry 2026, which is not in the ministry cube and is assembled in this study. <strong>b</strong> — the same underlying data measured five ways, with the conclusion each measurement invites.
</figcaption>
</figure>
</div>
<p>The pattern in panel a of <a href="#fig-frames" class="quarto-xref">Figure&nbsp;2</a> is not a decline. It is a plateau that ended. The nine communities sit +0.4 to +1.0 above their pre-COVID baseline in every year from 2020 to 2024, peaking in 2021, and then return to it in 2025. The relaxation did not decay gradually, which is what “returning to normal” would look like; it held for three full years after the peak — 2022, 2023 and 2024 are all about +0.65 — and then ended in a single step. Whatever produced the COVID-era marking regime was still producing it in 2024, and stopped in 2025.</p>
<p>That is enough to change the reading of three separate claims in this report.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Measured as</th>
<th>Change</th>
<th>Invites the conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024 → 2025, nine communities</td>
<td><span class="math inline">\(-0.65\)</span></td>
<td>“A national collapse; the competency model bites.”</td>
</tr>
<tr class="even">
<td>2025 → 2026, nine communities</td>
<td><span class="math inline">\(+0.17\)</span></td>
<td>“A recovery everywhere, so 2026 is a Basque problem.”</td>
</tr>
<tr class="odd">
<td>2015–19 baseline → 2026, nine communities</td>
<td><span class="math inline">\(+0.02\)</span></td>
<td>“Nothing has happened; Spain is where it was a decade ago.”</td>
</tr>
<tr class="even">
<td>2025 → 2026, Euskadi</td>
<td><span class="math inline">\(-1.48\)</span></td>
<td>“The Basque fall is one and a half points.”</td>
</tr>
<tr class="odd">
<td>2015–19 baseline → 2026, Euskadi</td>
<td><span class="math inline">\(-1.93\)</span></td>
<td>“The Basque fall is nearly two points — a third larger.”</td>
</tr>
</tbody>
</table>
<p>Rows one and three are the uncomfortable pair. Both are true of the same nine communities and the same ministry series, and they are not reconcilable as statements of fact about “what happened to Physics in Spain”: one says the subject collapsed, the other that it is exactly where it was in 2015–2019, <span class="math inline">\(+0.02\)</span> away after eleven years. The contradiction is entirely in the choice of reference year, and the year-on-year framing is the one that misleads, because 2024 was not a normal year to measure from.</p>
<p>This weakens <strong>H1</strong> further than <a href="#the-hypotheses-one-by-one">the hypothesis review above</a> already did. That section could say only that the competency model explains 2025 and not 2026. Measured from the pre-COVID baseline, it does not clearly explain 2025 either: the 2025 sitting did not fall below the historical norm, it returned to it. A model introduced in 2025 that leaves the national mean 0.15 below where it sat in 2015–2019 is not obviously doing anything at all to the national mean; the visible <span class="math inline">\(-0.81\)</span> is the withdrawal of five years of COVID-era leniency, and would have appeared in 2025 under any marking scheme that stopped being lenient.</p>
<p>It also makes the Basque case worse, not better. The headline everyone quoted is <span class="math inline">\(-1.48\)</span>, measured from 2025. Against Euskadi’s own pre-COVID baseline of 5.92 the 2026 fall is <span class="math inline">\(-1.93\)</span> — a third larger than the number in circulation — because 2025 was already 0.45 below that baseline. The Basque series did not fall once; it fell twice, and only the second fall was reported as news.</p>
<p>None of this is a criticism of the sources. The Ministry publishes years, the universities publish years, and a year-on-year change is the only comparison most readers can make from what is published. But it means the honest form of every claim in this report carries its reference point on its face, and that the three sentences most likely to be quoted from this study — “the 2025 fall was national”, “the 2026 fall is regional”, “Euskadi fell 1.48” — are each true only in the frame that produced them.</p>
</section>
<section id="how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one" class="level2">
<h2 class="anchored" data-anchor-id="how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one">How this reading was arrived at, and what it cost each earlier one</h2>
<p>The previous section shows that the frame decides the answer. This one records the order in which the frames were tried, because the sequence is itself a finding: the analysis in this chapter was not assembled in one pass, and four of its six steps damaged the conclusion that motivated them.</p>
<div id="fig-path" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig18_analysis_path.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: <strong>a</strong> — the two headline quantities under three successive framings, all computed on the same nine communities. The national number does not merely shrink as the frame widens; it changes sign. <strong>b</strong> — the order the questions were asked in, the claim each step produced, and what the later steps did to it. Every value is read from the JSON written by the script that computed it, so the figure cannot drift from the analysis it narrates.
</figcaption>
</figure>
</div>
<p>The sequence in panel b of <a href="#fig-path" class="quarto-xref">Figure&nbsp;3</a> ran as follows.</p>
<p><strong>Step 1</strong> was the July framing, taken from the institutions: Física fell 1.48 points and the competency model is to blame. <strong>Step 2</strong>, the cross-section of 2026 in <a href="../chapters/03-spain-2026.html">Chapter 3</a>, overturned it — six of nine communities rose in 2026 under the same model, and a national cause cannot produce opposite signs in the same year. That is the step that produced this chapter’s original hypothesis ranking.</p>
<p><strong>Step 3</strong> asked whether the 2026 fall was a change of shape or of position, and answered that Canarias 2026 sits on the historical locus: the distribution moved down without being reshaped. <strong>Step 4</strong> then asked how much evidence supports the locus where those cohorts fall, and found almost none — two region-years of 187 below mean 4.5, and a fit whose own interval there is four times its width at the centre of the data. The step-3 claim survived, but only as <em>consistent with</em> a location shift rather than a demonstration of one. <strong>Step 5</strong> decoupled the two distributions and found the 8–10 share strongly non-normal, so the standard-deviation units in which the step-3 residuals had been quoted are not calibrated on that panel, and those residuals are directional only.</p>
<p><strong>Step 6</strong> re-baselined to the pre-COVID norm and did the most damage of all — not to step 3, but to step 2. Step 2’s reasoning depends on 2025 having been a national collapse that the competency model could be blamed for. Measured from 2015–2019 the 2025 sitting was not a collapse: it was a return to the norm after a five-year plateau, and the nine communities finish 2026 <span class="math inline">\(+0.02\)</span> from where they started in 2015. So the hypothesis ranking earlier in this chapter, which demoted H1 to “a description of 2025”, now has to demote it further: there is no national 2025 anomaly for it to describe.</p>
<p>Three things follow that are worth stating plainly, because they bear on how this report should be read rather than on what it found.</p>
<p>The first is that every step which <em>narrowed</em> the claim came from asking about the data rather than about the subject — where the observations actually lie, whether the distributions are what the summary statistics assume, what the baseline year happens to be. None of the four weakening steps required new data. They required looking at the data that was already in hand from a different angle, and each angle was one an unhurried reader would eventually have asked about.</p>
<p>The second is that the two surviving strong claims are the narrow ones. That Euskadi 2026 is anomalous survives every reframing and gets <em>larger</em> under the honest baseline, from <span class="math inline">\(-1.48\)</span> to <span class="math inline">\(-1.93\)</span>. That the 2026 fall is confined to Física and Matemáticas II while Química and Biología held (<a href="../chapters/05-subjects-sittings.html">Chapter 5</a>) is untouched by any of this, because it is a within-cohort comparison and carries no baseline choice at all. Comparisons that do not need a reference point are the ones that did not move.</p>
<p>The third is the uncomfortable one. If this analysis had stopped at step 2 — which is where a competent and honest reading of the published sources naturally stops — it would have produced a coherent, quotable and partly wrong account: a national collapse in 2025 caused by the reform, and a separate Basque failure in 2026. Both halves of that sentence are artefacts of measuring from the previous year. Nothing in the published sources signals that the previous year was abnormal; the plateau is only visible once eleven years are put side by side on one axis, which no institutional publication does. That is not a failure of the sources, but it is a reason to treat any single-year comparison in this domain, including the ones in this report’s own earlier chapters, as provisional until it has been checked against a decade.</p>
</section>
<section id="the-institutional-record-since-6-july" class="level2">
<h2 class="anchored" data-anchor-id="the-institutional-record-since-6-july">The institutional record since 6 July</h2>
<ul>
<li><strong>6 July</strong>, EHU: Física figures published as a counter-example in the Euskara controversy; tribunal data handed to the Education Department; anomalous tribunal values reported for eleven subjects including Física <span class="citation" data-cites="ehu2026campusa argia2026ehu">(<a href="#ref-argia2026ehu" role="doc-biblioref">Argia, 2026</a>; <a href="#ref-ehu2026campusa" role="doc-biblioref">Euskal Herriko Unibertsitatea, 2026</a>)</span>.</li>
<li><strong>7 July</strong>, Science and Universities Counsellor: admits a “déficit de confianza, fundamentado o no fundamentado” in the marking system; floats multi-marker models; ≈ 40 judicial appeals by students with very low marks.</li>
<li><strong>7 July</strong>, extraordinary sitting: 71.4 % global pass (90.6 % in 2025); no Física figure.</li>
<li><strong>8–10 July</strong>: 12 000-signature faculty manifesto in support of markers; EHU appeals the court measures on the Euskara marks; press notes that “los ceros en Física duplican a los de Euskera”.</li>
<li><strong>12 July</strong>, Education Counsellor Pedrosa <span class="citation" data-cites="pedrosa2026entrevista">(<a href="#ref-pedrosa2026entrevista" role="doc-biblioref">Alonso, 2026</a>)</span>: the Department has only the EHU report, will request more data, will review all subjects for 2027 “a corto plazo”, has no diagnosis yet, and does not hold other communities’ data.</li>
<li><strong>30 July</strong>, Galicia (context): after errors in three papers, the Xunta announces peer review of papers and double marking for 2027 — the single-author, no-external-review failure mode that any Basque audit should check for.</li>
<li><strong>7 September</strong>: nothing sent to schools for PAU 2027 beyond the Euskara II instructions; “2027 será un año de ajuste técnico” and the competency model is to be fully deployed in 2028.</li>
</ul>
</section>
<section id="what-to-ask-for-in-order-of-value" class="level2">
<h2 class="anchored" data-anchor-id="what-to-ask-for-in-order-of-value">What to ask for, in order of value</h2>
<ol type="1">
<li><strong>Física by tribunal, 2025 and 2026</strong>: <span class="math inline">\(n_j\)</span>, <span class="math inline">\(\bar{x}_j\)</span>, <span class="math inline">\(s_j\)</span> and the school composition of each tribunal’s scripts. EHU computed this. It separates H2 from H3 in one table.</li>
<li><strong>The full Física grade histogram, 2024–2026</strong>, in one-point bands with zeros and tens, as ULL and ULPGC publish routinely. It replaces the model of <a href="../chapters/04-distributions.html">Chapter 4</a> with data.</li>
<li><strong>July 2026 Física</strong>: presented, passed, mean. Its position relative to the June result tells whether the July paper was pitched like the June one.</li>
<li><strong>Revision statistics for Física 2026</strong>: requests, share raised, mean change. Published for four subjects, not for the subject with the lowest mean.</li>
<li><strong>Física by sex, language and territory for 2023–2026</strong>, the breakdowns the annual reports carried until 2022.</li>
<li><strong>Problem-level marks</strong> (four problems, options a/b) for a sample of scripts: this is the item-level evidence that distinguishes “the paper was hard” from “the paper was unanswerable”, and it is what the Canarian subcommittee planned for 2026.</li>
</ol>
</section>
<section id="design-questions-for-2027-that-the-data-already-inform" class="level2">
<h2 class="anchored" data-anchor-id="design-questions-for-2027-that-the-data-already-inform">Design questions for 2027 that the data already inform</h2>
<ul>
<li><strong>Optionality.</strong> The 2026 Basque paper fixed problems 1 and 2 with no alternative (optional share 75 % → 50 %; Canarias, the other community that cut choice by ≥ 25 points, also fell — <a href="../chapters/11-exam-content.html">Chapter 11</a>). The COVID years (single super-option, choice among questions) produced the highest means in the series; the 2025–26 reduction of choice coincides with the two lowest. Restoring a choice within problems 1–2 is the cheapest lever with a documented effect.</li>
<li><strong>Calibration against a reference.</strong> The Ministry cube gives, for every subject, community and year, a full distribution; a target distribution for Física (for example the 2017–2024 Basque band structure, <span class="math inline">\([0,5)\)</span> ≈ 30 %, <span class="math inline">\([9,10]\)</span> ≈ 15 %) can be written into the coordination instructions and checked against a pre-test of the paper on a sample of Bachillerato students, as some communities’ ponencias already do informally.</li>
<li><strong>The threshold.</strong> The Canarian histograms show that in 2026 the customary rounding of borderline scripts to 5 vanished. Whether that is desirable is a policy question; that it moves the pass rate by 5–8 points is an empirical one.</li>
<li><strong>Order of exams.</strong> Física is sat on the last slot of the science day in several communities; the Tenerife minutes name this explicitly. The Basque timetable is a free parameter.</li>
<li><strong>Second marking.</strong> Galicia’s 2027 reform (double marking, external review of papers) is the model that the “déficit de confianza” language of July points toward; Veas &amp; López-Pina’s Rasch equating in Comunitat Valenciana is the statistical complement.</li>
</ul>
<p>None of these requires new data to be argued; all of them would be sharpened by the six items above.</p>



</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-pedrosa2026entrevista" class="csl-entry" role="listitem">
Alonso, I. (2026). <em>Bego<span>ñ</span>a pedrosa: <span>“Analizaremos los factores que han podido influir”</span> (interview with the basque education counsellor)</em>. Noticias de Gipuzkoa, 12 July 2026. <a href="https://www.noticiasdegipuzkoa.eus/sociedad/2026/07/12/analizaremos-factores-han-podido-influir-11316893.html">https://www.noticiasdegipuzkoa.eus/sociedad/2026/07/12/analizaremos-factores-han-podido-influir-11316893.html</a>
</div>
<div id="ref-argia2026ehu" class="csl-entry" role="listitem">
Argia. (2026). <em><span>EHUk</span> emandako datuek azaldu dute euskarako notak ez direla salbuespen izan</em>. Argia, 6–8 July 2026. <a href="https://www.argia.eus/albistea/ehuk-emandako-datuek-azaldu-dute-euskarako-notak-ez-direla-salbuespen-izan">https://www.argia.eus/albistea/ehuk-emandako-datuek-azaldu-dute-euskarako-notak-ez-direla-salbuespen-izan</a>
</div>
<div id="ref-ehu2026campusa" class="csl-entry" role="listitem">
Euskal Herriko Unibertsitatea. (2026). <em><span>EHU</span> concluye que la asignatura <span class="nocase">Euskara y Literatura II</span> no presenta un comportamiento excepcional cuando se analizan de forma global los resultados de la <span>PAU</span></em>. Campusa, 6 July 2026. <a href="https://www.ehu.eus/es/web/campusa/-/ehu-concluye-que-la-asignatura-euskara-y-literatura-ii-no-presenta-un-comportamiento-excepcional-cuando-se-analizan-de-forma-global-los-resultados-de-la-pau">https://www.ehu.eus/es/web/campusa/-/ehu-concluye-que-la-asignatura-euskara-y-literatura-ii-no-presenta-un-comportamiento-excepcional-cuando-se-analizan-de-forma-global-los-resultados-de-la-pau</a>
</div>
<div id="ref-sancheztarazaga2026pau" class="csl-entry" role="listitem">
Sánchez-Tarazaga, L., &amp; Gimeno Rovira, J. A. (2026). <em><span></span>C<span>ó</span>mo compatibilizar un bachillerato que busca habilidades cr<span>í</span>ticas con una <span>PAU</span> que todav<span>í</span>a prima la memorizaci<span>ó</span>n?</em> The Conversation (Espa<span>ñ</span>a), 2 June 2026. <a href="https://doi.org/10.64628/AAO.atrdhyeha">https://doi.org/10.64628/AAO.atrdhyeha</a>
</div>
<div id="ref-veas2025consistency" class="csl-entry" role="listitem">
Veas, A., &amp; López-Pina, J.-A. (2025). Consistency analysis of assessment boards in university entrance examinations in <span>Spain</span>. <em>European Journal of Investigation in Health, Psychology and Education</em>, <em>15</em>(6), 102. <a href="https://doi.org/10.3390/ejihpe15060102">https://doi.org/10.3390/ejihpe15060102</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/05-subjects-sittings.html" class="pagination-link" aria-label="Subjects &amp; participation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Subjects &amp; participation</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/11-exam-content.html" class="pagination-link" aria-label="The papers themselves">
        <span class="nav-page-text">The papers themselves</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Independent analysis prepared 18 September 2026 · all figures reproducible from <code>scripts/</code></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Data: EHU, SIIU/EPAU, Generalitat de Catalunya, GVA, Junta de Andalucía, CM, Uniovi, UCLM, ULL, ULPGC, UNIZAR, UPNA, UMU, UC, CiUG, UR</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>