<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-19">
<meta name="description" content="A hand-coded comparison of the ordinary-sitting Física papers of nine communities for 2025 and 2026 — structure, optionality and the competency criteria of every exercise — set against the change in the mean grade.">

<title>The papers themselves – PAU Física 2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/01-data-hunt.html" rel="next">
<link href="../chapters/06-interpretation.html" rel="prev">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-f9bd6e3554e59631090df615afca0c0c.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6a3ca9ab01c0de29e82d083f58a2981d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-f9bd6e3554e59631090df615afca0c0c.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-dd0417445b71b53e57531a9890920c9d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-c07cefc3e6b4ffd37a3d4fc762d735ef.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dd0417445b71b53e57531a9890920c9d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/favicon.svg" alt="PAU Física" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PAU Física 2026</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../chapters/02-euskadi.html" aria-current="page"> 
<span class="menu-text">Findings</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/01-data-hunt.html"> 
<span class="menu-text">Data hunt</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/08-sources.html"> 
<span class="menu-text">Sources &amp; log</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img" aria-label="Repository (placeholder)">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="" title="Theme" class="quarto-navigation-tool px-1" aria-label="Theme"><i class="bi bi-moon"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-euskadi.html">Findings</a></li><li class="breadcrumb-item"><a href="../chapters/11-exam-content.html">The papers themselves</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Findings</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-euskadi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Euskadi 2010–2026: the series and the break</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-spain-2026.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spain 2026: nine communities, three directions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The shape of the collapse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-subjects-sittings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Subjects, sittings, participation and groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-interpretation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interpretation and the 2027 question</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-exam-content.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">The papers themselves</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-data-hunt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The data hunt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literature: what exists and what does not</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Sources &amp; log</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-log.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Log</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-reproduce.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methods, checks and reproduction</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-question" id="toc-the-question" class="nav-link active" data-scroll-target="#the-question"><span class="header-section-number">1</span> The question</a></li>
  <li><a href="#the-coding-scheme" id="toc-the-coding-scheme" class="nav-link" data-scroll-target="#the-coding-scheme"><span class="header-section-number">2</span> The coding scheme</a></li>
  <li><a href="#structure-and-content-of-the-eighteen-papers" id="toc-structure-and-content-of-the-eighteen-papers" class="nav-link" data-scroll-target="#structure-and-content-of-the-eighteen-papers"><span class="header-section-number">3</span> Structure and content of the eighteen papers</a></li>
  <li><a href="#what-the-papers-of-the-rising-communities-look-like" id="toc-what-the-papers-of-the-rising-communities-look-like" class="nav-link" data-scroll-target="#what-the-papers-of-the-rising-communities-look-like"><span class="header-section-number">4</span> What the papers of the rising communities look like</a></li>
  <li><a href="#what-the-papers-of-the-falling-communities-look-like" id="toc-what-the-papers-of-the-falling-communities-look-like" class="nav-link" data-scroll-target="#what-the-papers-of-the-falling-communities-look-like"><span class="header-section-number">5</span> What the papers of the falling communities look like</a></li>
  <li><a href="#paper-change-against-grade-change" id="toc-paper-change-against-grade-change" class="nav-link" data-scroll-target="#paper-change-against-grade-change"><span class="header-section-number">6</span> Paper change against grade change</a></li>
  <li><a href="#a-note-on-the-uji-rating" id="toc-a-note-on-the-uji-rating" class="nav-link" data-scroll-target="#a-note-on-the-uji-rating"><span class="header-section-number">7</span> A note on the UJI rating</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-euskadi.html">Findings</a></li><li class="breadcrumb-item"><a href="../chapters/11-exam-content.html">The papers themselves</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">The papers themselves</h1>
<p class="subtitle lead">How competency-oriented were the 2025 and 2026 Física exams in the communities that rose and in those that fell?</p>
  <div class="quarto-categories">
    <div class="quarto-category">findings</div>
    <div class="quarto-category">exams</div>
  </div>
  </div>

<div>
  <div class="description">
    A hand-coded comparison of the ordinary-sitting Física papers of nine communities for 2025 and 2026 — structure, optionality and the competency criteria of every exercise — set against the change in the mean grade.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-question" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-question"><span class="header-section-number">1</span> The question</h2>
<p>The comparative chapters establish that between 2025 and 2026 the Física mean rose in six of the nine communities with a published figure and fell in three, Euskadi most of all. One reading of that pattern, put forward when this chapter was commissioned, is that the Basque paper moved further towards the competency model than the others: in 2025 the EHU paper had one competency-style exercise out of four blocks; in 2026 it had two obligatory competency exercises out of four, that is half of the marks. If the communities that rose did not move at all, the “competency” label would be doing very different work in different places, and the 2026 Basque result would be at least partly a <em>paper-design</em> event rather than a <em>cohort</em> event.</p>
<p>That is a question about the exams, not about the results, so this chapter reads the exams. The eighteen ordinary-sitting papers (nine communities × two years) were collected — the <a href="../chapters/01-data-hunt.html">Data hunt</a> chapter and the <a href="../chapters/08-sources.html">source registry</a> say where each came from — and every exercise, with every option counted separately, was coded on the same criteria that the EHU competency-conversion scheme uses. The coding file is <code>data/exam_coding_2025_2026.csv</code> (146 rows); the script that turns it into the tables and figures of this chapter is <code>scripts/07_exam_coding.py</code>.</p>
</section>
<section id="the-coding-scheme" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="the-coding-scheme"><span class="header-section-number">2</span> The coding scheme</h2>
<p>Each item (an exercise, or one option of an exercise) carries the structural facts — block, obligatory or optional, number of options in its slot, points — and six content codes:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ctx</code></td>
<td>0 no context · 1 <em>decorative</em> (a named real object or setting, but the tasks are the standard calculation and the context adds no data, claim or decision) · 2 <em>substantive</em> (a scenario, role, headline, regulation or design specification that drives the tasks or must be interpreted)</td>
</tr>
<tr class="even">
<td><code>app</code></td>
<td>a technological, medical, social or environmental application is named</td>
</tr>
<tr class="odd">
<td><code>explain</code></td>
<td>at least one section demands a qualitative explanation or justification in words that is not itself a calculation</td>
</tr>
<tr class="even">
<td><code>graph</code></td>
<td>the student must read data off a given graph, table, photograph or figure</td>
</tr>
<tr class="odd">
<td><code>draw</code></td>
<td>the student must produce a diagram (ray tracing, vector scheme, force diagram, sketch of a curve)</td>
</tr>
<tr class="even">
<td><code>evaluate</code></td>
<td>a numerical result must be judged against a real-world criterion, claim, specification or regulation (“¿te parece realista?”, “cumple el requisito?”, “¿está protegida?”)</td>
</tr>
</tbody>
</table>
<p>From these, an item is <strong>competency-style</strong> when it has a substantive context <em>and</em> an explain or an evaluate section — the minimum that the EHU scheme (real-world narrative, qualitative reasoning, evaluation) and the UJI study’s three criteria (contextualised, productive, complex) have in common. Two paper-level measures follow. The <em>expected share of competency points</em> assumes a student who chooses options at random,</p>
<p><span class="math display">\[
E_{\text{comp}} \;=\; \frac{1}{10}\sum_{i} \frac{p_i\,c_i}{n_i}\times 100,
\]</span></p>
<p>where <span class="math inline">\(p_i\)</span> are the points of item <span class="math inline">\(i\)</span>, <span class="math inline">\(n_i\)</span> the number of options in its slot (1 when obligatory) and <span class="math inline">\(c_i\in\{0,1\}\)</span> its competency flag; and the <em>guaranteed</em> competency points are those of obligatory items only, which no choice of options can avoid. The <em>optional share</em> of a paper is the fraction of its 10 points that sit in slots where the student chooses. A last, cruder measure, <em>criteria per item</em>, is the mean number of the five EHU criteria (substantive context, application, explain, graph, evaluate) met by an item.</p>
<p>Three caveats before the numbers. The coding is one reader’s, made in one pass with the scheme fixed in advance; borderline calls are recorded in the <code>note</code> column so they can be disputed. Only the ordinary sitting is coded. And nothing here measures <em>difficulty</em> — a naked, context-free question can be very hard and a contextualised one very easy; the chapter is about the <em>type</em> of paper, which is what the question asked.</p>
</section>
<section id="structure-and-content-of-the-eighteen-papers" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="structure-and-content-of-the-eighteen-papers"><span class="header-section-number">3</span> Structure and content of the eighteen papers</h2>
<div id="tbl-format" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-format-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Format of each ordinary paper: items offered and answered, share of the 10 points in slots where the student chooses, and points that are obligatory. File: <code>data/exam_structure_2025_2026.csv</code>.
</figcaption>
<div aria-describedby="tbl-format-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Paper</th>
<th>Structure</th>
<th>Items offered</th>
<th>Items answered</th>
<th>Optional %</th>
<th>Obligatory pts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Andalucía 2025</td>
<td>Four blocks: a) obligatory (1) + choose b1/b2 (1.5)</td>
<td>12</td>
<td>8</td>
<td>60</td>
<td>4.0</td>
</tr>
<tr class="even">
<td>Andalucía 2026</td>
<td>Block A obligatory (a + b); blocks B-D: choose a1/a2 and b1/b2</td>
<td>14</td>
<td>8</td>
<td>75</td>
<td>2.5</td>
</tr>
<tr class="odd">
<td>Asturias 2025</td>
<td>Answer any 5 of 8 questions (2 each)</td>
<td>8</td>
<td>5</td>
<td>100</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Asturias 2026</td>
<td>Answer any 5 of 8 questions (2 each)</td>
<td>8</td>
<td>5</td>
<td>100</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>Canarias 2025</td>
<td>Four blocks: choose option A or B (2.5 each)</td>
<td>8</td>
<td>4</td>
<td>100</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Canarias 2026</td>
<td>Obligatory 1a (1.5) and 2 (1.5); the rest in pairs (2.5/3/3/1.5 per block)</td>
<td>12</td>
<td>7</td>
<td>70</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td>Castilla-La Mancha 2025</td>
<td>Four questions, each: answer 2 of 3 sections</td>
<td>4</td>
<td>4</td>
<td>100</td>
<td>10.0</td>
</tr>
<tr class="even">
<td>Castilla-La Mancha 2026</td>
<td>A obligatory (2); B, C: fixed 0.5 + choose 1 of 2 (2.5); D: choose 1 of 2 (2)</td>
<td>9</td>
<td>6</td>
<td>70</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td>Cataluña 2025</td>
<td>Four exercises; options A/B in ex. 2 and 3</td>
<td>6</td>
<td>4</td>
<td>50</td>
<td>5.0</td>
</tr>
<tr class="even">
<td>Cataluña 2026</td>
<td>Four exercises; options A/B in ex. 1 and 4</td>
<td>6</td>
<td>4</td>
<td>50</td>
<td>5.0</td>
</tr>
<tr class="odd">
<td>Comunitat Valenciana 2025</td>
<td>Six questions; question 2 obligatory (1.5); the other five A/B</td>
<td>11</td>
<td>6</td>
<td>85</td>
<td>1.5</td>
</tr>
<tr class="even">
<td>Comunitat Valenciana 2026</td>
<td>Four apartados; apartado 1 single option (2); 2-4 A/B (3/3/2)</td>
<td>7</td>
<td>4</td>
<td>80</td>
<td>2.0</td>
</tr>
<tr class="odd">
<td>Extremadura 2025</td>
<td>Block A obligatory; blocks B-D: choose 1 of 2</td>
<td>7</td>
<td>4</td>
<td>75</td>
<td>2.5</td>
</tr>
<tr class="even">
<td>Extremadura 2026</td>
<td>Block A obligatory; blocks B-D: choose 1 of 2</td>
<td>7</td>
<td>4</td>
<td>75</td>
<td>2.5</td>
</tr>
<tr class="odd">
<td>Madrid 2025</td>
<td>Block 1 obligatory; blocks 2-4: choose A/B</td>
<td>7</td>
<td>4</td>
<td>75</td>
<td>2.5</td>
</tr>
<tr class="even">
<td>Madrid 2026</td>
<td>Block 1 obligatory (graph item); blocks 2-4: choose A/B</td>
<td>7</td>
<td>4</td>
<td>75</td>
<td>2.5</td>
</tr>
<tr class="odd">
<td>País Vasco 2025</td>
<td>Block A obligatory; blocks B, C, D: choose 1 of 2 (2.5 each)</td>
<td>7</td>
<td>4</td>
<td>75</td>
<td>2.5</td>
</tr>
<tr class="even">
<td>País Vasco 2026</td>
<td>Ex. 1 and 2 obligatory (competencial); ex. 3 and 4: choose a/b</td>
<td>6</td>
<td>4</td>
<td>50</td>
<td>5.0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-structure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Competency content of each ordinary paper. “Contextualised items” have <code>ctx ≥ 1</code>; “substantive-context items” have <code>ctx = 2</code>; “competency items” additionally demand explanation or evaluation. Expected competency points assume random choice of options; obligatory competency points cannot be avoided. File: <code>data/exam_structure_2025_2026.csv</code>.
</figcaption>
<div aria-describedby="tbl-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Paper</th>
<th>Contextualised items %</th>
<th>Substantive-context items %</th>
<th>Competency items %</th>
<th>Expected competency pts %</th>
<th>Obligatory competency pts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Andalucía 2025</td>
<td>33</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Andalucía 2026</td>
<td>29</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>Asturias 2025</td>
<td>50</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Asturias 2026</td>
<td>62</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>Canarias 2025</td>
<td>12</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Canarias 2026</td>
<td>42</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>Castilla-La Mancha 2025</td>
<td>75</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Castilla-La Mancha 2026</td>
<td>22</td>
<td>11</td>
<td>11</td>
<td>20</td>
<td>2.0</td>
</tr>
<tr class="odd">
<td>Cataluña 2025</td>
<td>83</td>
<td>83</td>
<td>67</td>
<td>75</td>
<td>5.0</td>
</tr>
<tr class="even">
<td>Cataluña 2026</td>
<td>83</td>
<td>83</td>
<td>50</td>
<td>38</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>Comunitat Valenciana 2025</td>
<td>45</td>
<td>9</td>
<td>9</td>
<td>15</td>
<td>1.5</td>
</tr>
<tr class="even">
<td>Comunitat Valenciana 2026</td>
<td>29</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>Extremadura 2025</td>
<td>29</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Extremadura 2026</td>
<td>71</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>Madrid 2025</td>
<td>57</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>Madrid 2026</td>
<td>29</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>País Vasco 2025</td>
<td>14</td>
<td>14</td>
<td>14</td>
<td>25</td>
<td>2.5</td>
</tr>
<tr class="even">
<td>País Vasco 2026</td>
<td>100</td>
<td>67</td>
<td>50</td>
<td>62</td>
<td>5.0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-criteria" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-criteria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Share of items meeting each criterion, and the mean number of EHU criteria met per item. File: <code>data/exam_structure_2025_2026.csv</code>.
</figcaption>
<div aria-describedby="tbl-criteria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Paper</th>
<th>Application %</th>
<th>Explain/justify %</th>
<th>Graph/data interpretation %</th>
<th>Diagram production %</th>
<th>Evaluation/judgment %</th>
<th>Criteria met per item (of 5)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Andalucía 2025</td>
<td>8</td>
<td>58</td>
<td>0</td>
<td>33</td>
<td>0</td>
<td>0.67</td>
</tr>
<tr class="even">
<td>Andalucía 2026</td>
<td>14</td>
<td>79</td>
<td>0</td>
<td>21</td>
<td>0</td>
<td>0.93</td>
</tr>
<tr class="odd">
<td>Asturias 2025</td>
<td>25</td>
<td>50</td>
<td>0</td>
<td>38</td>
<td>0</td>
<td>0.75</td>
</tr>
<tr class="even">
<td>Asturias 2026</td>
<td>12</td>
<td>12</td>
<td>0</td>
<td>12</td>
<td>0</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>Canarias 2025</td>
<td>12</td>
<td>25</td>
<td>0</td>
<td>12</td>
<td>0</td>
<td>0.38</td>
</tr>
<tr class="even">
<td>Canarias 2026</td>
<td>8</td>
<td>17</td>
<td>0</td>
<td>8</td>
<td>0</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>Castilla-La Mancha 2025</td>
<td>25</td>
<td>75</td>
<td>25</td>
<td>25</td>
<td>0</td>
<td>1.25</td>
</tr>
<tr class="even">
<td>Castilla-La Mancha 2026</td>
<td>22</td>
<td>33</td>
<td>0</td>
<td>22</td>
<td>0</td>
<td>0.67</td>
</tr>
<tr class="odd">
<td>Cataluña 2025</td>
<td>33</td>
<td>83</td>
<td>0</td>
<td>67</td>
<td>0</td>
<td>2.00</td>
</tr>
<tr class="even">
<td>Cataluña 2026</td>
<td>67</td>
<td>50</td>
<td>0</td>
<td>33</td>
<td>33</td>
<td>2.33</td>
</tr>
<tr class="odd">
<td>Comunitat Valenciana 2025</td>
<td>18</td>
<td>45</td>
<td>27</td>
<td>36</td>
<td>9</td>
<td>1.09</td>
</tr>
<tr class="even">
<td>Comunitat Valenciana 2026</td>
<td>29</td>
<td>43</td>
<td>57</td>
<td>14</td>
<td>0</td>
<td>1.29</td>
</tr>
<tr class="odd">
<td>Extremadura 2025</td>
<td>14</td>
<td>57</td>
<td>29</td>
<td>0</td>
<td>0</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>Extremadura 2026</td>
<td>43</td>
<td>29</td>
<td>14</td>
<td>29</td>
<td>0</td>
<td>0.86</td>
</tr>
<tr class="odd">
<td>Madrid 2025</td>
<td>29</td>
<td>14</td>
<td>0</td>
<td>14</td>
<td>0</td>
<td>0.43</td>
</tr>
<tr class="even">
<td>Madrid 2026</td>
<td>14</td>
<td>0</td>
<td>29</td>
<td>0</td>
<td>0</td>
<td>0.43</td>
</tr>
<tr class="odd">
<td>País Vasco 2025</td>
<td>14</td>
<td>43</td>
<td>14</td>
<td>43</td>
<td>0</td>
<td>0.86</td>
</tr>
<tr class="even">
<td>País Vasco 2026</td>
<td>67</td>
<td>83</td>
<td>0</td>
<td>17</td>
<td>50</td>
<td>2.67</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-profiles" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig12_exam_profiles.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Contextualisation profile of each paper. For every community the left bar is 2025 and the right bar 2026; the stack splits the expected points into competency-style (blue), substantive context without an explain/evaluate demand (green) and decorative context (yellow). The change in the ordinary-sitting mean is printed under each community.
</figcaption>
</figure>
</div>
</section>
<section id="what-the-papers-of-the-rising-communities-look-like" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="what-the-papers-of-the-rising-communities-look-like"><span class="header-section-number">4</span> What the papers of the rising communities look like</h2>
<p><strong>Asturias</strong> (<span class="math inline">\(+1.13\)</span>) and <strong>Madrid</strong> (<span class="math inline">\(+1.05\)</span>), the two largest rises, had <em>no</em> competency-style exercise in either year. Asturias keeps its long-standing format — answer any five of eight two-point questions, so the whole paper is optional — and its contexts are decorative and, in 2026, whimsical: a melon weighed on Jupiter, two pumpkins and an apple, a kayak off Cudillero, a porcelain figurine in front of a mirror. Its 2025 paper actually demanded more reasoning (justify the sign of the work and whether it depends on the path; the Doppler echo question) than its 2026 paper, whose criteria-per-item score (0.25, tied with Canarias 2026) is the lowest of the eighteen. Madrid’s obligatory question changed from a narrated dwarf-planet problem (Eris, 2025) to a graph-reading item (a potential measured with a probe between two plates, <span class="math inline">\(V(x)=-3x\)</span>, 2026) — the one non-optional item with “graph interpretation” that the CRUE guidance asks for — and the rest of the 2026 paper is bare: no context at all in five of seven items. Madrid’s optionality (75 %) did not move.</p>
<p><strong>Castilla-La Mancha</strong> (<span class="math inline">\(+0.94\)</span>) is the only rising community whose paper moved towards the competency model, and it did so modestly: a new obligatory two-point item set in the Artemis II re-entry (compare the orbital and escape speeds; compute the energy to dissipate for a safe landing) replaced a “choose two of three sections” Saturn problem, and the paper’s optionality fell from 100 % to 70 %. Its expected competency points went from 0 to 20 %, all of them guaranteed. Everything else in the 2026 UCLM paper is classical.</p>
<p><strong>Cataluña</strong> (<span class="math inline">\(+0.80\)</span>) was, in 2025, the most contextualised paper of the set — every exercise narrated (space debris and the end of the ISS, Millikan’s experiment, a coin inside a polycarbonate block in an art exhibition, a flute, a Na-24 blood-volume tracer) with “justifiqueu” sections throughout — and it stayed that way in 2026 (a Generalitat nanosatellite, Halley’s comet, an X-ray tube, a phone’s vibration motor, Chernobyl at forty years). Its structure did not change either: four exercises, options in two of them, 50 % optional. On this coding its competency share <em>fell</em> (75 → 38 %), because two of the 2026 contexts drive calculations only and the explain/evaluate demands moved into the optional exercises; the substantive-context share stayed above 85 %. Catalan students have sat contextualised papers for well over a decade — the UJI study rates Cataluña, with País Vasco, as the most competency-oriented system of 2015–2025 <span class="citation" data-cites="sancheztarazaga2026pau">(<a href="#ref-sancheztarazaga2026pau" role="doc-biblioref">Sánchez-Tarazaga &amp; Gimeno Rovira, 2026</a>)</span> — so for them 2026 brought no change of genre.</p>
<p><strong>Comunitat Valenciana</strong> (<span class="math inline">\(+0.51\)</span>) went the other way. Its 2025 obligatory item was the most fully competency-style question in any 2025 paper outside Cataluña: a worker in a chlorine-electrolysis plant under an 18 kA cable, the Biot–Savart law to be stated and explained, the field to be drawn, and the result to be judged against the 2 T limit of Real Decreto 299/2016. In 2026 the obligatory item is a Deimos-2 satellite whose only demands are “deduce and calculate”. Valencia also redesigned its paper (six questions with 85 % optional points → four <em>apartados</em> with 80 %) and its 2026 paper is rich in <em>graph and figure interpretation</em> (57 % of items: a photographed rope wave, a laser scheme with angles to read, an <span class="math inline">\(E_k\)</span>–<span class="math inline">\(f\)</span> photoelectric plot to interpret) — a different flavour of “competency” from the narrative one.</p>
<p><strong>Andalucía</strong> (<span class="math inline">\(+0.17\)</span>) kept its style — a conceptual true/false “razone” section plus a problem in each block — and <em>increased</em> optionality from 60 % to 75 % by making the conceptual sections optional too. No competency-style exercise in either year; decorative contexts only (a suitcase dragged through an airport, a child on a slide, a wind farm in the Strait of Gibraltar).</p>
</section>
<section id="what-the-papers-of-the-falling-communities-look-like" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="what-the-papers-of-the-falling-communities-look-like"><span class="header-section-number">5</span> What the papers of the falling communities look like</h2>
<p><strong>País Vasco</strong> (<span class="math inline">\(-1.48\)</span>). The 2025 paper had seven problems in four blocks, one obligatory (Galileo satellite — an ESA/AVS narrative in which the student is a member of a design team, with “justifica”, “explica” and “discute” sections and a figure to check results against), and the other three blocks chosen one of two among classical problems. The 2026 paper has six items, of which the two obligatory ones — an alarmist Starlink headline to be assessed (“¿te parece realista que este impacto destruya grandes zonas?”, plus a reasoning-without-calculation section) and a weather-station microgenerator with a specification to check (fem ≥ 0.50 mV) — meet all five EHU criteria save the graph, and all four options carry a context as well, two of them substantive (a violin and a concert, a projector to be chosen and justified, an oxidised photocathode, the C-14 dating of bone remains with a sketch of the decay law). Every measure moves at once: expected competency points 25 → 62.5 %, guaranteed competency points 2.5 → 5.0, criteria per item 0.86 → 2.67 (the highest of the eighteen papers, above Cataluña’s 2.33), optionality 75 → 50 %. The format changed as well: the 2026 items are cut into six to nine numbered sub-tasks scored in 0.25-point steps, with a constants table replacing per-problem data.</p>
<p><strong>Canarias</strong> (<span class="math inline">\(-0.83\)</span>) did not move towards the competency model at all — its 2026 paper has no substantive context (the one real setting, Cs-137 in dust after a <em>calima</em> episode, is decorative) — but it did change structure: from four blocks with a free choice of option A or B (100 % optional) to a paper with two obligatory items (3 points) and unequal block weights (2.5 / 3 / 3 / 1.5), 70 % optional. Together with Euskadi it is one of the two communities that cut optionality by 25 points or more, and both fell.</p>
<p><strong>Extremadura</strong> (<span class="math inline">\(-0.82\)</span>) kept an identical structure (block A obligatory, choose one of two elsewhere, 75 % optional) and traded one decorative narrative (two Extremaduran students on an ESA mission, 2025) for another (the Artemis II launch, 2026), adding a photoelectric item built on an experimental data table. No competency-style exercise in either year.</p>
</section>
<section id="paper-change-against-grade-change" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="paper-change-against-grade-change"><span class="header-section-number">6</span> Paper change against grade change</h2>
<div id="fig-exam-scatter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-exam-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig11_exam_content.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-exam-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Change in the ordinary-sitting Física mean, 2025 → 2026, against (a) the change in expected competency points, (b) the change in the optional share of the paper and (c) the 2026 level of competency points. Nine communities; Pearson correlations printed in each panel. Orange = fell, red = Euskadi.
</figcaption>
</figure>
</div>
<div id="tbl-change" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-change-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Paper measures and grade change side by side, sorted by grade change. File: <code>data/exam_change_vs_grade.csv</code>.
</figcaption>
<div aria-describedby="tbl-change-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Community</th>
<th>Mean 2025</th>
<th>Mean 2026</th>
<th>Δ mean</th>
<th>Optional % 2025</th>
<th>Optional % 2026</th>
<th>Competency pts % 2025</th>
<th>Competency pts % 2026</th>
<th>Δ competency pts %</th>
<th>Oblig. competency pts 2025</th>
<th>Oblig. competency pts 2026</th>
<th>Criteria/item 2025</th>
<th>Criteria/item 2026</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Asturias</td>
<td>5.49</td>
<td>6.62</td>
<td>+1.13</td>
<td>100</td>
<td>100</td>
<td>0</td>
<td>0</td>
<td>+0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.75</td>
<td>0.25</td>
</tr>
<tr class="even">
<td>Madrid</td>
<td>5.65</td>
<td>6.70</td>
<td>+1.05</td>
<td>75</td>
<td>75</td>
<td>0</td>
<td>0</td>
<td>+0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.43</td>
<td>0.43</td>
</tr>
<tr class="odd">
<td>Castilla-La Mancha</td>
<td>5.86</td>
<td>6.80</td>
<td>+0.94</td>
<td>100</td>
<td>70</td>
<td>0</td>
<td>20</td>
<td>+20</td>
<td>0.0</td>
<td>2.0</td>
<td>1.25</td>
<td>0.67</td>
</tr>
<tr class="even">
<td>Cataluña</td>
<td>6.04</td>
<td>6.84</td>
<td>+0.80</td>
<td>50</td>
<td>50</td>
<td>75</td>
<td>38</td>
<td>-38</td>
<td>5.0</td>
<td>0.0</td>
<td>2.00</td>
<td>2.33</td>
</tr>
<tr class="odd">
<td>Comunitat Valenciana</td>
<td>5.89</td>
<td>6.40</td>
<td>+0.51</td>
<td>85</td>
<td>80</td>
<td>15</td>
<td>0</td>
<td>-15</td>
<td>1.5</td>
<td>0.0</td>
<td>1.09</td>
<td>1.29</td>
</tr>
<tr class="even">
<td>Andalucía</td>
<td>5.69</td>
<td>5.86</td>
<td>+0.17</td>
<td>60</td>
<td>75</td>
<td>0</td>
<td>0</td>
<td>+0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.67</td>
<td>0.93</td>
</tr>
<tr class="odd">
<td>Extremadura</td>
<td>6.09</td>
<td>5.27</td>
<td>-0.82</td>
<td>75</td>
<td>75</td>
<td>0</td>
<td>0</td>
<td>+0</td>
<td>0.0</td>
<td>0.0</td>
<td>1.00</td>
<td>0.86</td>
</tr>
<tr class="even">
<td>Canarias</td>
<td>5.08</td>
<td>4.25</td>
<td>-0.83</td>
<td>100</td>
<td>70</td>
<td>0</td>
<td>0</td>
<td>+0</td>
<td>0.0</td>
<td>0.0</td>
<td>0.38</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>País Vasco</td>
<td>5.47</td>
<td>3.99</td>
<td>-1.48</td>
<td>75</td>
<td>50</td>
<td>25</td>
<td>62</td>
<td>+38</td>
<td>2.5</td>
<td>5.0</td>
<td>0.86</td>
<td>2.67</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>With nine points no correlation is significant and none is claimed; the signs are what matter, and they answer the question as it was put. Across the six communities that rose, the expected competency content went <strong>down or stayed at zero in five</strong> (Asturias 0 → 0, Madrid 0 → 0, Andalucía 0 → 0, Valencia 15 → 0, Cataluña 75 → 38) and rose only in Castilla-La Mancha (0 → 20). The Basque increase (<span class="math inline">\(+37.5\)</span> points of expected share, <span class="math inline">\(+2.5\)</span> guaranteed points) is the largest in the set and is matched in direction by no rising community. The correlation between the change in competency content and the change in grade is negative (<span class="math inline">\(r=-0.47\)</span>; <span class="math inline">\(-0.62\)</span> on the criteria-per-item measure; <span class="math inline">\(-0.89\)</span> on the change in the share of contextualised points, a figure driven by Euskadi and Extremadura at one end and Madrid, Castilla-La Mancha and Valencia at the other). The correlation with the change in optionality is positive (<span class="math inline">\(r=+0.37\)</span>): the two papers that removed the most choice (Castilla-La Mancha and Canarias, <span class="math inline">\(-30\)</span> points each; Euskadi <span class="math inline">\(-25\)</span>) contain both the third-largest rise and two of the three falls, so optionality alone separates nothing.</p>
<p>What the coding therefore supports is narrower and, for the purpose of the 2027 discussion, more useful than a correlation:</p>
<ol type="1">
<li><strong>The 2026 recovery elsewhere happened on papers that had not become more competency-oriented.</strong> Where the recovery was largest (Asturias, Madrid) the papers are, on every criterion, traditional; where the paper was already competency-style (Cataluña) it had been so for years and did not change; where a genuinely competency-style obligatory item existed in 2025 (Valencia) it was replaced by a lighter one in 2026.</li>
<li><strong>The Basque paper is the one paper in the set that changed genre between the two years</strong>, and it changed on three axes at once — content type (from one competency exercise to half the marks), guaranteed exposure (the competency exercises are the obligatory ones), and format (granular 0.25-point sub-tasks, halved optionality). Castilla-La Mancha, the only other paper that moved in the same direction, moved on one axis by a fifth of the distance and rose.</li>
<li><strong>Canarias shows that a structural cut in optionality without any competency content coincides with a fall of the same order as the second Basque step.</strong> That is one data point, and Canarias carries its own history (the 2019 collapse, the third-exam-of-the-day timetable noted in its coordination minutes); but it means the Basque fall cannot be attributed to the competency exercises <em>rather than</em> to the reduction in choice, on this evidence.</li>
</ol>
<p>The cleanest statement is the one the earlier chapters left open: the reform framework (RD 534/2024) is common to all seventeen communities and cannot explain 2026; the <em>papers</em> are not common, and the Basque 2026 paper differs from its 2025 predecessor more than any other paper in this set differs from its own. Whether that difference produced the fall through the competency exercises, through the loss of choice, through the unfamiliar granular format, through the amount of reading the new items require in ninety minutes, or through marking-scheme effects that the corrector documents would show, is a question the grade data cannot settle and the exams alone cannot either. The natural next step is the one the UAM and Las Palmas commissions have taken elsewhere: an item-level analysis of the 2026 Basque scripts (marks by sub-task, by exercise and by option chosen), which would say directly whether the two obligatory competency exercises are where the 2 066 candidates lost their marks.</p>
</section>
<section id="a-note-on-the-uji-rating" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="a-note-on-the-uji-rating"><span class="header-section-number">7</span> A note on the UJI rating</h2>
<p>The UJI study <span class="citation" data-cites="sancheztarazaga2026pau">(<a href="#ref-sancheztarazaga2026pau" role="doc-biblioref">Sánchez-Tarazaga &amp; Gimeno Rovira, 2026</a>)</span> rated País Vasco and Cataluña as the most competency-oriented PAU systems of 2015–2025 and Madrid as the least. The present coding of the 2025 papers agrees on the ordering (Cataluña 2.00 and Euskadi 0.86 criteria per item versus Madrid 0.43), with the Basque 2025 paper owing its position to a single obligatory exercise. In 2026 the Basque paper (2.67) overtakes Cataluña (2.33); Madrid (0.43) does not move. If “competency orientation” is measured as the UJI study measures it, the 2026 Basque paper is now the most competency-oriented Física paper in Spain among the nine coded here — which is the strongest form of the hypothesis this chapter was asked to test, and the reason the item-level data matter.</p>



</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-sancheztarazaga2026pau" class="csl-entry" role="listitem">
Sánchez-Tarazaga, L., &amp; Gimeno Rovira, J. A. (2026). <em><span></span>C<span>ó</span>mo compatibilizar un bachillerato que busca habilidades cr<span>í</span>ticas con una <span>PAU</span> que todav<span>í</span>a prima la memorizaci<span>ó</span>n?</em> The Conversation (Espa<span>ñ</span>a), 2 June 2026. <a href="https://doi.org/10.64628/AAO.atrdhyeha">https://doi.org/10.64628/AAO.atrdhyeha</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/example\.org\/pau-fisika-2026");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/06-interpretation.html" class="pagination-link" aria-label="Interpretation and the 2027 question">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Interpretation and the 2027 question</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/01-data-hunt.html" class="pagination-link" aria-label="The data hunt">
        <span class="nav-page-text">The data hunt</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Independent analysis prepared 18 September 2026 · all figures reproducible from <code>scripts/</code></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Data: EHU, SIIU/EPAU, Generalitat de Catalunya, GVA, Junta de Andalucía, CM, Uniovi, UCLM, ULL, ULPGC, UNIZAR, UPNA, UMU, UC, CiUG, UR</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>