<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Josu M. Igartua">
<meta name="dcterms.date" content="2026-09-21">
<meta name="keywords" content="university entrance examinations, educational assessment, decomposition, identification, curriculum reform, physics education">
<meta name="description" content="A research article. One region’s physics entrance mean fell 1.48 marks in a single year while eight comparators rose. The national curriculum reform cannot be the cause, because it applied to all of them. The fall is decomposed exactly into the parts published aggregates can separate; four fifths of the region-specific residue are shown to be unidentifiable from any published aggregate, and the datum that would identify them is named.">

<title>When a national reform cannot explain a regional outcome – PAU Física 2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/15-synthesis.html" rel="next">
<link href="../chapters/07-literature.html" rel="prev">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5b4e4ad6cda8ee308e5de16fe7059631.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-55ab141dd447a5db25f9b02bc13364cd.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5b4e4ad6cda8ee308e5de16fe7059631.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4f56ef24fd7e0b60995d53dadae59254.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-d7169c38db111d135d171b3357e2edd5.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-4f56ef24fd7e0b60995d53dadae59254.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css?family=Inter:400,400i,500,600,700%7CJetBrains+Mono:400,700&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/favicon.svg" alt="PAU Física 2026" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PAU Física</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/02-euskadi.html"> 
<span class="menu-text">The Euskadi break</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/03-spain-2026.html"> 
<span class="menu-text">Spain 2026</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/08-sources.html"> 
<span class="menu-text">Sources &amp; methods</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/17-paper.html">Paper</a></li><li class="breadcrumb-item"><a href="../chapters/17-paper.html">Decomposition and identification</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><i class="bi bi-house" role="img">
</i> 
 <span class="menu-text">Findings</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence and results</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-euskadi.html" class="sidebar-item-text sidebar-link"><i class="bi bi-bar-chart-line" role="img">
</i> 
 <span class="menu-text">Euskadi 2010–2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-spain-2026.html" class="sidebar-item-text sidebar-link"><i class="bi bi-globe-europe-africa" role="img">
</i> 
 <span class="menu-text">Spain 2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-distributions.html" class="sidebar-item-text sidebar-link"><i class="bi bi-graph-up" role="img">
</i> 
 <span class="menu-text">Shape of the collapse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-subjects-sittings.html" class="sidebar-item-text sidebar-link"><i class="bi bi-people" role="img">
</i> 
 <span class="menu-text">Subjects &amp; participation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-interpretation.html" class="sidebar-item-text sidebar-link"><i class="bi bi-compass" role="img">
</i> 
 <span class="menu-text">Interpretation &amp; 2027</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">The papers</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-exam-content.html" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-text" role="img">
</i> 
 <span class="menu-text">The papers themselves</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-ehu-paper-history.html" class="sidebar-item-text sidebar-link"><i class="bi bi-clock-history" role="img">
</i> 
 <span class="menu-text">Sixteen years of one paper</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-paradigm.html" class="sidebar-item-text sidebar-link"><i class="bi bi-diagram-3" role="img">
</i> 
 <span class="menu-text">The paradigm change, whole</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Research context</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-data-hunt.html" class="sidebar-item-text sidebar-link"><i class="bi bi-search" role="img">
</i> 
 <span class="menu-text">The data hunt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-literature.html" class="sidebar-item-text sidebar-link"><i class="bi bi-journal-text" role="img">
</i> 
 <span class="menu-text">Literature &amp; regulation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-paper.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-file-earmark-text" role="img">
</i> 
 <span class="menu-text">Decomposition and identification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Briefing</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-synthesis.html" class="sidebar-item-text sidebar-link"><i class="bi bi-clipboard-check" role="img">
</i> 
 <span class="menu-text">Synthesis for the coordination</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-synthesis-es.html" class="sidebar-item-text sidebar-link"><i class="bi bi-translate" role="img">
</i> 
 <span class="menu-text">Síntesis (castellano)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-briefing.html" class="sidebar-item-text sidebar-link"><i class="bi bi-envelope-paper" role="img">
</i> 
 <span class="menu-text">For the Admissions Office</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-briefing-es.html" class="sidebar-item-text sidebar-link"><i class="bi bi-translate" role="img">
</i> 
 <span class="menu-text">Informe (castellano)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Sources and reproducibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-sources.html" class="sidebar-item-text sidebar-link"><i class="bi bi-archive" role="img">
</i> 
 <span class="menu-text">Sources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-log.html" class="sidebar-item-text sidebar-link"><i class="bi bi-list-check" role="img">
</i> 
 <span class="menu-text">Work log</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-reproduce.html" class="sidebar-item-text sidebar-link"><i class="bi bi-code-slash" role="img">
</i> 
 <span class="menu-text">Reproduce the study</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-audit.html" class="sidebar-item-text sidebar-link"><i class="bi bi-shield-check" role="img">
</i> 
 <span class="menu-text">Audit</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#official-national-statistics" id="toc-official-national-statistics" class="nav-link" data-scroll-target="#official-national-statistics"><span class="header-section-number">2.1</span> Official national statistics</a></li>
  <li><a href="#the-2026-cross-section" id="toc-the-2026-cross-section" class="nav-link" data-scroll-target="#the-2026-cross-section"><span class="header-section-number">2.2</span> The 2026 cross-section</a></li>
  <li><a href="#the-examination-papers" id="toc-the-examination-papers" class="nav-link" data-scroll-target="#the-examination-papers"><span class="header-section-number">2.3</span> The examination papers</a></li>
  <li><a href="#an-externally-scaled-instrument" id="toc-an-externally-scaled-instrument" class="nav-link" data-scroll-target="#an-externally-scaled-instrument"><span class="header-section-number">2.4</span> An externally scaled instrument</a></li>
  <li><a href="#what-is-not-available" id="toc-what-is-not-available" class="nav-link" data-scroll-target="#what-is-not-available"><span class="header-section-number">2.5</span> What is not available</a></li>
  </ul></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#sec-frames" id="toc-sec-frames" class="nav-link" data-scroll-target="#sec-frames"><span class="header-section-number">3.1</span> Reference frames</a></li>
  <li><a href="#sec-locus" id="toc-sec-locus" class="nav-link" data-scroll-target="#sec-locus"><span class="header-section-number">3.2</span> The band locus</a></li>
  <li><a href="#sec-residual" id="toc-sec-residual" class="nav-link" data-scroll-target="#sec-residual"><span class="header-section-number">3.3</span> The conditional top-band residual</a></li>
  <li><a href="#sec-subjects" id="toc-sec-subjects" class="nav-link" data-scroll-target="#sec-subjects"><span class="header-section-number">3.4</span> The exact subject decomposition</a></li>
  <li><a href="#sec-index" id="toc-sec-index" class="nav-link" data-scroll-target="#sec-index"><span class="header-section-number">3.5</span> The reform-intensity index</a></li>
  <li><a href="#sec-simulation" id="toc-sec-simulation" class="nav-link" data-scroll-target="#sec-simulation"><span class="header-section-number">3.6</span> The marking-regime simulation</a></li>
  <li><a href="#sec-length" id="toc-sec-length" class="nav-link" data-scroll-target="#sec-length"><span class="header-section-number">3.7</span> Statement length</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#the-magnitude-in-three-frames" id="toc-the-magnitude-in-three-frames" class="nav-link" data-scroll-target="#the-magnitude-in-three-frames"><span class="header-section-number">4.1</span> The magnitude, in three frames</a></li>
  <li><a href="#three-distinct-events-not-one" id="toc-three-distinct-events-not-one" class="nav-link" data-scroll-target="#three-distinct-events-not-one"><span class="header-section-number">4.2</span> Three distinct events, not one</a></li>
  <li><a href="#what-the-fall-is-made-of-by-subject" id="toc-what-the-fall-is-made-of-by-subject" class="nav-link" data-scroll-target="#what-the-fall-is-made-of-by-subject"><span class="header-section-number">4.3</span> What the fall is made of, by subject</a></li>
  <li><a href="#what-the-papers-did" id="toc-what-the-papers-did" class="nav-link" data-scroll-target="#what-the-papers-did"><span class="header-section-number">4.4</span> What the papers did</a></li>
  <li><a href="#bounds-on-the-marking-regime" id="toc-bounds-on-the-marking-regime" class="nav-link" data-scroll-target="#bounds-on-the-marking-regime"><span class="header-section-number">4.5</span> Bounds on the marking regime</a></li>
  <li><a href="#the-cohort-term" id="toc-the-cohort-term" class="nav-link" data-scroll-target="#the-cohort-term"><span class="header-section-number">4.6</span> The cohort term</a></li>
  </ul></li>
  <li><a href="#the-identification-limit" id="toc-the-identification-limit" class="nav-link" data-scroll-target="#the-identification-limit"><span class="header-section-number">5</span> The identification limit</a>
  <ul class="collapse">
  <li><a href="#why-the-candidates-cannot-be-separated" id="toc-why-the-candidates-cannot-be-separated" class="nav-link" data-scroll-target="#why-the-candidates-cannot-be-separated"><span class="header-section-number">5.1</span> Why the candidates cannot be separated</a></li>
  <li><a href="#the-attribution-budget" id="toc-the-attribution-budget" class="nav-link" data-scroll-target="#the-attribution-budget"><span class="header-section-number">5.2</span> The attribution budget</a></li>
  <li><a href="#where-the-reading-load-lies" id="toc-where-the-reading-load-lies" class="nav-link" data-scroll-target="#where-the-reading-load-lies"><span class="header-section-number">5.3</span> Where the reading load lies</a></li>
  <li><a href="#the-identifying-datum" id="toc-the-identifying-datum" class="nav-link" data-scroll-target="#the-identifying-datum"><span class="header-section-number">5.4</span> The identifying datum</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">6</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#reference-frames-change-the-headline" id="toc-reference-frames-change-the-headline" class="nav-link" data-scroll-target="#reference-frames-change-the-headline"><span class="header-section-number">6.1</span> Reference frames change the headline</a></li>
  <li><a href="#what-can-and-cannot-be-projected" id="toc-what-can-and-cannot-be-projected" class="nav-link" data-scroll-target="#what-can-and-cannot-be-projected"><span class="header-section-number">6.2</span> What can and cannot be projected</a></li>
  <li><a href="#what-a-reader-may-conclude" id="toc-what-a-reader-may-conclude" class="nav-link" data-scroll-target="#what-a-reader-may-conclude"><span class="header-section-number">6.3</span> What a reader may conclude</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">7</span> Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">8</span> Conclusion</a></li>
  <li><a href="#author-note" id="toc-author-note" class="nav-link" data-scroll-target="#author-note">Author note</a></li>
  <li><a href="#data-and-code-availability" id="toc-data-and-code-availability" class="nav-link" data-scroll-target="#data-and-code-availability">Data and code availability</a></li>
  <li><a href="#appendix-a-provenance-and-quality-of-the-2026-cross-section" id="toc-appendix-a-provenance-and-quality-of-the-2026-cross-section" class="nav-link" data-scroll-target="#appendix-a-provenance-and-quality-of-the-2026-cross-section">Appendix A — Provenance and quality of the 2026 cross-section</a></li>
  <li><a href="#appendix-b-locus-diagnostics" id="toc-appendix-b-locus-diagnostics" class="nav-link" data-scroll-target="#appendix-b-locus-diagnostics">Appendix B — Locus diagnostics</a></li>
  <li><a href="#appendix-c-simulation-specification" id="toc-appendix-c-simulation-specification" class="nav-link" data-scroll-target="#appendix-c-simulation-specification">Appendix C — Simulation specification</a></li>
  <li><a href="#appendix-d-reproduction" id="toc-appendix-d-reproduction" class="nav-link" data-scroll-target="#appendix-d-reproduction">Appendix D — Reproduction</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="17-paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/17-paper.html">Paper</a></li><li class="breadcrumb-item"><a href="../chapters/17-paper.html">Decomposition and identification</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">When a national reform cannot explain a regional outcome</h1>
<p class="subtitle lead">Decomposition and the identification limits of published university-entrance aggregates</p>
  <div class="quarto-categories">
    <div class="quarto-category">paper</div>
    <div class="quarto-category">decomposition</div>
    <div class="quarto-category">identification</div>
    <div class="quarto-category">assessment</div>
  </div>
  </div>

<div>
  <div class="description">
    A research article. One region’s physics entrance mean fell 1.48 marks in a single year while eight comparators rose. The national curriculum reform cannot be the cause, because it applied to all of them. The fall is decomposed exactly into the parts published aggregates can separate; four fifths of the region-specific residue are shown to be unidentifiable from any published aggregate, and the datum that would identify them is named.
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Josu M. Igartua </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad del País Vasco / Euskal Herriko Unibertsitatea (UPV/EHU)
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">21 September 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">21 September 2026</p>
    </div>
  </div>
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>In June 2026 the mean mark in Physics at the Basque university-entrance examination fell to 3.99 from 5.47, the lowest value in a sixteen-year series and a one-year change of <span class="math inline">\(-1.48\)</span> marks. The explanation offered was the national competency-based reform of RD 534/2024. Arithmetic refutes it: the reform applied in all seventeen autonomous communities in both years, and six of the nine communities reporting a 2026 result rose under it. A national cause cannot produce opposite signs in the same year.</p>
    <p>This article decomposes the fall using only published aggregates. Against the nine-community field, <span class="math inline">\(-1.65\)</span> marks are region-specific, and none of the 2025 fall was. A balanced eight-subject panel splits the change exactly, with nothing fitted, into a field term of <span class="math inline">\(+0.80\)</span>, a component of <span class="math inline">\(-1.18\)</span> common to all of the region’s quantitative subjects, and <span class="math inline">\(-1.10\)</span> specific to Physics. A band locus fitted across 187 region-years separates changes of location from changes of shape and identifies 2024, not 2026, as the year the distribution changed shape.</p>
    <p>Withdrawn optionality (<span class="math inline">\(-0.20\)</span>) and an externally measured cohort term (<span class="math inline">\(-0.12\)</span>) can be bounded. The remaining <span class="math inline">\(-1.33\)</span> cannot: paper difficulty, marking severity, reading load and newly examined content each displace the whole distribution downward, so every function of that distribution takes the same value under all four. A marking-regime simulation reproduces between 59 and 87 per cent of the Physics-specific fall depending on assumptions the published data cannot adjudicate. The result is a quantified limit on what aggregate educational statistics can identify, and a statement of the datum — marks at sub-task level — that would remove it.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>university entrance examinations, educational assessment, decomposition, identification, curriculum reform, physics education</p>
  </div>
</div>

</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>In June 2026 the mean mark obtained in Physics at the ordinary sitting of the Basque university-entrance examination was 3.99 out of 10, from 2 066 candidates, with 39.8 per cent reaching the pass mark. The corresponding values were 5.47 in 2025 and 6.09 in 2024. The 2026 figure is the lowest in the sixteen years for which the series exists, and it lies below every regional Physics mean recorded in eleven years of national statistics with the single exception of Canarias in 2019. The one-year change, <span class="math inline">\(-1.48\)</span> marks, is matched or exceeded in only seven of the 170 year-to-year changes available in the national panel.</p>
<p>The explanation advanced when the result became public was the competency-based examination model introduced for all Spanish university-entrance examinations by Royal Decree 534/2024 <span class="citation" data-cites="rd534_2024">(<a href="#ref-rd534_2024" role="doc-biblioref">Gobierno de España, 2024</a>)</span>. The attribution is natural: the reform was recent, it was substantial, and it coincided with the fall.</p>
<p>It is also refuted by the data that were already public when it was made. The decree applied in all seventeen autonomous communities, in both 2025 and 2026. Of the nine communities that had published a 2026 Physics mean at the time of writing, six rose — by between <span class="math inline">\(+0.17\)</span> and <span class="math inline">\(+1.13\)</span> marks — under the same decree in the same year that one community fell 1.48. A cause common to all seventeen cannot produce movements of opposite sign among them. Whatever the decree did, it is not what happened in Physics in the Basque Country in 2026.</p>
<div id="fig-nine" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig03_regions_2026_vs_2025.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nine-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The nine communities that had published a 2026 Physics mean, 2025 to 2026. Six rose and three fell, under a curriculum reform that applied to all of them in both years. The refutation of a common cause is visible without any statistic: a national mechanism cannot move six communities up and three down in the same sitting.
</figcaption>
</figure>
</div>
<p><a href="#fig-nine" class="quarto-xref">Figure&nbsp;1</a> states the refutation without recourse to a statistic. That refutation is cheap, and it leaves the substantive question open. This article addresses it in three steps. First, the fall is decomposed into the parts that published aggregates can separate: the part shared with the rest of the country, the part common to a region’s quantitative subjects, and the part specific to one subject. This is arithmetic, not modelling, and the terms sum to the observed change by construction. Second, the components of the region-specific residue that admit a defensible magnitude are bounded. Third, and principally, the article establishes that the remainder — four fifths of the region-specific change — cannot be attributed to any of its candidate causes using published data of any kind, and quantifies that limit.</p>
<p>The third result is the contribution, and it is general. The candidate mechanisms for a fall of this kind — a harder paper, a stricter marking regime, a heavier reading load, content examined for the first time — are not merely difficult to separate. They are collinear in every statistic that is published: each displaces the whole distribution downward, each lowers the mean, each reduces the pass rate and thins the upper bands. Aggregate educational statistics do not contain the information needed to distinguish them, and no further analysis of those aggregates will supply it. The article makes that limit explicit, gives it a magnitude, and identifies the one datum that would remove it.</p>
</section>
<section id="data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<p>Four bodies of evidence are used, and they are not interchangeable. Each is described with its provenance and its limitations, because several of the article’s conclusions turn on what a given source can and cannot support.</p>
<section id="official-national-statistics" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="official-national-statistics"><span class="header-section-number">2.1</span> Official national statistics</h2>
<p>The EPAU/SIIU cubes published by the Spanish Ministry of Universities give, for each autonomous community and each year from 2015 to 2025, the mean mark, the pass rate and the distribution across grade bands for every examined subject <span class="citation" data-cites="siiu_epau2025">(<a href="#ref-siiu_epau2025" role="doc-biblioref">Ministerio de Ciencia, Innovación y Universidades (SIIU), 2026</a>)</span>. This is the only source in which all communities are measured on the same basis. It yields a balanced panel of 187 community-year observations (17 communities × 11 years) and 170 year-to-year transitions (17 × 10), which are the reference populations for every rank statement in this article.</p>
<p>The 2026 cube is not published until June 2027. Every 2026 figure used here therefore comes from elsewhere, and is marked as such wherever it appears.</p>
</section>
<section id="the-2026-cross-section" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-2026-cross-section"><span class="header-section-number">2.2</span> The 2026 cross-section</h2>
<p>Nine of the seventeen communities had published a 2026 Physics mean at the time of writing. These were assembled individually from university and regional government publications <span class="citation" data-cites="ehu2026notak govern2026dossier madrid2026pau junta2026pevau uniovi2026junio gva2026junio">(<a href="#ref-madrid2026pau" role="doc-biblioref">Comunidad de Madrid, 2026</a>; <a href="#ref-ehu2026notak" role="doc-biblioref">Euskal Herriko Unibertsitatea, 2026</a>; <a href="#ref-govern2026dossier" role="doc-biblioref">Generalitat de Catalunya, 2026</a>; <a href="#ref-gva2026junio" role="doc-biblioref">Generalitat Valenciana, Conselleria d’Educació, Universitats i Ocupació, 2026</a>; <a href="#ref-junta2026pevau" role="doc-biblioref">Junta de Andalucía, 2026</a>; <a href="#ref-uniovi2026junio" role="doc-biblioref">Universidad de Oviedo, 2026</a>)</span>. Two were recoverable only from interactive dashboards that no search engine indexes.</p>
<p>The nine are not a random sample of the seventeen, and are not treated as one. They are used for a single purpose, described in §3.1: distinguishing a year in which every community moved from a year in which one moved alone. Each figure carries a quality tier — official statistic, institutional presentation, or press report — and the single press-level figure is excluded from every calculation on which a conclusion depends.</p>
</section>
<section id="the-examination-papers" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="the-examination-papers"><span class="header-section-number">2.3</span> The examination papers</h2>
<p>Every exercise and option of the eighteen ordinary papers set in 2025 and 2026 by the nine reporting communities — 146 items — was coded against the competency criteria published by the examining authority, recording for each item whether it requires a numerical result, whether it carries substantive real-world context, whether it demands explanation or judgement, and what proportion of the paper’s marks a candidate may decline to attempt. A second coder repeated the exercise blind, giving <span class="math inline">\(\kappa = 0.76\)</span> on the competency flag. The complete archive of the region’s own papers since 2010, 34 papers, was read in the same way.</p>
</section>
<section id="an-externally-scaled-instrument" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="an-externally-scaled-instrument"><span class="header-section-number">2.4</span> An externally scaled instrument</h2>
<p>PISA measures the same students at age fifteen, on a scale fixed outside any national examination system, and its 2025 round was published on 8 September 2026. It is used once, in §4.6, to bound a cohort term. Its cohorts and the examination cohorts are aligned explicitly rather than assumed to correspond.</p>
</section>
<section id="what-is-not-available" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="what-is-not-available"><span class="header-section-number">2.5</span> What is not available</h2>
<p>Three things would resolve most of what this article shows to be unresolvable, and none of them is published: marks at the level of the individual sub-task, marks disaggregated by marking panel, and the 2026 grade-band table for Physics — the last of which had been published in every preceding year. Their absence is not incidental to the argument; §5 shows that it is the argument.</p>
</section>
</section>
<section id="methods" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods</h1>
<section id="sec-frames" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-frames"><span class="header-section-number">3.1</span> Reference frames</h2>
<p>A one-year change in an examination mean has no interpretation on its own, because the examination changes every year. Three reference frames are therefore reported throughout, and they answer different questions.</p>
<p>The <em>year-on-year</em> frame compares 2026 with 2025. The <em>baseline</em> frame compares 2026 with the region’s own 2015–2019 mean, before the pandemic-era relief measures. The <em>field</em> frame compares the region’s change with the mean change of the nine communities that published a 2026 result.</p>
<p>Only the third can distinguish a national movement from a regional one, which is the distinction on which the refutation in §1 rests. It is constructed as <span class="math inline">\(\Delta_{\text{specific}} = \Delta_{\text{region}} - \Delta_{\text{field}}\)</span>, where the field mean <em>includes</em> the region under study. Including it is the conservative choice: excluding it would enlarge the region-specific term.</p>
</section>
<section id="sec-locus" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-locus"><span class="header-section-number">3.2</span> The band locus</h2>
<p>A change in a mean and a change in the shape of a distribution are different events, and a mean cannot distinguish them: candidates leaving the top band while others arrive from below can leave the mean almost stationary.</p>
<p>To separate them, the share of candidates in each grade band is regressed on the mean across all 187 community-year observations. The resulting curve — the <em>locus</em> — gives the band share an ordinary distribution exhibits at a given mean. For any observed change in the mean, the locus predicts the band change that would accompany it if only the location had moved. The difference between the observed and predicted band change is the movement of shape, net of location.</p>
<p>The locus is descriptive. It carries no causal claim and no assumption about the underlying distribution beyond the regularity it measures directly.</p>
</section>
<section id="sec-residual" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="sec-residual"><span class="header-section-number">3.3</span> The conditional top-band residual</h2>
<p>The locus yields a per-band quantity. To rank a community-year against all others it is summarised as a single standardised figure: the share of candidates in the 8–10 band, conditional on the community’s mean, expressed relative to the other communities in the same year and standardised across the 170 transitions. A value of <span class="math inline">\(-1\)</span> means a community has one standard deviation less top band than its own mean, read against its contemporaries, would lead one to expect.</p>
</section>
<section id="sec-subjects" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-subjects"><span class="header-section-number">3.4</span> The exact subject decomposition</h2>
<p>The examining authority published means for eight subjects in both 2025 and 2026. Four comparator communities published three of the same subjects. This yields a balanced panel on which the observed change in Physics splits into four terms:</p>
<p><span class="math display">\[
\Delta_{\text{Physics}}^{\text{region}}
= \underbrace{\overline{\Delta}^{\text{field}}_{\text{core}}}_{\text{field core}}
+ \underbrace{\left(\overline{\Delta}^{\text{field}}_{\text{Physics}} - \overline{\Delta}^{\text{field}}_{\text{core}}\right)}_{\text{field Physics premium}}
+ \underbrace{\left(\overline{\Delta}^{\text{region}}_{\text{core}} - \overline{\Delta}^{\text{field}}_{\text{core}}\right)}_{\text{region-common}}
+ \underbrace{\varepsilon}_{\text{Physics-specific}}
\]</span></p>
<p>where “core” denotes the three subjects shared by all five communities. The identity is exact: the four terms sum to the observed change by construction, and nothing is fitted. Its value is that it separates a movement affecting all of a region’s quantitative subjects from one affecting a single subject, which no single-subject statistic can do.</p>
</section>
<section id="sec-index" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="sec-index"><span class="header-section-number">3.5</span> The reform-intensity index</h2>
<p>A national frame applied in seventeen places is seventeen different papers. To measure how far each community’s 2026 paper moved from its own 2025 predecessor, four movements are computed from the coded papers: the change in optionality (entered with its sign reversed, since reducing choice is the direction the national orientations prescribe), the change in the share of marks carried by competency-coded items, the change in the share carrying substantive context, and the change in the share that is contextualised. Each is standardised within the nine and the four are averaged.</p>
<p>Standardising within the nine makes the index a ranking device and not a scale with meaning of its own. It is reported with that restriction, and §4.4 states explicitly what it can and cannot establish with <span class="math inline">\(n = 9\)</span>.</p>
</section>
<section id="sec-simulation" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="sec-simulation"><span class="header-section-number">3.6</span> The marking-regime simulation</h2>
<p>The marking specification in force from 2025 defines seven classes of minor error, each attracting a fixed deduction, and a class of grave error that voids the sub-task in which it occurs. A linguistic component and a spelling rule apply to items that produce text, subject to a cap.</p>
<p>To bound the effect of applying that specification more completely in its second year than in its first, a candidate population is constructed non-parametrically from the published 2025 band distribution, so that the baseline reproduces the 2025 marks by construction rather than by assumption. Deductions are then applied at a given rate, with a floor at zero for each sub-task, and the resulting distribution is compared with what was observed. Two voiding regimes — cascading and independent — and a range of penalty distributions across candidates are examined, because the published data do not determine which holds.</p>
<p>The simulation is used to produce bounds, not an estimate. Its output is the range of the Physics-specific fall that a marking regime could account for under assumptions the published data cannot adjudicate between.</p>
</section>
<section id="sec-length" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sec-length"><span class="header-section-number">3.7</span> Statement length</h2>
<p>Reading load is measured as the number of words a candidate must read in the statement of each item, counted on a fixed convention: mark allocations, rubrics and other recurring furniture are excluded, so that the measure reflects what must be read to understand the task. Both the load of the whole paper as issued and the load actually faced by a candidate exercising the available choice are reported, since they differ materially when optionality changes.</p>
</section>
</section>
<section id="results" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Results</h1>
<section id="the-magnitude-in-three-frames" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-magnitude-in-three-frames"><span class="header-section-number">4.1</span> The magnitude, in three frames</h2>
<p>The three reference frames of §3.1 give values that differ by less than half a mark, so no conclusion in this article depends on the choice between them.</p>
<div id="tbl-frames" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[24,52,24]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The 2026 change under three reference frames.
</figcaption>
<div aria-describedby="tbl-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 52%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Frame</th>
<th>Question</th>
<th style="text-align: right;">2026</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Year on year</td>
<td>how far did the mean fall from 2025?</td>
<td style="text-align: right;"><span class="math inline">\(-1.48\)</span></td>
</tr>
<tr class="even">
<td>Against the pre-COVID baseline</td>
<td>how far is 2026 from the region’s ordinary level?</td>
<td style="text-align: right;"><span class="math inline">\(-1.91\)</span></td>
</tr>
<tr class="odd">
<td>Against the nine-community field</td>
<td>how much is specific to the region?</td>
<td style="text-align: right;"><span class="math inline">\(-1.65\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The frames are not equivalent in what they permit. Only the third supports a claim about regional specificity, and it is the only one used for that purpose below.</p>
<div id="fig-series" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig01_euskadi_series.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The Basque Physics series, ordinary sitting, 2010–2026, with the governing legislation and the examination model actually in use shown as separate rows, because they do not coincide. The darker tint marks the two sittings held under pandemic relief measures; the lighter one the four-of-eight paper those measures imposed, which remained in force until 2024. The grey line is the national cube, which ends in 2025. The two arrows are changes, not levels, and both originate at the region’s own 2025 mean: the region’s own change to 3.99 and the nine-community field’s change of <span class="math inline">\(+0.17\)</span>, whose head at 5.64 is therefore where the subject would have finished had it moved with the field. The bracket between the heads is the region-specific component, <span class="math inline">\(-1.65\)</span>.
</figcaption>
</figure>
</div>
<p>Two features of <a href="#fig-series" class="quarto-xref">Figure&nbsp;2</a> bear on what follows. The pandemic relief measures were in force for two sittings, not one, and the second of them, 2021, produced the highest mean in the whole series (7.69) — 1.63 above 2022. Any baseline that includes those years is not a baseline. And the change of governing legislation in 2017 did not coincide with a change of examination model, which did not occur until 2020 and occurred then for reasons unrelated to the legislation. Legislative dates are therefore poor instruments for examination change in this setting.</p>
</section>
<section id="three-distinct-events-not-one" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="three-distinct-events-not-one"><span class="header-section-number">4.2</span> Three distinct events, not one</h2>
<p>The series contains three separable events, and conflating them is the most common error in reading it.</p>
<p><strong>2024 changed the shape and barely moved the level.</strong> The mean moved <span class="math inline">\(-0.21\)</span>, in a series whose year-to-year standard deviation is 0.85 — that is, nothing. The distribution, however, moved a great deal. The 8–10 band fell 9.0 percentage points where the locus of §3.2 predicts 3.1 for a fall of 0.21 in the mean, and the pass rate <em>rose</em> 2.3 points where the locus predicts a fall of 2.8. Fewer candidates at the top, more just above the line, with the mean almost stationary.</p>
<p>Summarised by the conditional residual of §3.3, the region’s position moved <span class="math inline">\(-3.08\)</span> standard deviations between 2023 and 2024: the second most negative of the 170 transitions in the national panel. On the combined size of both departures from the locus it ranks eleventh of 170. Both figures are reported; the event is large on either.</p>
<div id="fig-locus" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-locus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/paper/fig04_locus.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-locus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Location against shape. <strong>(a)</strong> Every year-to-year transition in the national panel, with the change in the mean on the horizontal axis and, on the vertical, the change in the top band net of what the locus predicts from the change in the mean alone. A year that moved only its location sits on the horizontal line. <strong>(b)</strong> The same two years as bars, observed against the locus prediction, for the top band and the pass rate.
</figcaption>
</figure>
</div>
<p>This matters because 2024 was the last sitting of the previous examination format, a year before the first paper set under the new national frame. Every test in this article that operates on the mean is blind to it, and all of them are correct: a mean cannot see candidates leave the top while others arrive from below.</p>
<p><strong>2025 changed the level, and the change was national.</strong> The region lost 0.62; the nine-community field lost 0.65. Read against the field, there is nothing region-specific in 2025 at all — a difference of three hundredths of a mark.</p>
<p><strong>2026 is region-specific.</strong> The field gained 0.17 while the region lost 1.48, so the region-specific component is <span class="math inline">\(-1.65\)</span>, and the whole of it falls in one year.</p>
</section>
<section id="what-the-fall-is-made-of-by-subject" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="what-the-fall-is-made-of-by-subject"><span class="header-section-number">4.3</span> What the fall is made of, by subject</h2>
<p><a href="#fig-subjects" class="quarto-xref">Figure&nbsp;4</a> applies the exact decomposition of §3.4. The four terms sum to the observed <span class="math inline">\(-1.48\)</span> by construction.</p>
<div id="tbl-split" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[26,12,62]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: The exact four-term split of the <span class="math inline">\(-1.48\)</span>. No parameter is fitted.
</figcaption>
<div aria-describedby="tbl-split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 12%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th style="text-align: right;">Marks</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Field core</td>
<td style="text-align: right;"><span class="math inline">\(+0.06\)</span></td>
<td>what the three shared subjects did in the four comparators</td>
</tr>
<tr class="even">
<td>Field Physics premium</td>
<td style="text-align: right;"><span class="math inline">\(+0.74\)</span></td>
<td>Physics above its own community’s mean, in all four</td>
</tr>
<tr class="odd">
<td><strong>Region-common</strong></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{-1.18}\)</span></td>
<td>what moved all of the region’s quantitative subjects together</td>
</tr>
<tr class="even">
<td><strong>Physics-specific</strong></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{-1.10}\)</span></td>
<td>what is left for the Physics paper</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-subjects" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-subjects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/paper/fig05_subjects.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-subjects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: <strong>(a)</strong> The eight subjects examined by the region in both years, quantitative subjects distinguished from the rest. <strong>(b)</strong> Each community’s change in Physics against its own mean change over the three shared subjects; a community on the dotted diagonal moved Physics exactly as it moved everything else. <strong>(c)</strong> The four terms of the exact split.
</figcaption>
</figure>
</div>
<p>The result is that <strong>more than half of what separates this region from the field is not specific to Physics</strong>. In the same sitting, at the same institution, under the same marking specification, Mathematics II fell 1.67 marks — more than Physics — while Chemistry (<span class="math inline">\(-0.21\)</span>), Biology (<span class="math inline">\(+0.15\)</span>) and Spanish Language (<span class="math inline">\(+0.03\)</span>) did not follow. A single-subject analysis of Physics cannot see this term and will attribute all of it to the Physics paper.</p>
</section>
<section id="what-the-papers-did" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="what-the-papers-did"><span class="header-section-number">4.4</span> What the papers did</h2>
<p>The nine 2026 papers differ from their own 2025 predecessors by very different amounts. On the index of §3.5 the region under study scores <span class="math inline">\(+1.76\)</span> and ranks first of nine; the next community scores <span class="math inline">\(+0.39\)</span> and the remaining seven sit at or below zero. Five of the six communities whose mean rose in 2026 carry <em>negative</em> index values.</p>
<div id="fig-reform" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reform-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/paper/fig06_reform_intensity.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reform-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: <strong>(a)</strong> Optionality in 2025 and 2026 against the band prescribed by the national orientations. <strong>(b)</strong> The reform-intensity index against the change in the mean, across the nine communities. <strong>(c)</strong> The share of marks carried by competency-coded items, 2025 and 2026.
</figcaption>
</figure>
</div>
<p>Across the nine, the index and the change in the mean correlate at <span class="math inline">\(r = -0.70\)</span> (<span class="math inline">\(p = 0.035\)</span>, <span class="math inline">\(n = 9\)</span>). This is reported with an explicit caveat, because the caveat is as informative as the coefficient: removing the region under study reduces the association among the remaining eight to <span class="math inline">\(r = -0.40\)</span> (<span class="math inline">\(p = 0.33\)</span>). The relation <em>is</em> the single community. What the index establishes is not a dose-response across communities but the fact that <strong>one community implemented the national frame completely and alone</strong>, moving all four axes at once while the others moved one or none. With <span class="math inline">\(n = 9\)</span> and the outcome concentrated in one point, this is consistency, not evidence of effect, and it is exactly what prevents the nine-community panel from testing the hypothesis it suggests.</p>
<p>Three specific movements are worth recording. The share of marks carried by competency-coded items rose from 25 to 62.5 per cent — the largest movement in the set, and the only one of that magnitude. Optionality was halved, with two of four problems carrying no choice at all; simulation of the two formats values that change at <span class="math inline">\(-0.26\)</span> marks gross, and <span class="math inline">\(-0.20\)</span> net of the optionality reductions the other communities made in the same year. Reading load rose 45 per cent, to approximately 1 430 words of statement. The 2026 paper is the only one of the eighteen that changed genre between the two years.</p>
</section>
<section id="bounds-on-the-marking-regime" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="bounds-on-the-marking-regime"><span class="header-section-number">4.5</span> Bounds on the marking regime</h2>
<p>2026 was the second year in which the marking specification of §3.6 was in force. A regime applied cautiously in its first year and fully in its second would reproduce the observed pattern — a negligible region-specific change in 2025 followed by a large one in 2026 — without any change in the specification itself. The hypothesis is therefore consistent with the timing, and the question is whether it is consistent with the magnitude.</p>
<div id="fig-marking" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-marking-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/paper/fig07_marking_regime.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-marking-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: <strong>(a)</strong> The deduction channel: the simulated fall as a function of the number of deductions applied per candidate. <strong>(b)</strong> Four published quantities reproduced by the fitted regime, against one that is not published. <strong>(c)</strong> The three quantities the specification itself fixes.
</figcaption>
</figure>
</div>
<p>Under a flat penalty the cost is 0.080 marks per deduction, so twelve deductions per candidate produce 0.96 marks, or 87 per cent of the Physics-specific <span class="math inline">\(-1.10\)</span>. Distributing the penalties unevenly across candidates — which is what any real marking regime does — reduces the yield, because marks cannot be taken from candidates who have none: across the plausible family of distributions the same twelve deductions yield between 0.65 and 0.89 marks, or 59 to 81 per cent.</p>
<p>Two further constraints narrow the space without closing it. Only sub-tasks that produce a numerical result can attract unit, prefix or rounding errors; the 2026 paper contains 27 to 32 sub-tasks, of which 14 to 19 are so exposed, which places twelve deductions at 0.67 per exposed answer and the twenty-one needed to carry the entire fall at 1.26 per exposed answer. The linguistic channel is capped by the specification itself at 1.00 marks, and a joint fit to the published quantities values a single error at 0.044 marks, which crowds that channel to a small fraction of its cap.</p>
<p>The conclusion of this subsection is a range, not a number: <strong>a marking regime applied more completely in its second year can account for between 59 and 87 per cent of the Physics-specific fall</strong>, and the published data do not determine where in that range the truth lies. The single quantity that would discriminate — the 2026 grade-band distribution, published in every prior year — is not available.</p>
</section>
<section id="the-cohort-term" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="the-cohort-term"><span class="header-section-number">4.6</span> The cohort term</h2>
<p>PISA 2025 places the region at 458.5 in science against a national 477.1, a fall of 21.0 points from 2022. Converted at one standard deviation of PISA to one of the examination, and prorated over the two years separating the examination cohorts, this yields a cohort term of 0.18 marks gross and 0.12 marks in excess of the national movement.</p>
<p>The more important result concerns rates rather than levels. The per-cohort-year change is not a slope but a sequence of steps: <span class="math inline">\(+3.7\)</span>, <span class="math inline">\(-7.5\)</span>, <span class="math inline">\(+1.4\)</span>, <span class="math inline">\(-2.0\)</span>, <span class="math inline">\(-7.0\)</span> points per cohort-year across successive rounds. A linear extrapolation would produce an honest confidence interval around the wrong model. Moreover the cohort term, at 0.12 to 0.18 marks, is between five and seven times smaller than the 0.85-mark standard deviation of the paper-to-paper variation it would have to be read against. It is real, it is externally measured, and it is far too small to be the event.</p>
</section>
</section>
<section id="the-identification-limit" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> The identification limit</h1>
<section id="why-the-candidates-cannot-be-separated" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="why-the-candidates-cannot-be-separated"><span class="header-section-number">5.1</span> Why the candidates cannot be separated</h2>
<p>Four mechanisms remain in contention for the region-specific residue: the content and difficulty of the paper, the severity with which it was marked, the reading load it imposed, and the syllabus content examined for the first time after a period in which optionality had allowed candidates to avoid it.</p>
<p>These are not merely hard to disentangle. They are <em>collinear in every statistic that is published</em>. Each of the four displaces the entire distribution downward. Each lowers the mean. Each reduces the pass rate. Each thins the upper bands and thickens the lower ones. Two of them — the conversion of the paper to the competency format and the reopening of the syllabus — are moreover properties of the same paper in the same sitting, and were introduced together.</p>
<p>A published aggregate is a function of the distribution. If four mechanisms produce the same displacement of the distribution, then every function of that distribution takes the same value under all four, and no amount of further analysis of published aggregates can separate them. This is a statement about the information content of the data, not about the sophistication of the method. It would remain true given unlimited analytical resources and unlimited time.</p>
</section>
<section id="the-attribution-budget" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-attribution-budget"><span class="header-section-number">5.2</span> The attribution budget</h2>
<p><a href="#tbl-budget" class="quarto-xref">Table&nbsp;3</a> states the position for the region-specific <span class="math inline">\(-1.65\)</span>, with the status of each row given explicitly.</p>
<div id="tbl-budget" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[40,12,48]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: The attribution budget for the region-specific <span class="math inline">\(-1.65\)</span>.
</figcaption>
<div aria-describedby="tbl-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 12%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th style="text-align: right;">Marks</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Common to the country</td>
<td style="text-align: right;"><span class="math inline">\(+0.17\)</span></td>
<td>observed</td>
</tr>
<tr class="even">
<td>Optionality withdrawn, net of other communities’ reductions</td>
<td style="text-align: right;"><span class="math inline">\(-0.20\)</span></td>
<td>quantified by simulation</td>
</tr>
<tr class="odd">
<td>Cohort, in excess of the national movement</td>
<td style="text-align: right;"><span class="math inline">\(-0.12\)</span></td>
<td>quantified, upper bound</td>
</tr>
<tr class="even">
<td>Paper content and reading load</td>
<td style="text-align: right;">—</td>
<td><strong>not identified</strong> (one signal, seen twice)</td>
</tr>
<tr class="odd">
<td>Marking severity</td>
<td style="text-align: right;">—</td>
<td><strong>not identified</strong> (bounded at 59–87 % of the Physics-specific term)</td>
</tr>
<tr class="even">
<td>Panel-to-panel severity and spread</td>
<td style="text-align: right;">—</td>
<td><strong>not identified</strong></td>
</tr>
<tr class="odd">
<td>Newly examined content</td>
<td style="text-align: right;">—</td>
<td><strong>not identified</strong> (bounded: optional in June)</td>
</tr>
<tr class="even">
<td>Composition of those who sat</td>
<td style="text-align: right;">—</td>
<td><strong>not identified</strong>; runs against the fall</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-budget" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/paper/fig08_attribution_budget.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: The budget as a waterfall. The two quantified components account for <span class="math inline">\(-0.31\)</span> of the <span class="math inline">\(-1.65\)</span>; the remaining <span class="math inline">\(-1.33\)</span> — four fifths — is not attributed to any mechanism.
</figcaption>
</figure>
</div>
<p>Two components can be given a defensible magnitude and together they come to <span class="math inline">\(-0.31\)</span> marks, under a fifth of the region-specific change. <strong>The remaining <span class="math inline">\(-1.33\)</span>, four fifths of the total, is not attributed to anything.</strong></p>
<p>That is a finding rather than an omission. The preceding subsection establishes that it is not attributable, and §4.5 shows what a partial attribution looks like when it is attempted: the marking regime alone spans 59 to 87 per cent of the Physics-specific term, a range wide enough that adopting either end would change the conclusion, and nothing published adjudicates between them. Summing the upper bounds of the individual channels exceeds the quantity to be explained by <span class="math inline">\(+0.38\)</span> marks, which is a direct demonstration that the channels overlap and that treating them additively over-attributes.</p>
</section>
<section id="where-the-reading-load-lies" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="where-the-reading-load-lies"><span class="header-section-number">5.3</span> Where the reading load lies</h2>
<p>The 45 per cent increase in reading load is naturally attributed to the competency items, on the assumption that narrative framing is what lengthens a statement. Direct measurement of the printed statements does not support that attribution. In the longest item, the narrative accounts for 71 words against 70 in its 2025 predecessor, while the demand text — the part that states what is to be done — rises from 88 words to 181. The additional load is in the task specification, not in the context that surrounds it. The examining authority’s own worked reconstruction of the same item, which reaches 66 words for the broken-out step alone, corroborates the measurement independently.</p>
<div id="fig-statements" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-statements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/paper/fig09_statements.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-statements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: <strong>(a)</strong> Statement length item by item, both years, against the length band that the 2027 specification targets. <strong>(b)</strong> Two independent reconstructions of the longest item, forward from a conventional statement and backward from the one issued. <strong>(c)</strong> The paper as a whole: words read, words answered, and the 2027 target.
</figcaption>
</figure>
</div>
<p>This correction does not alter the budget — reading load remains unidentified either way — but it matters for what would follow from a decision to shorten statements, since shortening the narrative and shortening the demand are different interventions with different costs.</p>
</section>
<section id="the-identifying-datum" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="the-identifying-datum"><span class="header-section-number">5.4</span> The identifying datum</h2>
<p>The collinearity is a property of aggregates, not of the examination. At the level of the individual sub-task the four mechanisms separate cleanly, because they act on different sub-tasks and leave different signatures.</p>
<p>A marking regime applied more completely acts on sub-tasks that produce a numerical result and leaves the others untouched; the exposure measurement of §4.5 makes this testable, since 14 to 19 of the paper’s 27 to 32 sub-tasks are so exposed and the remainder are not. A harder or longer item depresses performance on that item for all candidates. Newly examined content depresses performance on the sub-tasks that examine it, and on no others. Reading load acts in proportion to the length of the statement each sub-task carries.</p>
<p>Marks at sub-task level, for a sample of scripts, therefore identify what no aggregate can. Marking panel identifiers would separate a fifth mechanism — between-panel severity — which the aggregate likewise cannot see. Both are generated as a by-product of any marking process that records sub-task marks. The proposition established here is narrow: these quantities, and nothing already published, constitute the information the identification requires.</p>
</section>
</section>
<section id="discussion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Discussion</h1>
<section id="reference-frames-change-the-headline" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="reference-frames-change-the-headline"><span class="header-section-number">6.1</span> Reference frames change the headline</h2>
<p>The figure that circulated, <span class="math inline">\(-1.48\)</span>, is the year-on-year change. Measured against the region’s own 2015–2019 baseline the 2026 fall is <span class="math inline">\(-1.93\)</span>, a third larger, because 2025 already sat 0.45 below that baseline. The series did not fall once; it fell twice, and only the second fall was reported.</p>
<p>The same arithmetic cuts the other way nationally. Against pre-COVID baselines, six of the nine communities sit <em>above</em> their own norm in 2026. A reader told that “Spain is where it was” and a reader told that “Physics collapsed” can both be shown the same ministry series, because the two statements differ only in the reference year. The year-on-year framing is the one that misleads, because 2024 was not an ordinary year to measure from: it was the last sitting under relief-era optionality and, as §4.2 shows, the year the distribution changed shape.</p>
<p>The general point is that in a system where the instrument is rebuilt annually, every claim of the form “marks fell by <span class="math inline">\(x\)</span>” is incomplete unless it carries its reference point, and claims that omit it are not comparable even when they use the same source.</p>
</section>
<section id="what-can-and-cannot-be-projected" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="what-can-and-cannot-be-projected"><span class="header-section-number">6.2</span> What can and cannot be projected</h2>
<p>Interest in a result of this kind is usually prospective. The findings above bear directly on what may be projected, and the answer is: very little.</p>
<p>The cohort term is externally measured and real, but it is between five and seven times smaller than the paper-to-paper variation against which it must be read, and it moves in steps rather than along a slope (§4.6). A linear projection of it would therefore be a precise interval around a model the data reject.</p>
<p>Scenarios can nonetheless be stated, provided they are labelled for what they are: arithmetic under an assumption, not forecasts. If the 2027 paper resembles the 2025 paper, the cohort term alone places the mean near 5.11; if it resembles the 2026 paper, near 3.81. The error bar on either is the two-year band of ordinary paper-to-paper variation, <span class="math inline">\(\pm 2.37\)</span> marks — wider than the distance between the two scenarios. That the interval swallows the difference between the scenarios is not a defect of the calculation. It is the result: <strong>the paper, not the cohort, determines the outcome, and the paper is a decision rather than a trend.</strong></p>
</section>
<section id="what-a-reader-may-conclude" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="what-a-reader-may-conclude"><span class="header-section-number">6.3</span> What a reader may conclude</h2>
<p>Three statements are supported. The 2025 fall was national, and the region moved with the country to within three hundredths of a mark. The 2026 fall is region-specific, at <span class="math inline">\(-1.65\)</span> marks against the field, and slightly more than half of it is not specific to Physics but common to the region’s quantitative subjects. And four fifths of the region-specific change cannot be attributed to any mechanism with published data.</p>
<p>Three statements are not supported, though each has been made. That the national competency reform caused the fall: it applied everywhere and six of nine rose under it. That the cohort caused it: the externally measured cohort movement is an order of magnitude too small, and 5.6 per cent <em>fewer</em> candidates sat the subject in 2026, so composition works against the fall rather than for it. And that the marking regime caused it: that hypothesis is consistent with the timing and is bounded between 59 and 87 per cent of the Physics-specific term, which is not the same as being established at either end.</p>
</section>
</section>
<section id="limitations" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Limitations</h1>
<p>The 2026 cross-section is nine communities assembled from sources of mixed quality, not a published statistic, and it is not a random sample of the seventeen. With <span class="math inline">\(n = 9\)</span> the reform-intensity association is descriptive and collapses when the single extreme point is removed, as §4.4 states.</p>
<p>Every quantity in this article is a cohort statistic from a different examination, marked by different panels, in a system where the instrument changes annually. None of the comparisons is a causal estimate and none is presented as one. The simulation of §3.6 is a bounding exercise whose inputs — the rate at which deductions were applied and their distribution across candidates — are not observed; its output is a range precisely because those inputs are unknown.</p>
<p>The locus of §3.2 is fitted on 187 observations spanning a period that includes the pandemic relief measures. Those years are identified in <a href="#fig-series" class="quarto-xref">Figure&nbsp;2</a> and the sensitivity of the locus to their inclusion is reported in the appendix, but the panel is not long enough to exclude them and retain useful precision.</p>
<p>Finally, the article establishes that four fifths of the region-specific change is unidentifiable from published aggregates. It does not establish that no mechanism dominates — only that the published data cannot say which.</p>
</section>
<section id="conclusion" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusion</h1>
<p>A single region’s Physics entrance mean fell 1.48 marks in one year while the comparator field rose 0.17. The national curriculum reform that was blamed applied equally to communities that rose, and cannot be the cause. Measured against the field, <span class="math inline">\(-1.65\)</span> marks are region-specific, and an exact subject decomposition shows that <span class="math inline">\(-1.18\)</span> of the region’s movement was common to all its quantitative subjects and only <span class="math inline">\(-1.10\)</span> specific to Physics — so a single-subject analysis would misattribute more than half of the event.</p>
<p>Of the region-specific change, <span class="math inline">\(-0.31\)</span> marks can be bounded: withdrawn optionality and an externally measured cohort term. The remaining <span class="math inline">\(-1.33\)</span> cannot be attributed, because the four candidate mechanisms displace the distribution in the same direction and are therefore indistinguishable in any function of it. A simulation of the marking regime illustrates the size of the resulting indeterminacy: it accounts for anywhere between 59 and 87 per cent of the Physics-specific term depending on assumptions the published data cannot adjudicate, and summing the channels’ upper bounds over-attributes the quantity to be explained by <span class="math inline">\(+0.38\)</span> marks.</p>
<p>The contribution is therefore a quantified limit on what published educational aggregates can identify, obtained on a case where the limit binds hard, together with a decomposition framework that isolates the part of an outcome that is genuinely subject-specific and a statement of the datum — marks at sub-task level — that would remove the indeterminacy. Systems that publish only aggregates should expect this limit to bind whenever more than one plausible mechanism moves the whole distribution in the same direction, which is to say in most of the cases that prompt an investigation at all.</p>
</section>
<section id="author-note" class="level1 unnumbered">
<h1 class="unnumbered">Author note</h1>
<p>The author coordinates the Physics examination that is the subject of this article. The analysis uses only aggregates that were publicly available at the time of writing, listed in §2 with their provenance; no data available to the author by virtue of that role were used, and the quantities identified in §5.4 as the ones that would resolve the indeterminacy are not among the data used here. Every figure and table is generated from the cited files by scripts that reproduce them on a clean run.</p>
</section>
<section id="data-and-code-availability" class="level1 unnumbered">
<h1 class="unnumbered">Data and code availability</h1>
<p>All source files, analysis scripts and figure code are published alongside this article. A clean run reproduces every table byte for byte and every figure pixel for pixel. The extended technical treatment referenced throughout reports the intermediate quantities and the diagnostic tests for each result.</p>
</section>
<section id="appendix-a-provenance-and-quality-of-the-2026-cross-section" class="level1 unnumbered">
<h1 class="unnumbered">Appendix A — Provenance and quality of the 2026 cross-section</h1>
<div id="tbl-provenance" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[24,52,24]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-provenance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Provenance and quality tier of each 2026 figure. The Catalan figure is on the <em>aptes</em> basis, which differs from the ministry basis; comparisons involving it are made <em>aptes</em>-to-<em>aptes</em>.
</figcaption>
<div aria-describedby="tbl-provenance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 52%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th>Community</th>
<th>2026 source</th>
<th>Tier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>País Vasco</td>
<td>institutional presentation of 6 July 2026</td>
<td>institutional</td>
</tr>
<tr class="even">
<td>Cataluña</td>
<td>Govern dossier, <em>aptes</em> basis</td>
<td>official</td>
</tr>
<tr class="odd">
<td>Madrid</td>
<td>regional publication, chart labels</td>
<td>official</td>
</tr>
<tr class="even">
<td>Andalucía</td>
<td>Junta table</td>
<td>official</td>
</tr>
<tr class="odd">
<td>Asturias</td>
<td>university release</td>
<td>institutional</td>
</tr>
<tr class="even">
<td>Comunitat Valenciana</td>
<td>regional publication</td>
<td>official</td>
</tr>
<tr class="odd">
<td>Castilla-La Mancha</td>
<td>interactive dashboard</td>
<td>official</td>
</tr>
<tr class="even">
<td>Canarias</td>
<td>interactive dashboard</td>
<td>official</td>
</tr>
<tr class="odd">
<td>Extremadura</td>
<td>press report</td>
<td>press — excluded from conclusions</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="appendix-b-locus-diagnostics" class="level1 unnumbered">
<h1 class="unnumbered">Appendix B — Locus diagnostics</h1>
<p>The locus of §3.2 is fitted across 187 community-year observations. The mean-band relation is strong and monotonic over the observed range; residual standard deviations are reported per band with the fit. The pandemic years 2020 and 2021 are the highest-leverage observations in the panel and are flagged as such; refitting without them changes the predicted band movement for a fall of 0.21 in the mean by less than half a percentage point, which does not alter the sign or the order of magnitude of the 2024 departure reported in §4.2.</p>
<p>The conditional residual of §3.3 is standardised across the 170 transitions. Because the standardisation is within-year, a common national movement does not enter it, which is the property that makes it usable for the comparison in §4.2.</p>
</section>
<section id="appendix-c-simulation-specification" class="level1 unnumbered">
<h1 class="unnumbered">Appendix C — Simulation specification</h1>
<p>The candidate population is constructed non-parametrically from the published 2025 grade-band distribution, so that the simulated 2025 marks reproduce the published 2025 marks by construction. Sub-task marks are allocated within each candidate at a fixed item standard deviation, with sensitivity reported at 0.1, 0.2 and 0.3.</p>
<p>Deductions are applied at a specified rate per candidate, each at the fixed value the specification names, with a floor at zero for each sub-task; grave errors void the sub-task in which they occur, under both a cascading and an independent regime. Penalties are distributed across candidates by a kernel in the candidate’s own attainment level, normalised to unit mean, with over-dispersion examined separately. The linguistic component enters only on sub-tasks that produce text and is capped as the specification requires.</p>
<p>The reported output is the range of the Physics-specific fall reproduced across this space, not a point estimate, because the rate and the distribution of deductions are not observed.</p>
</section>
<section id="appendix-d-reproduction" class="level1 unnumbered">
<h1 class="unnumbered">Appendix D — Reproduction</h1>
<p>Every figure and table in this article is produced from the cited data files by the published scripts. The figures shown here and the corresponding figures in the extended technical treatment are drawn by the same panel code at different page proportions, so the two cannot differ in any quantity — only in layout.</p>



</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-madrid2026pau" class="csl-entry" role="listitem">
Comunidad de Madrid. (2026). <em>Presentaci<span>ó</span>n de resultados <span>PAU</span> 2026</em>. <a href="https://www.comunidad.madrid/docs/2026-06/presentacion-resultados-pau-2026_vd.pdf">https://www.comunidad.madrid/docs/2026-06/presentacion-resultados-pau-2026_vd.pdf</a>
</div>
<div id="ref-ehu2026notak" class="csl-entry" role="listitem">
Euskal Herriko Unibertsitatea. (2026). <em><span>USaP</span> kalifikazioen inguruan (<span>USaP</span> proben kalifikazioak)</em>. Presentation attached to the Campusa release of 6 July 2026, 14 pp. <a href="https://www.ehu.eus/documents/d/campusa/20260706-notak-po">https://www.ehu.eus/documents/d/campusa/20260706-notak-po</a>
</div>
<div id="ref-govern2026dossier" class="csl-entry" role="listitem">
Generalitat de Catalunya. (2026). <em>Proves d’acc<span>é</span>s a la universitat (<span>PAU</span>). Convocat<span>ò</span>ria ordin<span>à</span>ria 2026. Dossier de resultats</em>. Govern.cat press dossier, 23 June 2026, 25 pp. <a href="https://govern.cat/govern/docs/2026/06/23/12/39/Dossier_resultats%20PAU%202026.pdf">https://govern.cat/govern/docs/2026/06/23/12/39/Dossier_resultats%20PAU%202026.pdf</a>
</div>
<div id="ref-gva2026junio" class="csl-entry" role="listitem">
Generalitat Valenciana, Conselleria d’Educació, Universitats i Ocupació. (2026). <em>Estad<span>í</span>sticas <span>PAU</span> <span>JUNIO</span> 2026 / <span>JULIO</span> 2026 / <span>GLOBALES</span> 2026</em>. <a href="https://universitats.gva.es/es/estadistiques">https://universitats.gva.es/es/estadistiques</a>
</div>
<div id="ref-rd534_2024" class="csl-entry" role="listitem">
Gobierno de España. (2024). <em>Real decreto 534/2024, de 11 de junio, por el que se regulan los requisitos de acceso a las ense<span>ñ</span>anzas universitarias oficiales de grado, las caracter<span>í</span>sticas b<span>á</span>sicas de la prueba de acceso y la normativa b<span>á</span>sica de los procedimientos de admisi<span>ó</span>n</em>. BOE n.&nbsp;142, 12 June 2024 (consolidated text as amended by RD 482/2025). <a href="https://www.boe.es/buscar/act.php?id=BOE-A-2024-11858">https://www.boe.es/buscar/act.php?id=BOE-A-2024-11858</a>
</div>
<div id="ref-junta2026pevau" class="csl-entry" role="listitem">
Junta de Andalucía. (2026). <em>El 90,63% del alumnado supera la <span>PEvAU</span> en la convocatoria ordinaria. Notas medias por materias</em>. Nota de prensa, 11 June 2026. <a href="https://www.juntadeandalucia.es/organismos/universidadinvestigacioneinnovacion/servicios/actualidad/noticias/detalle/667462.html">https://www.juntadeandalucia.es/organismos/universidadinvestigacioneinnovacion/servicios/actualidad/noticias/detalle/667462.html</a>
</div>
<div id="ref-siiu_epau2025" class="csl-entry" role="listitem">
Ministerio de Ciencia, Innovación y Universidades (SIIU). (2026). <em>Estad<span>í</span>stica de las pruebas de acceso a la universidad. Curso 2024–2025 (a<span>ñ</span>o 2025)</em>. PC-Axis tables px_pau_gen_materias_{nota,matric,distr}_fase_ca, published 8 June 2026. <a href="https://www.ciencia.gob.es/Ministerio/Estadisticas/SIIU/PAU.html">https://www.ciencia.gob.es/Ministerio/Estadisticas/SIIU/PAU.html</a>
</div>
<div id="ref-uniovi2026junio" class="csl-entry" role="listitem">
Universidad de Oviedo. (2026). <em>El 95,12% del estudiantado aprueba la <span>PAU</span> en <span>Asturias</span> en la convocatoria de junio</em>. Nota de prensa, 12 June 2026. <a href="https://www.uniovi.es/actualidad/noticias/-/asset_publisher/Ru0cAJNPrm1m/content/el-95-12-del-estudiantado-aprueba-la-pau-en-asturias-en-la-convocatoria-de-junio">https://www.uniovi.es/actualidad/noticias/-/asset_publisher/Ru0cAJNPrm1m/content/el-95-12-del-estudiantado-aprueba-la-pau-en-asturias-en-la-convocatoria-de-junio</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/07-literature.html" class="pagination-link" aria-label="Literature &amp; regulation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Literature &amp; regulation</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/15-synthesis.html" class="pagination-link" aria-label="Synthesis for the coordination">
        <span class="nav-page-text">Synthesis for the coordination</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Independent analysis prepared 18–19 September 2026, audited 19 and 20 September · all figures reproducible from <code>scripts/</code></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Data: EHU, SIIU/EPAU, Generalitat de Catalunya, GVA, Junta de Andalucía, CM, Uniovi, UCLM, ULL, ULPGC, UNIZAR, UPNA, UMU, UC, CiUG, UR</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>