<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-18">
<meta name="description" content="A structured reading of the hypotheses for the 2026 Basque Physics result against the assembled evidence, the institutional narrative after 6 July, and a prioritised list of data requests and design choices for PAU 2027.">

<title>Interpretation and the 2027 question – PAU Física 2026</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/11-exam-content.html" rel="next">
<link href="../chapters/05-subjects-sittings.html" rel="prev">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-34ccee47bae06f2332eb94a15df79591.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0c8081985eeeb50794d30fa8d31fc890.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-34ccee47bae06f2332eb94a15df79591.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-29e5ce9c295aebebc96a6ba847e0be6c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-e0926ce36429a4f6419cf7f43c044cdd.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-29e5ce9c295aebebc96a6ba847e0be6c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css?family=Inter:400,400i,500,600,700%7CJetBrains+Mono:400,700&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/favicon.svg" alt="PAU Física 2026" class="navbar-logo light-content">
    <img src="../assets/favicon.svg" alt="PAU Física 2026" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PAU Física</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/02-euskadi.html"> 
<span class="menu-text">The Euskadi break</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/03-spain-2026.html"> 
<span class="menu-text">Spain 2026</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/08-sources.html"> 
<span class="menu-text">Sources &amp; methods</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-euskadi.html">Evidence and results</a></li><li class="breadcrumb-item"><a href="../chapters/06-interpretation.html">Interpretation &amp; 2027</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><i class="bi bi-house" role="img">
</i> 
 <span class="menu-text">Findings</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence and results</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-euskadi.html" class="sidebar-item-text sidebar-link"><i class="bi bi-bar-chart-line" role="img">
</i> 
 <span class="menu-text">Euskadi 2010–2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-spain-2026.html" class="sidebar-item-text sidebar-link"><i class="bi bi-globe-europe-africa" role="img">
</i> 
 <span class="menu-text">Spain 2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-distributions.html" class="sidebar-item-text sidebar-link"><i class="bi bi-graph-up" role="img">
</i> 
 <span class="menu-text">Shape of the collapse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-subjects-sittings.html" class="sidebar-item-text sidebar-link"><i class="bi bi-people" role="img">
</i> 
 <span class="menu-text">Subjects &amp; participation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-interpretation.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-compass" role="img">
</i> 
 <span class="menu-text">Interpretation &amp; 2027</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">The papers</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-exam-content.html" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-text" role="img">
</i> 
 <span class="menu-text">The papers themselves</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-ehu-paper-history.html" class="sidebar-item-text sidebar-link"><i class="bi bi-clock-history" role="img">
</i> 
 <span class="menu-text">Sixteen years of one paper</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Research context</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-data-hunt.html" class="sidebar-item-text sidebar-link"><i class="bi bi-search" role="img">
</i> 
 <span class="menu-text">The data hunt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-literature.html" class="sidebar-item-text sidebar-link"><i class="bi bi-journal-text" role="img">
</i> 
 <span class="menu-text">Literature &amp; regulation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Sources and reproducibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-sources.html" class="sidebar-item-text sidebar-link"><i class="bi bi-archive" role="img">
</i> 
 <span class="menu-text">Sources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-log.html" class="sidebar-item-text sidebar-link"><i class="bi bi-list-check" role="img">
</i> 
 <span class="menu-text">Work log</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-reproduce.html" class="sidebar-item-text sidebar-link"><i class="bi bi-code-slash" role="img">
</i> 
 <span class="menu-text">Reproduce the study</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-hypotheses-one-by-one" id="toc-the-hypotheses-one-by-one" class="nav-link active" data-scroll-target="#the-hypotheses-one-by-one">The hypotheses, one by one</a>
  <ul class="collapse">
  <li><a href="#is-the-drift-real" id="toc-is-the-drift-real" class="nav-link" data-scroll-target="#is-the-drift-real">Is the drift real?</a></li>
  <li><a href="#a-basque-signal-that-arrives-a-year-early" id="toc-a-basque-signal-that-arrives-a-year-early" class="nav-link" data-scroll-target="#a-basque-signal-that-arrives-a-year-early">A Basque signal that arrives a year early</a></li>
  <li><a href="#an-instrument-the-basque-tribunals-do-not-mark" id="toc-an-instrument-the-basque-tribunals-do-not-mark" class="nav-link" data-scroll-target="#an-instrument-the-basque-tribunals-do-not-mark">An instrument the Basque tribunals do not mark</a></li>
  <li><a href="#do-the-two-instruments-fall-at-the-same-rate" id="toc-do-the-two-instruments-fall-at-the-same-rate" class="nav-link" data-scroll-target="#do-the-two-instruments-fall-at-the-same-rate">Do the two instruments fall at the same rate?</a></li>
  <li><a href="#how-much-of-the-paper-is-reading" id="toc-how-much-of-the-paper-is-reading" class="nav-link" data-scroll-target="#how-much-of-the-paper-is-reading">How much of the paper is reading?</a></li>
  <li><a href="#what-pisa-2025-says-about-pau-2027" id="toc-what-pisa-2025-says-about-pau-2027" class="nav-link" data-scroll-target="#what-pisa-2025-says-about-pau-2027">What PISA 2025 says about PAU 2027</a></li>
  </ul></li>
  <li><a href="#was-2026-a-shift-or-a-change-of-shape" id="toc-was-2026-a-shift-or-a-change-of-shape" class="nav-link" data-scroll-target="#was-2026-a-shift-or-a-change-of-shape">Was 2026 a shift or a change of shape?</a></li>
  <li><a href="#what-you-compare-against-decides-what-you-find" id="toc-what-you-compare-against-decides-what-you-find" class="nav-link" data-scroll-target="#what-you-compare-against-decides-what-you-find">What you compare against decides what you find</a></li>
  <li><a href="#how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one" id="toc-how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one" class="nav-link" data-scroll-target="#how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one">How this reading was arrived at, and what it cost each earlier one</a></li>
  <li><a href="#the-institutional-record-since-6-july" id="toc-the-institutional-record-since-6-july" class="nav-link" data-scroll-target="#the-institutional-record-since-6-july">The institutional record since 6 July</a></li>
  <li><a href="#what-to-ask-for-in-order-of-value" id="toc-what-to-ask-for-in-order-of-value" class="nav-link" data-scroll-target="#what-to-ask-for-in-order-of-value">What to ask for, in order of value</a></li>
  <li><a href="#design-questions-for-2027-that-the-data-already-inform" id="toc-design-questions-for-2027-that-the-data-already-inform" class="nav-link" data-scroll-target="#design-questions-for-2027-that-the-data-already-inform">Design questions for 2027 that the data already inform</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-euskadi.html">Evidence and results</a></li><li class="breadcrumb-item"><a href="../chapters/06-interpretation.html">Interpretation &amp; 2027</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Interpretation and the 2027 question</h1>
<p class="subtitle lead">Which explanations survive the evidence, what would decide between the rest, and what to ask for</p>
  <div class="quarto-categories">
    <div class="quarto-category">findings</div>
    <div class="quarto-category">interpretation</div>
    <div class="quarto-category">2027</div>
  </div>
  </div>

<div>
  <div class="description">
    A structured reading of the hypotheses for the 2026 Basque Physics result against the assembled evidence, the institutional narrative after 6 July, and a prioritised list of data requests and design choices for PAU 2027.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-hypotheses-one-by-one" class="level2">
<h2 class="anchored" data-anchor-id="the-hypotheses-one-by-one">The hypotheses, one by one</h2>
<p>The evidence assembled in Chapters 2–5 is observational and the exam changes every year, so nothing below is a causal estimate. But the hypotheses that circulated in July can be sorted by what the data allow.</p>
<p><strong>H1 — “The competency model (RD 534/2024) is to blame.”</strong> <em>Explains 2025, not 2026.</em> The model was applied in all seventeen communities in both years. In 2025 the Física mean fell in 14 of 17, by <span class="math inline">\(-0.81\)</span> on average — Euskadi’s <span class="math inline">\(-0.62\)</span> was below the national move. In 2026 at least six of nine reporting communities rose by <span class="math inline">\(+0.5\)</span> to <span class="math inline">\(+1.1\)</span> under the same model; Euskadi fell <span class="math inline">\(-1.48\)</span>. A national cause cannot produce opposite signs in the same year. The Basque institutions’ July framing (“el nuevo enfoque competencial pasa factura”) is therefore at most a description of 2025. There is a further difficulty with it: the only systematic rating of PAU papers’ competency orientation, covering six communities over 2015–2025 <span class="citation" data-cites="sancheztarazaga2026pau">(<a href="#ref-sancheztarazaga2026pau" role="doc-biblioref">Sánchez-Tarazaga &amp; Gimeno Rovira, 2026</a>)</span>, places País Vasco and Cataluña at the <em>top</em> of the range before the reform, so the Basque papers did not “become competency-based” in 2025 — they were already the most competency-oriented in Spain, and Cataluña, rated alongside them, rose in 2026.</p>
<p><strong>H2 — “The 2026 Basque Física paper was harder, or differently pitched, than its own 2025 paper and than other communities’ 2026 papers.”</strong> <em>Consistent with everything.</em> The cohort-wide displacement of the distribution (<a href="../chapters/04-distributions.html">Chapter 4</a>), the confinement of the damage to Física and Matemáticas II with Química, Biología and Lengua unaffected (<a href="../chapters/05-subjects-sittings.html">Chapter 5</a>), the Catalan mirror image (Física up, Matemàtiques down, same authority, same cohort) and the Canarian coordinators’ own reading of their milder 2025 all point to the paper — its problems, its optionality (two of four problems with no choice in 2026), its marking scheme — as the first-order variable. The July package already noted that the 2026 ordinary paper’s gravitational problem contains a validity issue in its energy comparison. A structured content audit of the 2025 and 2026 papers of the nine communities with a 2026 result was carried out on 19 September and is reported in <a href="../chapters/11-exam-content.html">The papers themselves</a>: none of the six rising communities increased the competency content of its paper (five stayed at zero or fell; Castilla-La Mancha added one obligatory contextualised item), while the Basque paper moved from one competency exercise to half the marks, halved its optionality and changed format at the same time — it is the only paper in the set that changed genre between the two years. The comparison with the 2010–2024 Basque papers is in <a href="../chapters/12-ehu-paper-history.html">Sixteen years of one paper</a>: the 2025 break (no theory questions, new structure, first numerical penalties) was absorbed better than the national average; the 2026 step (competencial half, choice halved, −0.1 list and symbolic-first, syllabus opened) is the one the grades react to. An item-level analysis of the 2026 scripts is the natural continuation.</p>
<p><strong>H3 — “Tribunals marked more severely.”</strong> <em>Possible, unmeasured, and acknowledged by EHU.</em> The rector’s press conference reported “significant variation between evaluation panels” in Física among other subjects <span class="citation" data-cites="argia2026ehu">(<a href="#ref-argia2026ehu" role="doc-biblioref">Argia, 2026</a>)</span>, and the 6 July deck published tribunal-mean ranges for Euskara (2.88–4.43), Lengua (5.80–6.92) and Inglés (6.65–7.56) but not for Física. Rater-severity effects of the size needed to move a subject mean by more than a point are not unknown in Spanish PAU marking <span class="citation" data-cites="veas2025consistency">(<a href="#ref-veas2025consistency" role="doc-biblioref">Veas &amp; López-Pina, 2025</a>)</span>, but the cohort-wide shape of the 2026 distribution says severity, if present, was general rather than confined to a few panels. Only the tribunal-level Física table settles this.</p>
<p><strong>H4 — “The cohort was weaker or differently composed.”</strong> <em>Weak inside the PAU data, stronger outside it. The recruitment version fails outright (<a href="#is-the-drift-real">below</a>) and the PAU shows no drift; but an externally marked instrument shows Basque science falling from +9 points above Spain to −5 over the decade, breaking in 2015 (<a href="#an-instrument-the-basque-tribunals-do-not-mark">below</a>).</em> Presentation fell 6 % from 2025 and enrolment is unpublished, so a small compositional component cannot be excluded, but the school marks of the preceding cohort were 7.09 with 98 % passing, and the same students’ Química and Biología marks did not move. A weaker cohort does not fail Física and Matemáticas by 1.5 points while holding Química. What the conditional measure adds is narrower and concerns the top of the distribution only.</p>
<section id="is-the-drift-real" class="level3">
<h3 class="anchored" data-anchor-id="is-the-drift-real">Is the drift real?</h3>
<p>H4 is usually posed as a claim about one cohort, but it has a slower version worth testing separately: that the students presenting for Física arrive a little less prepared each year, so that part of 2025 and 2026 is the end of a long drift rather than an event. The mechanism is concrete. Física is voluntary, its examined population grew 30 % over this decade — from 37,661 to 49,010 — and a subject that recruits more widely should be recruiting further down the distribution.</p>
<p>The counts matter here more than usual, and an earlier version of this section got them wrong. Física appears in both phases until 2016 and only in the specific phase from 2017, so counting the specific phase alone understates 2015 and 2016 by about 18 % — 30,839 against a true 37,661 in 2015. Those two years then present as small-cohort years that happen to have high means, and a dilution effect appears which is not there. Every count below is pooled across phases.</p>
<div id="fig-drift" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-drift-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig20_cohort_drift.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-drift-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <strong>a</strong> — the national mean by year with the 2015–2019 trend extrapolated forward, and the number presented (pooled across phases) on the right-hand axis. The shaded plateau years are the ones that cannot be used to measure a drift. <strong>b</strong> — take-up, the share of each community’s PAU candidates sitting Física, with the pooled national series in black; it is flat. <strong>c</strong> — the dilution test on take-up: each point is a community-year, with both variables expressed as deviations from that community’s own average, so the comparison is a community against itself rather than against communities that differ for other reasons. The fitted line is flat, and the raw-cohort-size version of the same test is no better.
</figcaption>
</figure>
</div>
<p>Three tests. The two that can see composition find nothing, and the one that appears to support the intuition cannot tell students from papers.</p>
<p>The pre-COVID years do decline, at <span class="math inline">\(-0.071\)</span> points a year with <span class="math inline">\(R^2 = 0.75\)</span> (<span class="math inline">\(p = 0.058\)</span>) — five points falling steadily, which is what the intuition predicts. But the decline did not continue: extrapolated to 2025 that trend projects a mean of 5.20, and the actual 2025 mean is <strong>5.67</strong>, <span class="math inline">\(+0.47\)</span> above it. Whatever was pulling the mean down between 2015 and 2019 either stopped or was offset.</p>
<p>The dilution mechanism is not detectable at all, and this is where the count correction bites. On the undercounted series it looked real and modest — <span class="math inline">\(r = -0.212\)</span>, <span class="math inline">\(p = 0.032\)</span> — which is what an earlier version of this section reported. On the pooled counts it disappears: <span class="math inline">\(r = -0.064\)</span>, <span class="math inline">\(p = 0.525\)</span> over the same 102 non-plateau region-years. The entire apparent effect was two mislabelled years.</p>
<p>Panels b and c of <a href="#fig-drift" class="quarto-xref">Figure&nbsp;1</a> test it on the variable that actually corresponds to the mechanism. Raw cohort size confounds a community whose whole candidate population grew with one in which a larger fraction chose Física; only the second is composition. Using <code>Lengua Castellana y Literatura II</code> — compulsory in the general phase, hence a count of candidates — as the denominator, take-up is the share of a community’s PAU candidates sitting Física. It has barely moved: <strong>0.222 in 2015, 0.241 in 2025</strong>, a rise of 8 % in relative terms across a decade. And within a community it is unrelated to the mean: <span class="math inline">\(r = -0.020\)</span>, <span class="math inline">\(p = 0.839\)</span>. Física is not visibly recruiting further down the distribution, because it is not visibly recruiting more widely at all.</p>
<p>And the shape measure shows nothing either. The conditional top-band share has no significant trend across the non-plateau years (<span class="math inline">\(-0.0029\)</span> a year, <span class="math inline">\(p = 0.082\)</span>), which is where a recruitment effect should show first and most clearly.</p>
<p>The honest summary is that the drift is not visible on any measure that can see composition, and that the one measure suggesting a fall — the 2015–19 trend in the mean — cannot distinguish students from papers. The reason is visible in panel a of <a href="#fig-drift" class="quarto-xref">Figure&nbsp;1</a> and is the same obstruction that produced the reference-frame problem: the five years in the middle of the decade are the plateau, and they are unusable for estimating a slow trend. Six year-points remain to fit a decade. That is why none of these tests is decisive, and it is a better reason to withhold judgement than any of the individual <span class="math inline">\(p\)</span>-values — a drift of <span class="math inline">\(-0.07\)</span> a year would need about fifteen clean years to separate from noise, and this decade contains six.</p>
<p>One consequence for the reading of 2026: a slow drift and a one-year event are not competing explanations here. The composition channel, which is the one that could have been measured, contributes nothing detectable, and the pre-2019 decline in the mean — the only surviving evidence of a drift — is confounded between the students and the paper in exactly the way this chapter cannot resolve from PAU data alone.</p>
</section>
<section id="a-basque-signal-that-arrives-a-year-early" class="level3">
<h3 class="anchored" data-anchor-id="a-basque-signal-that-arrives-a-year-early">A Basque signal that arrives a year early</h3>
<p>The conditional ratio of <a href="#fig-locus" class="quarto-xref">Figure&nbsp;6</a> turns up something none of the level-based figures did. Measured against the common locus, and then against the field in the same year, Euskadi’s share of top-band students among its passers sat <strong>+0.64 SD above the other communities on average across 2016–2023</strong> — the Basque cohort reliably produced more high marks than its own mean would predict. In 2024 that reverses to <span class="math inline">\(-0.96\)</span> SD relative to the field, and in 2025 it is still <span class="math inline">\(-0.52\)</span>.</p>
<p>Two things make this worth recording. It is not a single point: it is a two-year turn away from eight consecutive years on the other side. And it <em>predates both candidate causes</em> — it begins in 2024, a year before the competency model of RD 534/2024 was applied and two years before the 2026 paper.</p>
<p>The natural reading is the one about the cohort: that the top of the Basque Física cohort had begun to thin before anything changed in the examination. The school record complicates it rather than confirming it. The 2024–25 Bachillerato Física cohort scored 7.09 with 98 % passing, so whatever the exam was detecting, school assessment was not — and the gap between school and PAU marks widens from 1.62 in 2025 to 3.10 in 2026 on unchanged school marks. Either school assessment is not tracking the competence the PAU tests at the upper end, or the PAU stopped rewarding it. The ratio cannot distinguish those, because a thinner top tail and a paper that discriminates less at the top produce the same signature.</p>
<p>What it does establish is that the Basque series was already moving in 2024 on a measure that the mean, the pass rate and the 8–10 share all missed — each of those was unremarkable that year. That is an argument for adding the conditional ratio to the routine monitoring proposed <a href="#what-to-ask-for-in-order-of-value">below</a>, and it is an argument against treating 2026 as the beginning of the story.</p>
</section>
<section id="an-instrument-the-basque-tribunals-do-not-mark" class="level3">
<h3 class="anchored" data-anchor-id="an-instrument-the-basque-tribunals-do-not-mark">An instrument the Basque tribunals do not mark</h3>
<p>The ambiguity above — a thinner top tail or a paper that stopped rewarding it — is not resolvable from the PAU, because the PAU produces one number for both. It needs an instrument that measures the same students and is marked elsewhere. PISA is that instrument, and the cohorts can be matched exactly: PISA tests 15-year-olds, modal 4º ESO, who reach the PAU two years later.</p>
<p>That alignment also says what <em>cannot</em> be done. Only three PISA rounds fall inside this study’s PAU window — 2015 → PAU 2017, 2018 → PAU 2020, 2022 → PAU 2024 — and two of the three land in the marking plateau. A PAU–PISA correlation would be three points with two contaminated, and none is attempted here. What is available is one aligned cohort, compared on the one quantity both instruments measure at the same place in the distribution: PISA’s proficiency levels 5 and 6 are the top of its scale as the 8–10 band is the top of the PAU’s.</p>
<div id="fig-pisa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pisa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig21_pisa_link.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pisa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: <strong>a</strong> — the science score of País Vasco and Spain across every PISA round from 2006 to 2022. The shaded band marks the school closures of 2020–21. <strong>b</strong> — the same series as a gap, with the PAU year each cohort reaches. <strong>c</strong> — the three cohorts matched to a PAU year inside this study’s window, with the PISA gap on the horizontal axis and the PAU conditional top-band measure on the vertical; agreement would place every point in the lower-left or upper-right quadrant.
</figcaption>
</figure>
</div>
<p>The long series settles the question the two-round version could not, and it settles it against the reading offered here in an earlier draft. Across 2006, 2009 and 2012 the Basque science score ran <strong>+6.2, +6.4 and +9.2 points above Spain</strong>. Between 2012 and 2015 it fell <strong>22.6 points</strong> while Spain fell 3.7, and it has not recovered: <span class="math inline">\(-9.7\)</span> against Spain in 2015, <span class="math inline">\(+4.1\)</span> in 2018, <span class="math inline">\(-5.0\)</span> in 2022. Over the decade to 2022 the Basque fall is <strong>26 points against Spain’s 12</strong>.</p>
<p>The break is in the <strong>2015 round</strong> — administered five years before the schools closed. An earlier version of this section read only 2018 and 2022, found the Basque top tail thin in 2022, and attributed it to the pandemic cohort. That was wrong, and wrong in a way that mattered: it was offered as a reason to <em>discount</em> the slow-drift reading, and the earlier rounds show the opposite. A standing Basque advantage in science became a deficit a decade ago, on an instrument marked outside the Basque system, and stayed one.</p>
<p>The top of the distribution tells the same story without a trend. The Basque share at proficiency levels 5–6 in science runs 3.25 % in 2015, 3.87 % in 2018 and 3.32 % in 2022, against Spanish figures of 4.98 %, 4.18 % and 4.92 %. There is no progressive thinning: 2015 is as low as 2022. What there is, is a level that has sat below Spain’s in two rounds of three and below the OECD’s (7.47 % in 2022) in all of them.</p>
<p><strong>But the cohorts do not line up.</strong> This is the second correction, and it undoes the triangulation this section originally claimed. Of the three PISA rounds that map onto a PAU year inside the study window, only one agrees with the PAU conditional measure:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cohort</th>
<th>PISA gap vs Spain</th>
<th>PAU conditional vs field</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PISA 2015 → PAU 2017</td>
<td><span class="math inline">\(-9.7\)</span></td>
<td><span class="math inline">\(+0.70\)</span> SD</td>
<td>disagree</td>
</tr>
<tr class="even">
<td>PISA 2018 → PAU 2020</td>
<td><span class="math inline">\(+4.1\)</span></td>
<td><span class="math inline">\(-0.82\)</span> SD</td>
<td>disagree</td>
</tr>
<tr class="odd">
<td>PISA 2022 → PAU 2024</td>
<td><span class="math inline">\(-5.0\)</span></td>
<td><span class="math inline">\(-0.96\)</span> SD</td>
<td>agree</td>
</tr>
</tbody>
</table>
<p>One of three is what chance produces. The 2022/2024 match, which this section was originally built around, is not evidence of a cohort mechanism; it is the one case out of three in which two noisy measures happened to point the same way.</p>
<p>What survives is worth more than what was lost, and it supports the drift reading rather than the event reading. There is a real, large and sustained deterioration in Basque science attainment beginning in 2015, visible to an external instrument, which the PAU Física series does not show — Euskadi’s Física mean sits near its own baseline through 2024. Two conclusions follow. The PAU is not a good detector of whatever PISA is measuring, which is unsurprising given that Física is sat by a self-selected quarter of the cohort. And the slow-drift version of H4, which the <a href="#is-the-drift-real">previous section</a> could not find in the PAU data, is clearly present in the schooling that precedes it. Those are compatible: a decade-long weakening of the base need not show in a subject whose takers are drawn from the top of it.</p>
</section>
<section id="do-the-two-instruments-fall-at-the-same-rate" class="level3">
<h3 class="anchored" data-anchor-id="do-the-two-instruments-fall-at-the-same-rate">Do the two instruments fall at the same rate?</h3>
<p>The cohort test above compares single years and finds noise. A gentler question is whether the two series, taken whole, descend at the same rate — whether <a href="#fig-drift" class="quarto-xref">Figure&nbsp;1</a>’s panel a and <a href="#fig-pisa" class="quarto-xref">Figure&nbsp;2</a>’s panel a are parallel. That is a better question than whether they correlate, which three overlapping points cannot answer, and it turns out to have a more interesting answer than the cohort test did.</p>
<p>It needs a common scale. Each series is divided by its own student-level standard deviation: 2.34 marks for PAU Física, the median of the thirteen published regional standard deviations and consistent with the Beta fits of <a href="../chapters/04-distributions.html">Chapter 4</a>; about 90 points for PISA science, from the p10–p90 spread of the 2015 tables. A slope in standard deviations per decade is then the same quantity on both instruments.</p>
<div id="fig-slopes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig22_slope_compare.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: <strong>a</strong> — the PAU Física mean and the PISA science score for Spain and for Euskadi, each centred on its own mean and divided by its own student-level standard deviation, with the fitted trends. PAU plateau years are shaded and excluded from the fits. <strong>b</strong> — the four slopes with their 95 % intervals.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Series</th>
<th>Slope, SD per decade</th>
<th>95 % interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PAU Física, Spain</td>
<td><span class="math inline">\(-0.092\)</span></td>
<td><span class="math inline">\([-0.251,\ +0.068]\)</span></td>
</tr>
<tr class="even">
<td>PISA science, Spain</td>
<td><span class="math inline">\(-0.147\)</span></td>
<td><span class="math inline">\([-0.381,\ +0.086]\)</span></td>
</tr>
<tr class="odd">
<td>PAU Física, Euskadi</td>
<td><span class="math inline">\(-0.157\)</span></td>
<td><span class="math inline">\([-0.601,\ +0.286]\)</span></td>
</tr>
<tr class="even">
<td>PISA science, Euskadi</td>
<td><span class="math inline">\(-0.245\)</span></td>
<td><span class="math inline">\([-0.785,\ +0.296]\)</span></td>
</tr>
</tbody>
</table>
<p>The point estimates are strikingly consistent. All four decline; the PAU and PISA slopes for the same population differ by <span class="math inline">\(+0.06\)</span> and <span class="math inline">\(+0.09\)</span> SD per decade, differences that no test could distinguish from zero (<span class="math inline">\(p = 0.48\)</span> and <span class="math inline">\(p = 0.67\)</span>). And the relative figure is closer still: <strong>Euskadi falls 1.72 times as fast as Spain on the PAU and 1.66 times as fast on PISA</strong>. Two instruments with nothing in common — different ages, different subjects, different markers, different scales — put the Basque disadvantage at the same multiple of the national one.</p>
<p>That is worth stating because it tempers a claim made in the previous section. There it was said that PISA shows a deterioration the PAU Física series does not. On <em>cohorts</em> that stands, and the matching is one of three. On <em>trend</em> it overstates: the PAU does decline, at a rate whose point estimate sits comfortably inside PISA’s interval, and the reason it looked absent is that the plateau hides it in the raw series and the six surviving year-points cannot make it significant.</p>
<p>The honest summary is the one panel b is drawn to make unavoidable: <strong>every interval includes zero</strong>. With four PISA rounds and six usable PAU years, these data are consistent with two instruments measuring one common decline at the same rate — and equally consistent with no decline at all in either. The agreement of four point estimates, and of two independently computed ratios to within 4 %, is the kind of coincidence that is worth recording and is not worth believing on its own. It is a reason to keep measuring both, which is the recommendation of the next section, rather than a finding.</p>
</section>
<section id="how-much-of-the-paper-is-reading" class="level3">
<h3 class="anchored" data-anchor-id="how-much-of-the-paper-is-reading">How much of the paper is reading?</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Disclosure
</div>
</div>
<div class="callout-body-container callout-body">
<p>The author of this study was involved in setting the 2026 Basque Física paper, and specifically chose to expand the statement of its second exercise — spelling out each requirement and repeating it — because a competency-style <em>saber básico</em> was entering the examined set for the first time. That account is the origin of the hypothesis tested in this section, and it is first-hand evidence no amount of text analysis could have supplied: it establishes that the length was deliberate rather than accidental. It also means this section examines a decision its author made. The provenance note in <a href="../chapters/10-reproduce.html">Methods</a> records the same fact.</p>
</div>
</div>
<p>Every section so far has treated the paper as a single variable — harder or easier, more or less competency-oriented. It has another dimension that is objective, easy to measure and so far unexamined: how much text a candidate must read before answering. The competency reform pushes in exactly that direction, because contextualised items carry a scenario and the scenario has to be written down.</p>
<p>That matters more if the cohort’s reading has weakened, and the Basque cohort’s has, far more than its science. Over the decade to 2025 the País Vasco PISA reading score falls <strong>72 points</strong>, from 491.4 to 419.1, against a science fall of 24.5. The gap to Spain widens from <span class="math inline">\(-4.1\)</span> to <span class="math inline">\(-32.2\)</span>. Whatever else is true of these students, reading is where they have lost most ground. (There is no 2018 point: the Spanish PISA 2018 report contains mathematics and science only, because the OECD withheld Spain’s 2018 reading results over anomalous response patterns.)</p>
<div id="fig-reading" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reading-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig24_reading_load.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reading-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: <strong>a</strong> — change in the length of each community’s ordinary Física paper between 2025 and 2026, in per cent, against the change in its mean mark. Only each community’s change against itself is used, since structures differ. <strong>b</strong> — PISA reading and science for País Vasco, with Spain’s reading for comparison.
</figcaption>
</figure>
</div>
<p>The association is the strongest this study has found between any property of a paper and the movement of its grade: <strong><span class="math inline">\(r = -0.84\)</span>, <span class="math inline">\(p = 0.008\)</span></strong> across the eight communities with both a 2026 result and an archived pair of papers, and <span class="math inline">\(\rho = -0.76\)</span>, <span class="math inline">\(p = 0.028\)</span> on ranks. Stripping rubric and constant tables from the word counts leaves it unchanged at <span class="math inline">\(-0.84\)</span>. Asturias and the Comunitat Valenciana shortened their papers and rose; Extremadura, Canarias and País Vasco lengthened theirs and fell. The Basque paper lengthened <strong>39.5 %</strong>, from 1,452 words to 2,026, and fell furthest.</p>
<p>Three cautions, and the second is the one that matters.</p>
<p>The word count includes everything on the page, and papers that offer more choice print more text for the same student workload. That is why only within-community change is used, and it is why Madrid’s 4,070 words sit unremarked next to Asturias’s 899.</p>
<p><strong>Length and competency content are not independent.</strong> The competency measure of <a href="../chapters/11-exam-content.html">The papers themselves</a> correlates with the length change at <span class="math inline">\(r = +0.87\)</span>. Contextualised items are longer items, so the two are largely one signal seen twice, and with eight points they cannot be separated. What length adds is not a second cause but a better instrument: it is a count, reproducible by anyone with the PDFs, where the competency coding is a judgement made by one reader. That the objective measure correlates twice as strongly with the outcome (<span class="math inline">\(-0.84\)</span> against <span class="math inline">\(-0.47\)</span>) is a reason to prefer it as the measurement, not a reason to believe a new mechanism.</p>
<p>And the interaction that motivated the section — long papers hurting weak readers more than strong ones — is not tested here. Testing it needs the reading level of each community crossed with its length change, and with eight communities an interaction term would be fitting noise. It remains a hypothesis, and a cheap one to settle: the 2027 paper could be set with its statement length recorded, and the Basque reading collapse means that number now carries more weight than it did.</p>
</section>
<section id="what-pisa-2025-says-about-pau-2027" class="level3">
<h3 class="anchored" data-anchor-id="what-pisa-2025-says-about-pau-2027">What PISA 2025 says about PAU 2027</h3>
<p>PISA 2025 was published on 8 September 2026, eleven days before this chapter was written, and science was its major domain. It is the cohort that sits the PAU in 2027, so for the first time in this study a genuinely forward-looking measurement exists, and it is worth asking what estimate it supports.</p>
<p>The measurement itself is severe. Basque science falls to <strong>458.5</strong>, against a Spanish <strong>477.1</strong> and an OECD <strong>481.9</strong>. The gap to Spain, which was <span class="math inline">\(+9.2\)</span> in 2012 and <span class="math inline">\(-5.0\)</span> in 2022, is now <span class="math inline">\(-18.6\)</span> — the largest in the series and more than double the previous worst. At the top of the distribution the Basque share at levels 5–6 <strong>halves, from 3.32 % to 1.83 %</strong>, against a Spanish figure that holds near 4.2 %. On the instrument that does not depend on Basque marking, the cohort now sitting in 1º Bachillerato is the weakest this series has recorded.</p>
<div id="fig-2027" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2027-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig23_pau2027.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2027-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: <strong>a</strong> — the Euskadi Física series with two scenarios for 2027. The error bar on each is the paper-and-marking term alone, not a confidence interval on a prediction. <strong>b</strong> — the size of each contribution to the 2027 mark, on the same scale.
</figcaption>
</figure>
</div>
<p>Converting that into a PAU estimate is arithmetic, and the arithmetic is what makes the answer honest. The Basque PISA fall of 21.0 points is <span class="math inline">\(0.233\)</span> of a student standard deviation; transferred one-for-one to the PAU — the relation <a href="#do-the-two-instruments-fall-at-the-same-rate">figure 22</a> could neither reject nor establish — and prorated over the two years separating the PAU 2025 and PAU 2027 cohorts, it is a <strong>cohort term of <span class="math inline">\(-0.36\)</span> marks</strong>.</p>
<p>Set that against what else moves the number. The standard deviation of Euskadi’s own year-to-year change in the Física mean, excluding 2026, is <strong>0.855 marks</strong>; over two years the 95 % band on that alone is <strong><span class="math inline">\(\pm 2.37\)</span></strong>. The cohort term is <strong>6.5 times smaller than the band it has to be read against</strong>. And 2026 itself moved the mean by <span class="math inline">\(-1.48\)</span> in a single year on a changed paper — four times the cohort term, and more than the whole decade of PISA drift converted the same way (<span class="math inline">\(1.23\)</span> marks from 2012 to 2025).</p>
<p>So the estimate exists and is this:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>If the 2027 paper resembles</th>
<th>Central estimate</th>
<th>95 % band from the paper term alone</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>the 2025 paper</td>
<td><strong>5.11</strong></td>
<td><span class="math inline">\([2.74,\ 7.48]\)</span></td>
</tr>
<tr class="even">
<td>the 2026 paper</td>
<td><strong>3.63</strong></td>
<td><span class="math inline">\([1.26,\ 6.00]\)</span></td>
</tr>
</tbody>
</table>
<p>The two scenarios differ by 1.48 marks, which is the size of the 2026 event; the cohort contributes 0.36 to both. That is the finding, and it is not the one the question was hoping for. <strong>PAU 2027 is not something PISA predicts. It is something the 2027 paper and its marking scheme decide</strong>, with the cohort supplying a slow downward nudge an order of magnitude smaller than the choice. A forecast whose interval spans 2.7 to 7.5 is not a forecast; it is a restatement that the exam is the dominant variable.</p>
<p>Two things follow that are worth acting on rather than reading. The cohort term, small as it is, points the same way as every other measure in this section, so the sensible default for 2027 is that the intake will be slightly weaker than 2025’s and considerably weaker than the decade’s average — which argues for the paper being set with that in mind rather than against a remembered cohort. And the honest use of PISA 2025 here is not prediction but <em>attribution after the fact</em>: when the 2027 result arrives, the <span class="math inline">\(-0.36\)</span> is the part that should not be blamed on the paper, and everything beyond it is the part that should be explained.</p>
<p>That round has since been published, and <a href="#what-pisa-2025-says-about-pau-2027">the section below</a> reads it.</p>
<p><strong>H5 — “Students under-prepare Física because the weighting rules make it dispensable.”</strong> <em>Plausible as a slow driver, not as a 2026 trigger.</em> This is the Canarian coordinators’ hypothesis for their own decline (few degrees need a high Física mark; Matemáticas II carries the weighting; Física is examined last on a long day). It fits the ten-year erosion of the top decile better than a one-year fall of 1.5 points, and it is the hypothesis most directly addressable by the Basque ponderación table and the exam timetable for 2027.</p>
<p><strong>H6 — “Language or network bias.”</strong> <em>No evidence either way for Física.</em> The 2010–2022 series shows euskera/castellano differences of a few tenths in both directions and no sign that either network fails Física differentially; EHU’s 2026 bias analysis was run for Euskara II. Nothing published for Física 2026 speaks to this.</p>
<p>The ranking that emerges is H2 first, H3 unresolved and testable, H5 as background, H1 as a description of 2025 only, and H4 and H6 unsupported.</p>
</section>
</section>
<section id="was-2026-a-shift-or-a-change-of-shape" class="level2">
<h2 class="anchored" data-anchor-id="was-2026-a-shift-or-a-change-of-shape">Was 2026 a shift or a change of shape?</h2>
<p>The hypotheses above divide along a line the published aggregates can be made to test. A harder paper or a uniformly stricter marking scheme moves the whole distribution down together. A change in who sits the exam, or a marking change that bites only at the bottom, changes its <em>shape</em> — it thins the pass region without touching the top, or the reverse. The published data carry three summaries of the same distribution — the mean, the pass rate, and the share in the 8–10 band — and the second and third are near-deterministic functions of the first: across seventeen communities and eleven years the correlations are <span class="math inline">\(r = 0.974\)</span> and <span class="math inline">\(r = 0.961\)</span>. A scatter of pass rate against mean therefore mostly redraws arithmetic. What carries information is the <em>residual</em>: a cohort sitting off the common locus has a differently shaped distribution, not merely a lower one.</p>
<div id="fig-locus" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-locus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig16_shape_locus.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-locus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: <strong>a, b</strong> — Pass rate and the 8–10 band share against the mean Física mark, ordinary sitting, specific phase, seventeen communities 2015–2025 (n = 187 region-years, Ministry EPAU). The solid line is a quadratic fit; the pale band is ±2 residual standard deviations (1.9 pp left, 2.7 pp right) and the darker band the 95 % confidence interval of the fit itself, which widens where the region-years thin out. The dashed line is the same locus refitted with the 2020–2024 plateau removed: it departs from the solid one in the middle and upper range, where the plateau years sit, and converges on it at the low end, so the 2026 readings do not depend on the plateau. Hollow grey markers are 2015–16, the years in which Física could still be sat in the general phase; from 2017 LOMCE left it in the voluntary phase only and the presented cohort grew from 37,661 to 49,010 (pooled across phases). The Euskadi trajectory is drawn as a connected path. ULL and ULPGC 2026 are observed histograms, on a denominator of exams sat rather than presented. The EHU 2026 marker is hollow because its band share is a Beta fitted to the published mean, pass rate and zero count, so on these axes it can only restate them. The tinted strip marks the part of the mean axis where only two of the 187 region-years lie, and where all three 2026 cohorts sit. <strong>c</strong> — the ratio of b to a, <span class="math inline">\(P(x \ge 8 \mid x \ge 5)\)</span>: the share of those who passed who reached the top band. Because it is conditional on passing it carries far less of the level than either component, tracking the mean at <span class="math inline">\(r = 0.905\)</span> against <span class="math inline">\(0.974\)</span> and <span class="math inline">\(0.961\)</span>, and it is therefore the column that can separate a distribution that moved from one that was reshaped. <strong>d, e, f</strong> — the distribution of each column’s own vertical variable, with a normal of the same mean and standard deviation drawn for comparison and the 2026 values marked as vertical rules. These are deliberately not the distribution of the mean, which is the same variable on all three horizontal axes. <strong>g, h, i</strong> — the same three distributions with the 2020–2024 plateau removed, drawn over the full sample in pale grey; the dashed curve is the normal fitted to all years and the solid one the normal fitted without the plateau. Panels d–i share one vertical scale, which is why the bars in g–i are lower: 85 of the 187 region-years have been removed, and a density normalisation would have hidden that.
</figcaption>
</figure>
</div>
<p>Two things follow, and the first is a precondition for the second.</p>
<p><strong>The locus is a property of the marking scale, not of the cohort.</strong> Física’s examined population changed substantially inside this window: until 2016 it could be taken in the general phase, from 2017 LOMCE left it voluntary only, and the number presented grew by 30 % — from 37,661 to 49,010, pooled across phases. If the mapping from mean to pass rate depended on who sits the paper, it should step at that boundary. It does not: comparing residuals before and after 2017, the pass panel gives <span class="math inline">\(p = 0.40\)</span> and the top-band panel <span class="math inline">\(p = 0.12\)</span> once the two COVID sittings are excluded. On the full series the top-band difference does reach <span class="math inline">\(p = 0.008\)</span>, but that result is carried by 2020, whose residual of <span class="math inline">\(+3.6\)</span> pp is the largest in the panel, and it is the COVID year — so the honest reading is the conservative one. In <a href="#fig-locus" class="quarto-xref">Figure&nbsp;6</a> the hollow 2015–16 markers interleave with the later ones along the same curve. That stability is what licenses reading a 2026 point off the locus at all.</p>
<p><strong>Where 2026 can be observed, it is a location shift — but the test is weaker than it looks.</strong> The only 2026 cohorts with a published histogram are the two Canarian universities, and both land on the locus: ULL at <span class="math inline">\(-0.08\)</span> SD on the pass panel and <span class="math inline">\(+0.65\)</span> SD on the top band, ULPGC at <span class="math inline">\(-1.04\)</span> and <span class="math inline">\(+0.24\)</span>, against a historical scatter that reaches <span class="math inline">\(\pm 3.5\)</span> SD. Their distributions are the same shape as everyone else’s at that mean — simply further down it. Nothing was thinned selectively: the top of the Canarian cohort fell with the rest.</p>
<p>How much that settles depends on how much evidence sits where these cohorts fall, and the answer is honestly very little. The 187 region-year means pile up between 5.0 and 6.5 — they are themselves right-skewed and heavy-tailed rather than normal (skew <span class="math inline">\(+0.60\)</span>, excess kurtosis <span class="math inline">\(+0.88\)</span>; Shapiro–Wilk <span class="math inline">\(p = 0.00017\)</span>, Anderson–Darling <span class="math inline">\(A^2 = 2.06\)</span> against a 5 % critical value of <span class="math inline">\(0.77\)</span>). Only <strong>2 of 187</strong> sit below 4.5 — the tinted strip in panels a and b of <a href="#fig-locus" class="quarto-xref">Figure&nbsp;6</a> — and none within <span class="math inline">\(\pm 0.25\)</span> of where ULL (4.08) and the Basque cohort (3.99) fall. The curve there is therefore an extrapolation from the body of the data, and its own 95 % interval is <span class="math inline">\(\pm 1.41\)</span> pp at mean 4.08 against <span class="math inline">\(\pm 0.32\)</span> pp at mean 6.0, which is why the figure draws that interval as well as the flat scatter band. ULL’s residual of <span class="math inline">\(-0.16\)</span> pp sits comfortably inside the uncertainty of the very curve it is measured against.</p>
<p>The columns are also not equally well-behaved, and panels d, e and f of <a href="#fig-locus" class="quarto-xref">Figure&nbsp;6</a> separate them because they give different answers. The pass rate is symmetric and close to normal (skew <span class="math inline">\(+0.01\)</span>, excess kurtosis <span class="math inline">\(+0.39\)</span>; Shapiro–Wilk <span class="math inline">\(p = 0.096\)</span>, Anderson–Darling <span class="math inline">\(A^2 = 0.58\)</span>, below the critical value — normality cannot be rejected). The 8–10 share is not (skew <span class="math inline">\(+1.29\)</span>, <span class="math inline">\(A^2 = 5.80\)</span>), and neither is the conditional ratio (skew <span class="math inline">\(+0.98\)</span>, <span class="math inline">\(A^2 = 3.90\)</span>). Right-skew is what one should expect of a tail quantity pressed against zero, but it has a practical consequence: a residual quoted “in standard deviations” assumes roughly symmetric scatter, so the SD units are trustworthy on the pass panel and only indicative on the other two. Those residuals should be read as directional, not as calibrated probabilities.</p>
<p>The third column settles the question the first two could not. A uniform shift of the whole distribution moves the pass rate and the 8–10 share together, so a cohort sitting on both loci is consistent with a shift but does not demonstrate one — the two measurements are not independent tests. The conditional ratio is the quantity that distinguishes them, and on it the two observed 2026 cohorts sit <em>above</em> the locus, not below: ULL at <span class="math inline">\(+1.05\)</span> SD and ULPGC at <span class="math inline">\(+0.53\)</span> SD. Among the students who passed in Canarias in 2026, the top band is if anything slightly better represented than their mean predicts. Whatever happened there did not thin the top of the cohort relative to its middle, which is the first measurement in this sequence to strengthen a conclusion rather than qualify it.</p>
<p>The consequence is a limit on power, not a reversal of sign. Nothing in the 2026 data indicates a change of shape, and a <em>large</em> one would still have shown: a cohort that had thinned only at the bottom would sit several points off the curve, far outside even the widened interval. But a modest reshaping at mean 4 could not be detected with two historical neighbours, so “consistent with a pure location shift” is the correct reading, and “demonstrated to be one” is not.</p>
<p>That bears on the ranking above in one direction and one only. It is evidence against <strong>H4</strong>: a cohort that had become differently composed would be expected to sit off the locus, and Canarias does not. It does not discriminate between <strong>H2</strong> and <strong>H3</strong>, because a harder paper and a uniformly severer marking scheme produce the same signature here — both move the distribution without reshaping it. What it weighs against is any mechanism acting <em>strongly</em> and selectively on one part of the range.</p>
<p>The Basque case cannot be put to this test with what is published. The 2026 band shares shown in <a href="../chapters/04-distributions.html">Chapter 4</a> are output of the Beta fitted to the mean, the pass rate and the zero count; plotting them here as evidence would be circular, which is why the EHU 2026 marker in <a href="#fig-locus" class="quarto-xref">Figure&nbsp;6</a> is drawn hollow. Its apparent residual of <span class="math inline">\(-0.05\)</span> SD on the top band is the model agreeing with itself and should not be read as a result. Resolving the Basque case the same way needs one thing: the observed 2026 grade histogram, which is item 2 of the data requests below.</p>
<p>One data caveat surfaced in building this. The Ministry’s own cube is internally inconsistent for two of the 187 region-years — Galicia 2015 and 2016 — where the published pass rate and the published <span class="math inline">\([0,5)\)</span> share disagree by 5.64 and 4.48 pp; these are the two years in which Física appeared in both phases, so the cells are carried on different bases. Every band row sums to 100.0 and the remaining 185 agree to rounding, so the two points are kept rather than discarded, and they are recorded in <code>data/analysis/shape_locus.json</code>.</p>
</section>
<section id="what-you-compare-against-decides-what-you-find" class="level2">
<h2 class="anchored" data-anchor-id="what-you-compare-against-decides-what-you-find">What you compare against decides what you find</h2>
<p>Every number in this report is a change measured from some reference point, and the reference point is almost never argued for. It is usually the previous year, because that is what the sources publish and what the press quotes. Reading the same series against a different baseline does not merely adjust the size of the effect — in this case it reverses the sign of the national story.</p>
<div id="fig-frames" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig17_reference_frames.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: <strong>a</strong> — mean Física mark, ordinary sitting, for the nine communities that have published a 2026 result (the same nine in every year, so nothing here depends on which regions reported) and for Euskadi separately, against their own 2015–2019 baselines. The shaded years are the COVID-era plateau. Dotted segments carry 2026, which is not in the ministry cube and is assembled in this study. <strong>b</strong> — the same underlying data measured five ways, with the conclusion each measurement invites.
</figcaption>
</figure>
</div>
<p>The pattern in panel a of <a href="#fig-frames" class="quarto-xref">Figure&nbsp;7</a> is not a decline. It is a plateau that ended. The nine communities sit +0.4 to +1.0 above their pre-COVID baseline in every year from 2020 to 2024, peaking in 2021, and then return to it in 2025. The relaxation did not decay gradually, which is what “returning to normal” would look like; it held for three full years after the peak — 2022, 2023 and 2024 are all about +0.65 — and then ended in a single step. Whatever produced the COVID-era marking regime was still producing it in 2024, and stopped in 2025.</p>
<p>It was also not a uniform lift. The conditional measure of <a href="#fig-locus" class="quarto-xref">Figure&nbsp;6</a> makes that precise: among students who passed, the share reaching the 8–10 band ran <span class="math inline">\(0.353\)</span> across 2015–2019, rose to <span class="math inline">\(0.466\)</span> through the plateau (<span class="math inline">\(t = 7.14\)</span>, <span class="math inline">\(p = 4 \times 10^{-11}\)</span>), and came back to <span class="math inline">\(0.331\)</span> in 2025, statistically indistinguishable from the pre-COVID years (<span class="math inline">\(p = 0.30\)</span>). A regime that simply moved every mark up by two-thirds of a point would have left that ratio roughly where it was; instead it enriched the top band among passers by about a third. The COVID-era leniency was concentrated at the top of the scale, and the evidence that it was a change of <em>shape</em> is far stronger (<span class="math inline">\(p = 4 \times 10^{-11}\)</span>) than anything this chapter can say about 2026. Panel i of <a href="#fig-locus" class="quarto-xref">Figure&nbsp;6</a> shows the same thing from the other side: the conditional ratio’s departure from normality is largely an artefact of those five years, its Anderson–Darling statistic falling from <span class="math inline">\(3.90\)</span> to <span class="math inline">\(0.94\)</span> when they are removed, where the raw 8–10 share stays firmly non-normal at <span class="math inline">\(1.53\)</span> because its skew is intrinsic.</p>
<p>That is enough to change the reading of three separate claims in this report.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Measured as</th>
<th>Change</th>
<th>Invites the conclusion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024 → 2025, nine communities</td>
<td><span class="math inline">\(-0.65\)</span></td>
<td>“A national collapse; the competency model bites.”</td>
</tr>
<tr class="even">
<td>2025 → 2026, nine communities</td>
<td><span class="math inline">\(+0.17\)</span></td>
<td>“A recovery everywhere, so 2026 is a Basque problem.”</td>
</tr>
<tr class="odd">
<td>2015–19 baseline → 2026, nine communities</td>
<td><span class="math inline">\(+0.02\)</span></td>
<td>“Nothing has happened; Spain is where it was a decade ago.”</td>
</tr>
<tr class="even">
<td>2025 → 2026, Euskadi</td>
<td><span class="math inline">\(-1.48\)</span></td>
<td>“The Basque fall is one and a half points.”</td>
</tr>
<tr class="odd">
<td>2015–19 baseline → 2026, Euskadi</td>
<td><span class="math inline">\(-1.93\)</span></td>
<td>“The Basque fall is nearly two points — a third larger.”</td>
</tr>
</tbody>
</table>
<p>Rows one and three are the uncomfortable pair. Both are true of the same nine communities and the same ministry series, and they are not reconcilable as statements of fact about “what happened to Physics in Spain”: one says the subject collapsed, the other that it is exactly where it was in 2015–2019, <span class="math inline">\(+0.02\)</span> away after eleven years. The contradiction is entirely in the choice of reference year, and the year-on-year framing is the one that misleads, because 2024 was not a normal year to measure from.</p>
<p>This weakens <strong>H1</strong> further than <a href="#the-hypotheses-one-by-one">the hypothesis review above</a> already did. That section could say only that the competency model explains 2025 and not 2026. Measured from the pre-COVID baseline, it does not clearly explain 2025 either: the 2025 sitting did not fall below the historical norm, it returned to it. A model introduced in 2025 that leaves the national mean 0.15 below where it sat in 2015–2019 is not obviously doing anything at all to the national mean; the visible <span class="math inline">\(-0.81\)</span> is the withdrawal of five years of COVID-era leniency, and would have appeared in 2025 under any marking scheme that stopped being lenient.</p>
<p>It also makes the Basque case worse, not better. The headline everyone quoted is <span class="math inline">\(-1.48\)</span>, measured from 2025. Against Euskadi’s own pre-COVID baseline of 5.92 the 2026 fall is <span class="math inline">\(-1.93\)</span> — a third larger than the number in circulation — because 2025 was already 0.45 below that baseline. The Basque series did not fall once; it fell twice, and only the second fall was reported as news.</p>
<p>None of this is a criticism of the sources. The Ministry publishes years, the universities publish years, and a year-on-year change is the only comparison most readers can make from what is published. But it means the honest form of every claim in this report carries its reference point on its face, and that the three sentences most likely to be quoted from this study — “the 2025 fall was national”, “the 2026 fall is regional”, “Euskadi fell 1.48” — are each true only in the frame that produced them.</p>
</section>
<section id="how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one" class="level2">
<h2 class="anchored" data-anchor-id="how-this-reading-was-arrived-at-and-what-it-cost-each-earlier-one">How this reading was arrived at, and what it cost each earlier one</h2>
<p>The previous section shows that the frame decides the answer. This one records the order in which the frames were tried, because the sequence is itself a finding: the analysis in this chapter was not assembled in one pass, and four of its six steps damaged the conclusion that motivated them.</p>
<div id="fig-path" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig18_analysis_path.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: <strong>a</strong> — the two headline quantities under three successive framings, all computed on the same nine communities. The national number does not merely shrink as the frame widens; it changes sign. <strong>b</strong> — the order the questions were asked in, the claim each step produced, and what the later steps did to it. Every value is read from the JSON written by the script that computed it, so the figure cannot drift from the analysis it narrates.
</figcaption>
</figure>
</div>
<p>The sequence in panel b of <a href="#fig-path" class="quarto-xref">Figure&nbsp;8</a> ran as follows.</p>
<p><strong>Step 1</strong> was the July framing, taken from the institutions: Física fell 1.48 points and the competency model is to blame. <strong>Step 2</strong>, the cross-section of 2026 in <a href="../chapters/03-spain-2026.html">Chapter 3</a>, overturned it — six of nine communities rose in 2026 under the same model, and a national cause cannot produce opposite signs in the same year. That is the step that produced this chapter’s original hypothesis ranking.</p>
<p><strong>Step 3</strong> asked whether the 2026 fall was a change of shape or of position, and answered that Canarias 2026 sits on the historical locus: the distribution moved down without being reshaped. <strong>Step 4</strong> then asked how much evidence supports the locus where those cohorts fall, and found almost none — two region-years of 187 below mean 4.5, and a fit whose own interval there is four times its width at the centre of the data. The step-3 claim survived, but only as <em>consistent with</em> a location shift rather than a demonstration of one. <strong>Step 5</strong> decoupled the two distributions and found the 8–10 share strongly non-normal, so the standard-deviation units in which the step-3 residuals had been quoted are not calibrated on that panel, and those residuals are directional only.</p>
<p><strong>Step 6</strong> re-baselined to the pre-COVID norm and did the most damage of all — not to step 3, but to step 2. Step 2’s reasoning depends on 2025 having been a national collapse that the competency model could be blamed for. Measured from 2015–2019 the 2025 sitting was not a collapse: it was a return to the norm after a five-year plateau, and the nine communities finish 2026 <span class="math inline">\(+0.02\)</span> from where they started in 2015. So the hypothesis ranking earlier in this chapter, which demoted H1 to “a description of 2025”, now has to demote it further: there is no national 2025 anomaly for it to describe.</p>
<p><strong>Step 7</strong> conditioned on passing, and is the only step in the sequence that made a conclusion stronger rather than weaker. The pass rate and the 8–10 share are both dominated by the level, so a cohort lying on both loci was never two independent tests; their ratio is not, and on it the two observed 2026 cohorts sit <em>above</em> the locus. It also revised step 6 — the plateau did not merely lift the level, it reshaped the distribution, enriching the top band among passers from <span class="math inline">\(0.353\)</span> to <span class="math inline">\(0.466\)</span> (<span class="math inline">\(p = 4 \times 10^{-11}\)</span>) — and it found the Basque turn of 2024 described <a href="#a-basque-signal-that-arrives-a-year-early">above</a>, on a measure the other three were blind to.</p>
<p>That last point is the one with a bearing on how much of this sequence was luck. The conditional ratio was not part of the original design; it was suggested late, as an afterthought to a figure that already looked finished. Had it not been tried, the 2024 Basque signal would not have been found, and the plateau would still be described in this chapter as a lift rather than a reshaping. There is no reason to think the list of measures that were never tried is now empty.</p>
<p>Three further things follow that are worth stating plainly, because they bear on how this report should be read rather than on what it found.</p>
<p>The first is that every step which <em>narrowed</em> the claim came from asking about the data rather than about the subject — where the observations actually lie, whether the distributions are what the summary statistics assume, what the baseline year happens to be. None of the four weakening steps required new data. They required looking at the data that was already in hand from a different angle, and each angle was one an unhurried reader would eventually have asked about.</p>
<p>The second is that the two surviving strong claims are the narrow ones. That Euskadi 2026 is anomalous survives every reframing and gets <em>larger</em> under the honest baseline, from <span class="math inline">\(-1.48\)</span> to <span class="math inline">\(-1.93\)</span>. That the 2026 fall is confined to Física and Matemáticas II while Química and Biología held (<a href="../chapters/05-subjects-sittings.html">Chapter 5</a>) is untouched by any of this, because it is a within-cohort comparison and carries no baseline choice at all. Comparisons that do not need a reference point are the ones that did not move.</p>
<p>The third is the uncomfortable one. If this analysis had stopped at step 2 — which is where a competent and honest reading of the published sources naturally stops — it would have produced a coherent, quotable and partly wrong account: a national collapse in 2025 caused by the reform, and a separate Basque failure in 2026. Both halves of that sentence are artefacts of measuring from the previous year. Nothing in the published sources signals that the previous year was abnormal; the plateau is only visible once eleven years are put side by side on one axis, which no institutional publication does. That is not a failure of the sources, but it is a reason to treat any single-year comparison in this domain, including the ones in this report’s own earlier chapters, as provisional until it has been checked against a decade.</p>
</section>
<section id="the-institutional-record-since-6-july" class="level2">
<h2 class="anchored" data-anchor-id="the-institutional-record-since-6-july">The institutional record since 6 July</h2>
<ul>
<li><strong>6 July</strong>, EHU: Física figures published as a counter-example in the Euskara controversy; tribunal data handed to the Education Department; anomalous tribunal values reported for eleven subjects including Física <span class="citation" data-cites="ehu2026campusa argia2026ehu">(<a href="#ref-argia2026ehu" role="doc-biblioref">Argia, 2026</a>; <a href="#ref-ehu2026campusa" role="doc-biblioref">Euskal Herriko Unibertsitatea, 2026</a>)</span>.</li>
<li><strong>7 July</strong>, Science and Universities Counsellor: admits a “déficit de confianza, fundamentado o no fundamentado” in the marking system; floats multi-marker models; ≈ 40 judicial appeals by students with very low marks.</li>
<li><strong>7 July</strong>, extraordinary sitting: 71.4 % global pass (90.6 % in 2025); no Física figure.</li>
<li><strong>8–10 July</strong>: 12 000-signature faculty manifesto in support of markers; EHU appeals the court measures on the Euskara marks; press notes that “los ceros en Física duplican a los de Euskera”.</li>
<li><strong>12 July</strong>, Education Counsellor Pedrosa <span class="citation" data-cites="pedrosa2026entrevista">(<a href="#ref-pedrosa2026entrevista" role="doc-biblioref">Alonso, 2026</a>)</span>: the Department has only the EHU report, will request more data, will review all subjects for 2027 “a corto plazo”, has no diagnosis yet, and does not hold other communities’ data.</li>
<li><strong>30 July</strong>, Galicia (context): after errors in three papers, the Xunta announces peer review of papers and double marking for 2027 — the single-author, no-external-review failure mode that any Basque audit should check for.</li>
<li><strong>7 September</strong>: nothing sent to schools for PAU 2027 beyond the Euskara II instructions; “2027 será un año de ajuste técnico” and the competency model is to be fully deployed in 2028.</li>
</ul>
</section>
<section id="what-to-ask-for-in-order-of-value" class="level2">
<h2 class="anchored" data-anchor-id="what-to-ask-for-in-order-of-value">What to ask for, in order of value</h2>
<ol type="1">
<li><strong>Física by tribunal, 2025 and 2026</strong>: <span class="math inline">\(n_j\)</span>, <span class="math inline">\(\bar{x}_j\)</span>, <span class="math inline">\(s_j\)</span> and the school composition of each tribunal’s scripts. EHU computed this. It separates H2 from H3 in one table.</li>
<li><strong>The full Física grade histogram, 2024–2026</strong>, in one-point bands with zeros and tens, as ULL and ULPGC publish routinely. It replaces the model of <a href="../chapters/04-distributions.html">Chapter 4</a> with data.</li>
<li><strong>July 2026 Física</strong>: presented, passed, mean. Its position relative to the June result tells whether the July paper was pitched like the June one.</li>
<li><strong>Revision statistics for Física 2026</strong>: requests, share raised, mean change. Published for four subjects, not for the subject with the lowest mean.</li>
<li><strong>Física by sex, language and territory for 2023–2026</strong>, the breakdowns the annual reports carried until 2022.</li>
<li><strong>Problem-level marks</strong> (four problems, options a/b) for a sample of scripts: this is the item-level evidence that distinguishes “the paper was hard” from “the paper was unanswerable”, and it is what the Canarian subcommittee planned for 2026.</li>
</ol>
</section>
<section id="design-questions-for-2027-that-the-data-already-inform" class="level2">
<h2 class="anchored" data-anchor-id="design-questions-for-2027-that-the-data-already-inform">Design questions for 2027 that the data already inform</h2>
<ul>
<li><strong>Optionality.</strong> The 2026 Basque paper fixed problems 1 and 2 with no alternative (optional share 75 % → 50 %; Canarias, the other community that cut choice by ≥ 25 points, also fell — <a href="../chapters/11-exam-content.html">Chapter 11</a>). The COVID years (single super-option, choice among questions) produced the highest means in the series; the 2025–26 reduction of choice coincides with the two lowest. Restoring a choice within problems 1–2 is the cheapest lever with a documented effect.</li>
<li><strong>Calibration against a reference.</strong> The Ministry cube gives, for every subject, community and year, a full distribution; a target distribution for Física (for example the 2017–2024 Basque band structure, <span class="math inline">\([0,5)\)</span> ≈ 30 %, <span class="math inline">\([9,10]\)</span> ≈ 15 %) can be written into the coordination instructions and checked against a pre-test of the paper on a sample of Bachillerato students, as some communities’ ponencias already do informally.</li>
<li><strong>The threshold.</strong> The Canarian histograms show that in 2026 the customary rounding of borderline scripts to 5 vanished. Whether that is desirable is a policy question; that it moves the pass rate by 5–8 points is an empirical one.</li>
<li><strong>Order of exams.</strong> Física is sat on the last slot of the science day in several communities; the Tenerife minutes name this explicitly. The Basque timetable is a free parameter.</li>
<li><strong>Second marking.</strong> Galicia’s 2027 reform (double marking, external review of papers) is the model that the “déficit de confianza” language of July points toward; Veas &amp; López-Pina’s Rasch equating in Comunitat Valenciana is the statistical complement.</li>
</ul>
<p>None of these requires new data to be argued; all of them would be sharpened by the six items above.</p>



</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-pedrosa2026entrevista" class="csl-entry" role="listitem">
Alonso, I. (2026). <em>Bego<span>ñ</span>a pedrosa: <span>“Analizaremos los factores que han podido influir”</span> (interview with the basque education counsellor)</em>. Noticias de Gipuzkoa, 12 July 2026. <a href="https://www.noticiasdegipuzkoa.eus/sociedad/2026/07/12/analizaremos-factores-han-podido-influir-11316893.html">https://www.noticiasdegipuzkoa.eus/sociedad/2026/07/12/analizaremos-factores-han-podido-influir-11316893.html</a>
</div>
<div id="ref-argia2026ehu" class="csl-entry" role="listitem">
Argia. (2026). <em><span>EHUk</span> emandako datuek azaldu dute euskarako notak ez direla salbuespen izan</em>. Argia, 6–8 July 2026. <a href="https://www.argia.eus/albistea/ehuk-emandako-datuek-azaldu-dute-euskarako-notak-ez-direla-salbuespen-izan">https://www.argia.eus/albistea/ehuk-emandako-datuek-azaldu-dute-euskarako-notak-ez-direla-salbuespen-izan</a>
</div>
<div id="ref-ehu2026campusa" class="csl-entry" role="listitem">
Euskal Herriko Unibertsitatea. (2026). <em><span>EHU</span> concluye que la asignatura <span class="nocase">Euskara y Literatura II</span> no presenta un comportamiento excepcional cuando se analizan de forma global los resultados de la <span>PAU</span></em>. Campusa, 6 July 2026. <a href="https://www.ehu.eus/es/web/campusa/-/ehu-concluye-que-la-asignatura-euskara-y-literatura-ii-no-presenta-un-comportamiento-excepcional-cuando-se-analizan-de-forma-global-los-resultados-de-la-pau">https://www.ehu.eus/es/web/campusa/-/ehu-concluye-que-la-asignatura-euskara-y-literatura-ii-no-presenta-un-comportamiento-excepcional-cuando-se-analizan-de-forma-global-los-resultados-de-la-pau</a>
</div>
<div id="ref-sancheztarazaga2026pau" class="csl-entry" role="listitem">
Sánchez-Tarazaga, L., &amp; Gimeno Rovira, J. A. (2026). <em><span></span>C<span>ó</span>mo compatibilizar un bachillerato que busca habilidades cr<span>í</span>ticas con una <span>PAU</span> que todav<span>í</span>a prima la memorizaci<span>ó</span>n?</em> The Conversation (Espa<span>ñ</span>a), 2 June 2026. <a href="https://doi.org/10.64628/AAO.atrdhyeha">https://doi.org/10.64628/AAO.atrdhyeha</a>
</div>
<div id="ref-veas2025consistency" class="csl-entry" role="listitem">
Veas, A., &amp; López-Pina, J.-A. (2025). Consistency analysis of assessment boards in university entrance examinations in <span>Spain</span>. <em>European Journal of Investigation in Health, Psychology and Education</em>, <em>15</em>(6), 102. <a href="https://doi.org/10.3390/ejihpe15060102">https://doi.org/10.3390/ejihpe15060102</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/05-subjects-sittings.html" class="pagination-link" aria-label="Subjects &amp; participation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Subjects &amp; participation</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/11-exam-content.html" class="pagination-link" aria-label="The papers themselves">
        <span class="nav-page-text">The papers themselves</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Independent analysis prepared 18 September 2026 · all figures reproducible from <code>scripts/</code></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Data: EHU, SIIU/EPAU, Generalitat de Catalunya, GVA, Junta de Andalucía, CM, Uniovi, UCLM, ULL, ULPGC, UNIZAR, UPNA, UMU, UC, CiUG, UR</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>