<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Josu M. Igartua">
<meta name="dcterms.date" content="2026-09-20">
<meta name="description" content="A self-contained briefing for the head of admissions and the Física coordination: the established facts with their evidence class, a decomposition of the decay into separable components, the three quarters of it that no published data can yet attribute, the data requests that would separate them, and the design levers for 2027 ordered by the strength of the evidence behind them.">

<title>Briefing for the Admissions Office – PAU Física 2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/14-briefing-es.html" rel="next">
<link href="../chapters/15-synthesis-es.html" rel="prev">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5b4e4ad6cda8ee308e5de16fe7059631.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-55ab141dd447a5db25f9b02bc13364cd.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5b4e4ad6cda8ee308e5de16fe7059631.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4f56ef24fd7e0b60995d53dadae59254.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-d7169c38db111d135d171b3357e2edd5.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-4f56ef24fd7e0b60995d53dadae59254.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css?family=Inter:400,400i,500,600,700%7CJetBrains+Mono:400,700&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/favicon.svg" alt="PAU Física 2026" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">PAU Física</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/02-euskadi.html"> 
<span class="menu-text">The Euskadi break</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/03-spain-2026.html"> 
<span class="menu-text">Spain 2026</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../chapters/08-sources.html"> 
<span class="menu-text">Sources &amp; methods</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/15-synthesis.html">Briefing</a></li><li class="breadcrumb-item"><a href="../chapters/14-briefing.html">For the Admissions Office</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><i class="bi bi-house" role="img">
</i> 
 <span class="menu-text">Findings</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Evidence and results</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-euskadi.html" class="sidebar-item-text sidebar-link"><i class="bi bi-bar-chart-line" role="img">
</i> 
 <span class="menu-text">Euskadi 2010–2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-spain-2026.html" class="sidebar-item-text sidebar-link"><i class="bi bi-globe-europe-africa" role="img">
</i> 
 <span class="menu-text">Spain 2026</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-distributions.html" class="sidebar-item-text sidebar-link"><i class="bi bi-graph-up" role="img">
</i> 
 <span class="menu-text">Shape of the collapse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-subjects-sittings.html" class="sidebar-item-text sidebar-link"><i class="bi bi-people" role="img">
</i> 
 <span class="menu-text">Subjects &amp; participation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-interpretation.html" class="sidebar-item-text sidebar-link"><i class="bi bi-compass" role="img">
</i> 
 <span class="menu-text">Interpretation &amp; 2027</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">The papers</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-exam-content.html" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-text" role="img">
</i> 
 <span class="menu-text">The papers themselves</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-ehu-paper-history.html" class="sidebar-item-text sidebar-link"><i class="bi bi-clock-history" role="img">
</i> 
 <span class="menu-text">Sixteen years of one paper</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-paradigm.html" class="sidebar-item-text sidebar-link"><i class="bi bi-diagram-3" role="img">
</i> 
 <span class="menu-text">The paradigm change, whole</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Research context</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-data-hunt.html" class="sidebar-item-text sidebar-link"><i class="bi bi-search" role="img">
</i> 
 <span class="menu-text">The data hunt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-literature.html" class="sidebar-item-text sidebar-link"><i class="bi bi-journal-text" role="img">
</i> 
 <span class="menu-text">Literature &amp; regulation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Paper</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-paper.html" class="sidebar-item-text sidebar-link"><i class="bi bi-file-earmark-text" role="img">
</i> 
 <span class="menu-text">Decomposition and identification</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Briefing</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-synthesis.html" class="sidebar-item-text sidebar-link"><i class="bi bi-clipboard-check" role="img">
</i> 
 <span class="menu-text">Synthesis for the coordination</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-synthesis-es.html" class="sidebar-item-text sidebar-link"><i class="bi bi-translate" role="img">
</i> 
 <span class="menu-text">Síntesis (castellano)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-briefing.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-envelope-paper" role="img">
</i> 
 <span class="menu-text">For the Admissions Office</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-briefing-es.html" class="sidebar-item-text sidebar-link"><i class="bi bi-translate" role="img">
</i> 
 <span class="menu-text">Informe (castellano)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Sources and reproducibility</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-sources.html" class="sidebar-item-text sidebar-link"><i class="bi bi-archive" role="img">
</i> 
 <span class="menu-text">Sources</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-log.html" class="sidebar-item-text sidebar-link"><i class="bi bi-list-check" role="img">
</i> 
 <span class="menu-text">Work log</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-reproduce.html" class="sidebar-item-text sidebar-link"><i class="bi bi-code-slash" role="img">
</i> 
 <span class="menu-text">Reproduce the study</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-audit.html" class="sidebar-item-text sidebar-link"><i class="bi bi-shield-check" role="img">
</i> 
 <span class="menu-text">Audit</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-result" id="toc-the-result" class="nav-link active" data-scroll-target="#the-result">The result</a></li>
  <li><a href="#what-happened-elsewhere-in-spain" id="toc-what-happened-elsewhere-in-spain" class="nav-link" data-scroll-target="#what-happened-elsewhere-in-spain">What happened elsewhere in Spain</a></li>
  <li><a href="#what-the-fall-is-made-of" id="toc-what-the-fall-is-made-of" class="nav-link" data-scroll-target="#what-the-fall-is-made-of">What the fall is made of</a>
  <ul class="collapse">
  <li><a href="#three-events-not-one" id="toc-three-events-not-one" class="nav-link" data-scroll-target="#three-events-not-one">Three events, not one</a></li>
  <li><a href="#the-mark-budget" id="toc-the-mark-budget" class="nav-link" data-scroll-target="#the-mark-budget">The mark budget</a></li>
  <li><a href="#which-frame-and-does-it-matter" id="toc-which-frame-and-does-it-matter" class="nav-link" data-scroll-target="#which-frame-and-does-it-matter">Which frame, and does it matter</a></li>
  <li><a href="#is-the-1.65-físicas-or-euskadis" id="toc-is-the-1.65-físicas-or-euskadis" class="nav-link" data-scroll-target="#is-the-1.65-físicas-or-euskadis">Is the 1.65 Física’s, or Euskadi’s?</a></li>
  <li><a href="#what-can-be-subtracted-and-what-cannot" id="toc-what-can-be-subtracted-and-what-cannot" class="nav-link" data-scroll-target="#what-can-be-subtracted-and-what-cannot">What can be subtracted, and what cannot</a></li>
  <li><a href="#marking-severity-the-timing-fits-and-one-version-of-it-survives" id="toc-marking-severity-the-timing-fits-and-one-version-of-it-survives" class="nav-link" data-scroll-target="#marking-severity-the-timing-fits-and-one-version-of-it-survives">Marking severity: the timing fits, and one version of it survives</a></li>
  </ul></li>
  <li><a href="#the-shape-of-the-collapse" id="toc-the-shape-of-the-collapse" class="nav-link" data-scroll-target="#the-shape-of-the-collapse">The shape of the collapse</a></li>
  <li><a href="#inside-the-basque-system" id="toc-inside-the-basque-system" class="nav-link" data-scroll-target="#inside-the-basque-system">Inside the Basque system</a></li>
  <li><a href="#the-papers" id="toc-the-papers" class="nav-link" data-scroll-target="#the-papers">The papers</a></li>
  <li><a href="#the-hypotheses-with-verdicts" id="toc-the-hypotheses-with-verdicts" class="nav-link" data-scroll-target="#the-hypotheses-with-verdicts">The hypotheses, with verdicts</a></li>
  <li><a href="#pisa-2025-and-the-2027-estimate" id="toc-pisa-2025-and-the-2027-estimate" class="nav-link" data-scroll-target="#pisa-2025-and-the-2027-estimate">PISA 2025 and the 2027 estimate</a>
  <ul class="collapse">
  <li><a href="#can-a-rate-of-decay-be-projected" id="toc-can-a-rate-of-decay-be-projected" class="nav-link" data-scroll-target="#can-a-rate-of-decay-be-projected">Can a rate of decay be projected?</a></li>
  </ul></li>
  <li><a href="#what-the-evidence-does-not-establish" id="toc-what-the-evidence-does-not-establish" class="nav-link" data-scroll-target="#what-the-evidence-does-not-establish">What the evidence does not establish</a></li>
  <li><a href="#data-to-request-and-what-each-would-separate" id="toc-data-to-request-and-what-each-would-separate" class="nav-link" data-scroll-target="#data-to-request-and-what-each-would-separate">Data to request, and what each would separate</a></li>
  <li><a href="#design-levers-for-2027-ordered-by-evidence-and-cost" id="toc-design-levers-for-2027-ordered-by-evidence-and-cost" class="nav-link" data-scroll-target="#design-levers-for-2027-ordered-by-evidence-and-cost">Design levers for 2027, ordered by evidence and cost</a></li>
  <li><a href="#sources-and-reproducibility" id="toc-sources-and-reproducibility" class="nav-link" data-scroll-target="#sources-and-reproducibility">Sources and reproducibility</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="14-briefing.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/15-synthesis.html">Briefing</a></li><li class="breadcrumb-item"><a href="../chapters/14-briefing.html">For the Admissions Office</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Briefing for the Admissions Office</h1>
<p class="subtitle lead">PAU Física 2026 at UPV/EHU: what the fall is made of, what can and cannot be separated, and what that implies for the 2027 paper</p>
  <div class="quarto-categories">
    <div class="quarto-category">briefing</div>
    <div class="quarto-category">2027</div>
  </div>
  </div>

<div>
  <div class="description">
    A self-contained briefing for the head of admissions and the Física coordination: the established facts with their evidence class, a decomposition of the decay into separable components, the three quarters of it that no published data can yet attribute, the data requests that would separate them, and the design levers for 2027 ordered by the strength of the evidence behind them.
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Josu M. Igartua </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Física coordinator, PAU · UPV/EHU — from the dossier <em>Physics in the PAU, 2026</em>, audited 19 and 20 September 2026
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">20 September 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">21 September 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="The short version">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The short version
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Basque Física mean fell to <strong>3.99</strong> in June 2026. Of that fall, the part that is Euskadi’s own — measured against the nine communities that have published a 2026 result — is <strong>1.65 points</strong>, all of it in one year. Two components of it can be quantified, each as a difference from the field: the choice removed from the paper beyond what other communities removed (about <span class="math inline">\(-0.20\)</span>) and the Basque cohort’s decline in excess of Spain’s, as measured outside the Basque system (about <span class="math inline">\(-0.12\)</span>). <strong>The remaining four fifths cannot be attributed to anything with the data that has been published</strong>, because paper content, reading load, marking severity and newly examined topics leave the same trace in a mean. Separating them needs marks at the level of the sub-task and the tribunal, which EHU holds and has not released. And a year earlier, in 2024, the Basque distribution had already changed shape — the top band fell six points further than the level implied while the pass rate rose 2.3 points where the level predicted a fall of 2.8 — the second-most-negative single-year move of the 170 in the national panel, on the last paper of the old format.</p>
<p>Three further things this round established. <strong>More than half of what separates Euskadi from the field is not Física’s</strong>: on the balanced subject panel, Euskadi’s Física sits <span class="math inline">\(2.28\)</span> marks below what the four comparators’ Física did, and that gap divides into <span class="math inline">\(-1.18\)</span> which moved all of Euskadi’s quantitative subjects together — Matemáticas II fell 1.67 — and <span class="math inline">\(-1.10\)</span> which is Física’s alone. <strong>A general marking severity cannot be the main cause</strong>, because Lengua Castellana rose <span class="math inline">\(+0.03\)</span> and Biología <span class="math inline">\(+0.15\)</span> under the same tribunals; a severity confined to the numerical deductions fits the pattern, and one tally of the marking sheets would settle it. <strong>No rate of cohort decay can be projected</strong>: the PISA per-cohort-year change runs from <span class="math inline">\(+3.7\)</span> to <span class="math inline">\(-7.5\)</span>, so it is a sequence of steps and not a slope, and the cohort is worth about a fifth of a mark a year against a paper worth 0.85.</p>
<p>If the 2027 paper resembles the 2026 one, the central estimate is <strong>3.81</strong>. If it resembles the 2025 one, <strong>5.11</strong>. The cohort accounts for a third of a mark of the difference; the paper accounts for the rest.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="How to read this document">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to read this document
</div>
</div>
<div class="callout-body-container callout-body">
<p>Every statement carries one of four evidence classes: <strong>official</strong> (published by a university, a government or the Ministry, archived here with its hash), <strong>press</strong> (reported by the media, not verifiable at an official source), <strong>modelled</strong> (computed in the dossier from published aggregates, labelled as such), or <strong>testimony</strong> (the coordinator’s account of decisions that were never published). Nothing here is a causal estimate: these are cohort statistics of different papers marked by different tribunals, and the paper changes every year. Bracketed chapter numbers refer to the dossier’s chapters, which are listed in its sidebar.</p>
<p><strong>This version.</strong> 21 September 2026. The dossier was opened on 18 September and has been revised on every working day since: 19 September added the paper audits and the first external audit, 20 September the marking-regime and statement work with a second audit, and 21 September the coordination’s own remarks — the rebuilt figure 1, the three-way split of the competency verdict, and the COVID sittings. Every revision, with what it changed and why, is in the <a href="../chapters/09-log.html">work log</a> and in <a href="../chapters/13-audit.html">the record of remarks</a>.</p>
</div>
</div>
<section id="the-result" class="level2">
<h2 class="anchored" data-anchor-id="the-result">The result</h2>
<p>In the ordinary sitting of June 2026, 2 066 candidates sat Física at UPV/EHU. The mean was <strong>3.99</strong> and the pass rate <strong>39.8 %</strong>; <strong>24.5 %</strong> of the scripts scored two points or less (10 % in 2025) and <strong>3.2 %</strong> scored zero. The 2025 figures were 5.47 and 62.3 % on 2 189 candidates (official: the EHU deck of 6 July and the Ministry EPAU cube). EHU has not published the pass <em>count</em> (the rate implies 822–823), the July 2026 Física result, the tribunal-level Física table, the revision statistics for Física, nor any split by sex, language or territory — all of which it published for other subjects or in earlier years.</p>
<div id="fig-b-series" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig01_euskadi_series.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Física in the Basque university-entrance exam, ordinary sitting, 2010–2026. <strong>The ribbon carries two separate facts on the same axis</strong>: the <em>law</em> under which the exam was set, and the <em>paper model</em> actually used. They do not coincide — LOMCE governed from 2017 but the paper did not change until 2020, and it changed then for COVID and not for the law — which is why they are two rows and not one band; the marked interval under them spans those two years. <code>L1</code> and <code>L2</code> are the two LOMLOE papers, keyed beneath. <strong>COVID is two sittings and one model</strong>: the darker tint is 2020 and 2021, both set under the relief measures — 2021 is the highest mean in the series, 7.69 — and the lighter one the four-of-eight paper they forced, which was then kept through 2024. <strong>The grey line is the Ministry cube</strong> for all seventeen communities and stops at 2025, because the 2026 cube is not published until June 2027. <strong>The green marks</strong> are this study’s own cross-section of the nine communities that have published a 2026 result — a different population, and drawn detached for that reason. <strong>The two arrows on the right are changes, not levels</strong>, and both leave the same point, Euskadi’s own 2025 mean of 5.47. The <strong>blue</strong> arrow is Euskadi’s own change to 3.99, <span class="math inline">\(-1.48\)</span>. The <strong>green</strong> arrow is the change of the nine-community field, <span class="math inline">\(+0.17\)</span>, drawn from that same origin so that its head at 5.64 reads as <em>where Física would have ended had it moved with the field</em>. The bracket between the two heads is therefore the Basque-specific component, <span class="math inline">\(-1.65\)</span>, exactly. The distance between the two 2026 <strong>levels</strong> is 1.87 and is <em>not</em> that component, because the two series did not start level in 2025 (5.47 against 5.69). The field is the mean of the nine <strong>including</strong> Euskadi, which is the conservative reading; against the eight others alone the component would be <span class="math inline">\(-1.86\)</span>. The three values are the <code>total</code>, <code>common</code> and <code>basque_specific</code> terms of <code>data/analysis/decomposition.json</code>, computed by <code>scripts/21_decay_decomposition.py</code>. The Basque series is spliced from the EHU annual reports (2010–2022, all phases), the Ministry cube (2023–2025) and the EHU deck (2026); the three agree to ±0.02 where they overlap.
</figcaption>
</figure>
</div>
<p>Three facts about the level [Ch. 2]:</p>
<ul>
<li><strong>3.99 is the lowest value of the whole series</strong>, below the 2010–11 start of the two-phase PAU (4.45, 4.44). From 2012 to 2024 the exam produced means between 5.45 and 6.49 in every year but the COVID peak of 2021; a flat trend fitted to those twelve years leaves 2025 at <span class="math inline">\(-0.69\)</span> and 2026 at <span class="math inline">\(-2.18\)</span>, which is seven residual standard deviations.</li>
<li><strong>It is the second consecutive fall</strong>: <span class="math inline">\(6.09 \to 5.47 \to 3.99\)</span>. Against Euskadi’s own pre-COVID norm the 2026 sitting is <span class="math inline">\(-1.93\)</span> on the Ministry’s specific-phase series, <span class="math inline">\(-1.91\)</span> pooled and <span class="math inline">\(-1.92\)</span> on EHU’s own published series — a third larger than the <span class="math inline">\(-1.48\)</span> in circulation, because 2025 was already 0.45 below that norm. (Three conventions, three numbers within two hundredths; this briefing uses the pooled one wherever communities are compared.)</li>
<li><strong>A single-year change of <span class="math inline">\(-1.48\)</span> is rare but not unprecedented.</strong> Across the 170 year-to-year changes in the Ministry panel (17 communities × 10 transitions, SD 0.74) exactly seven were as negative: Extremadura 2024 (<span class="math inline">\(-2.10\)</span>), Cantabria 2017 (<span class="math inline">\(-1.94\)</span>), Canarias 2019 (<span class="math inline">\(-1.76\)</span>), Baleares 2025 (<span class="math inline">\(-1.65\)</span>), Euskadi 2022 (<span class="math inline">\(-1.62\)</span>, the post-COVID normalisation), Asturias 2025 (<span class="math inline">\(-1.55\)</span>) and Cantabria 2025 (<span class="math inline">\(-1.51\)</span>). What is exceptional is the <em>level</em>, and the two falls in a row.</li>
</ul>
</section>
<section id="what-happened-elsewhere-in-spain" class="level2">
<h2 class="anchored" data-anchor-id="what-happened-elsewhere-in-spain">What happened elsewhere in Spain</h2>
<p>In 2025, the first year of the LOMLOE competency exam, the Física mean fell in <strong>14 of 17</strong> communities by <span class="math inline">\(-0.81\)</span> on average; Euskadi’s <span class="math inline">\(-0.62\)</span> was <em>milder</em> than the national move. In 2026, nine communities have a published result:</p>
<div id="tbl-b-regions" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[22,10,10,10,48]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-regions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The nine 2026 results found. Official unless marked press; the 2025 comparator is the Ministry’s except for Cataluña, which is compared with itself on the aptes basis. The cross-section is unweighted: Madrid and Extremadura count equally [Ch. 3].
</figcaption>
<div aria-describedby="tbl-b-regions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Community</th>
<th style="text-align: right;">2025</th>
<th style="text-align: right;">2026</th>
<th style="text-align: right;">Δ</th>
<th>Basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Asturias</td>
<td style="text-align: right;">5.49</td>
<td style="text-align: right;">6.62</td>
<td style="text-align: right;"><span class="math inline">\(+1.13\)</span></td>
<td>presented, 76.9 % pass — <strong>press</strong> (Uniovi release, not archived)</td>
</tr>
<tr class="even">
<td>Madrid</td>
<td style="text-align: right;">5.65</td>
<td style="text-align: right;">6.70</td>
<td style="text-align: right;"><span class="math inline">\(+1.05\)</span></td>
<td>chart labels, one decimal</td>
</tr>
<tr class="odd">
<td>Castilla-La Mancha</td>
<td style="text-align: right;">5.86</td>
<td style="text-align: right;">6.80</td>
<td style="text-align: right;"><span class="math inline">\(+0.94\)</span></td>
<td>presented, n = 1 781</td>
</tr>
<tr class="even">
<td>Cataluña</td>
<td style="text-align: right;">6.04</td>
<td style="text-align: right;">6.84</td>
<td style="text-align: right;"><span class="math inline">\(+0.80\)</span></td>
<td>eligible students (“aptes”) both years, n = 8 021</td>
</tr>
<tr class="odd">
<td>Comunitat Valenciana</td>
<td style="text-align: right;">5.89</td>
<td style="text-align: right;">6.40</td>
<td style="text-align: right;"><span class="math inline">\(+0.51\)</span></td>
<td>presented, n = 5 259</td>
</tr>
<tr class="even">
<td>Andalucía</td>
<td style="text-align: right;">5.69</td>
<td style="text-align: right;">5.86</td>
<td style="text-align: right;"><span class="math inline">\(+0.17\)</span></td>
<td>presented</td>
</tr>
<tr class="odd">
<td>Extremadura</td>
<td style="text-align: right;">6.09</td>
<td style="text-align: right;">5.27</td>
<td style="text-align: right;"><span class="math inline">\(-0.82\)</span></td>
<td><strong>press</strong></td>
</tr>
<tr class="even">
<td>Canarias (ULL + ULPGC)</td>
<td style="text-align: right;">5.08</td>
<td style="text-align: right;">4.25</td>
<td style="text-align: right;"><span class="math inline">\(-0.83\)</span></td>
<td>presented, n = 1 395</td>
</tr>
<tr class="odd">
<td>País Vasco</td>
<td style="text-align: right;">5.47</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: right;"><span class="math inline">\(-1.48\)</span></td>
<td>presented, n = 2 066</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-b-regions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b-regions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig03_regions_2026_vs_2025.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b-regions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: 2025 → 2026 by community: open circle 2025, filled 2026; red fell, green rose. Cataluña is on its aptes basis in both years, Madrid’s values are chart labels rounded to one decimal, Extremadura’s 2026 value is press-reported.
</figcaption>
</figure>
</div>
<p>Six communities rose under the same national model in the same year; three fell. A national cause cannot produce opposite signs in the same year, so <strong>the competency model can at most describe 2025; it does not explain 2026</strong>. The eight remaining communities have published nothing; the Ministry’s 2026 cube is due in June 2027.</p>
<p>There is a second reason not to read 2025 as a national collapse. Measured against each community’s own 2015–2019 norm, <strong>2020–2024 was a plateau, not a decline</strong>: the nine communities sat <span class="math inline">\(+0.50\)</span> to <span class="math inline">\(+1.05\)</span> above their pre-COVID norm in every one of those years and returned to it in 2025 in a single step. The plateau is in every subject in the Ministry cube, and in 2025 every science subject came back to within about a fifth of a point of its norm while the humanities kept part of the lift. So the reform arrived in the same year as the end of a subject-general regime, and nothing in the PAU series separates the two. Against those norms the nine communities finish 2026 at <span class="math inline">\(+0.02\)</span> on average — but that average hides 2.9 points of spread, from Madrid at <span class="math inline">\(+1.02\)</span> to País Vasco at <span class="math inline">\(-1.91\)</span>.</p>
</section>
<section id="what-the-fall-is-made-of" class="level2">
<h2 class="anchored" data-anchor-id="what-the-fall-is-made-of">What the fall is made of</h2>
<p>This is the part of the briefing that bears on 2027, and it is new: it asks not how large the fall was but how many distinct things happened and which of them can be told apart.</p>
<div id="fig-b-decomp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b-decomp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig25_decomposition.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b-decomp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: <strong>a</strong> — every year-to-year transition in the national panel, placed by how much the mean moved and by how far the top band moved away from what that change of mean alone predicts. Euskadi’s are violet; 2024 and 2025 are ringed. <strong>b</strong> — those two Basque years, observed against the prediction, for both published band quantities. <strong>c</strong> — the 2025 → 2026 fall split into the part common to the nine reporting communities, the two Basque-specific parts that can be quantified, and the part that cannot.
</figcaption>
</figure>
</div>
<section id="three-events-not-one" class="level3">
<h3 class="anchored" data-anchor-id="three-events-not-one">Three events, not one</h3>
<p>A distribution can move in two ways: <strong>location</strong> (everything slides together, and the pass rate and the top band move exactly as the mean implies) or <strong>shape</strong> (they do not). The published aggregates can tell them apart, and the three recent Basque years are not the same kind of event.</p>
<div id="tbl-b-steps" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[16,11,12,14,11,11,11,14]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-steps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: The Basque steps against the locus fitted on all 187 region-years [Ch. 6].
</figcaption>
<div aria-describedby="tbl-b-steps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Δ mean</th>
<th style="text-align: right;">Δ top band</th>
<th style="text-align: right;">what the level predicts</th>
<th style="text-align: right;">excess</th>
<th style="text-align: right;">Δ pass %</th>
<th style="text-align: right;">predicted</th>
<th style="text-align: right;">excess</th>
<th>Reads as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2023 → 2024</td>
<td style="text-align: right;"><span class="math inline">\(-0.21\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-9.0\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-3.1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{-5.9}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(+2.3\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-2.8\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{+5.0}\)</span></td>
<td><strong>shape</strong></td>
</tr>
<tr class="even">
<td>2024 → 2025</td>
<td style="text-align: right;"><span class="math inline">\(-0.62\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-8.2\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-8.1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-10.7\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-8.9\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-1.8\)</span></td>
<td><strong>location</strong></td>
</tr>
<tr class="odd">
<td>2025 → 2026</td>
<td style="text-align: right;"><span class="math inline">\(-1.48\)</span></td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td>not published</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>2024 changed the shape and barely touched the level.</strong> The mean moved 0.21 in a series whose year-to-year standard deviation is 0.85 — nothing. But the top band fell nine points where the level predicts three, and the pass rate <em>rose</em> two where the level predicts a fall of three. The distribution compressed: fewer at the top, more just over the line. As a move of the conditional top-band residual it is the <strong>second-most-negative of the 170 transitions</strong> in the national panel, and the largest negative move outside the LOMLOE year (two positive moves are larger in absolute size). It happened on the last paper of the old format, with the old choice rule and the old theory questions.</p>
<p><strong>2025 changed the level and not the shape</strong>, and most of that change was the country’s, not Euskadi’s.</p>
<p><strong>2026 cannot be classified</strong>, because EHU has not published the distribution. The two 2026 cohorts in Spain that do publish one — the two Canarian universities, at almost exactly the Basque level — are pure location shifts.</p>
<p>One consequence is worth spelling out, because it is easy to miss and it governs how the rest of the dossier should be read. A distribution can lose candidates from its top and gain them just above the pass line at the same time, and the two movements cancel in the mean. That is precisely what 2024 did: the 8–10 share fell 9.0 points while the pass rate <em>rose</em> 2.3, and what came out was a change in the mean of 0.21 — a twentieth of what the two band moves were worth separately. So every test in this dossier that works on the mean — the reference frames, the plateau comparison, Euskadi’s rank among the communities — reports Euskadi at or near its own norm in 2024. Those tests are not wrong. They are answering a question about the average candidate, and the average candidate was where he had always been. The candidates who disappeared were at the top, and a mean cannot see them leave when others arrive from below. That is why this dossier reads the bands as well as the mean, and it is why the first thing that moved in the Basque exam moved in 2024, a year before the first LOMLOE paper.</p>
</section>
<section id="the-mark-budget" class="level3">
<h3 class="anchored" data-anchor-id="the-mark-budget">The mark budget</h3>
<p>Of the 1.48 points lost between 2025 and 2026, how much is Euskadi’s own? Comparing with the nine communities that have a 2026 result — the same nine in every year, so the comparison population never changes:</p>
<div id="tbl-b-budget" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[16,22,20,22,20]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: The Basque change split into the country’s move and Euskadi’s own, pooled phase [Ch. 6].
</figcaption>
<div aria-describedby="tbl-b-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Euskadi mean</th>
<th style="text-align: right;">Δ total</th>
<th style="text-align: right;">Common to the nine</th>
<th style="text-align: right;">Basque-specific</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2024</td>
<td style="text-align: right;">6.09</td>
<td style="text-align: right;"><span class="math inline">\(-0.21\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.03\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.18\)</span></td>
</tr>
<tr class="even">
<td>2025</td>
<td style="text-align: right;">5.47</td>
<td style="text-align: right;"><span class="math inline">\(-0.62\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.65\)</span></td>
<td style="text-align: right;"><span class="math inline">\(+0.03\)</span></td>
</tr>
<tr class="odd">
<td>2026</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: right;"><span class="math inline">\(-1.48\)</span></td>
<td style="text-align: right;"><span class="math inline">\(+0.17\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{-1.65}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In 2025 Euskadi moved with the field to within three hundredths of a point: <strong>the whole of that year’s fall was national</strong>. In 2026 the field rose <span class="math inline">\(+0.17\)</span> and Euskadi fell <span class="math inline">\(-1.48\)</span>, so the Basque-specific component is <strong><span class="math inline">\(-1.65\)</span></strong>.</p>
<p>That is the number to explain — not 1.48, which mixes a national recovery into a Basque fall, and not 1.93, which is the same thing measured from a different year.</p>
</section>
<section id="which-frame-and-does-it-matter" class="level3">
<h3 class="anchored" data-anchor-id="which-frame-and-does-it-matter">Which frame, and does it matter</h3>
<p>Why measure a Basque fall against a Spanish field at all, when the question is what happened in Euskadi? Three frames give three numbers:</p>
<div id="tbl-b-frames" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[28,50,22]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: The same result, three frames [Ch. 6].
</figcaption>
<div aria-describedby="tbl-b-frames-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 50%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Frame</th>
<th>What it asks</th>
<th style="text-align: right;">2026</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Year on year</td>
<td>how far did the Basque mean fall from 2025?</td>
<td style="text-align: right;"><span class="math inline">\(-1.48\)</span></td>
</tr>
<tr class="even">
<td>Against Euskadi’s own pre-COVID norm</td>
<td>how far is 2026 from where Euskadi normally sits?</td>
<td style="text-align: right;"><span class="math inline">\(-1.91\)</span></td>
</tr>
<tr class="odd">
<td>Against the nine-community field</td>
<td>how much is Euskadi’s own, once the country’s move is out?</td>
<td style="text-align: right;"><span class="math inline">\(-1.65\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>They span 0.43 of a mark. Nothing in this briefing turns on the choice, and every design implication below is the same under all three.</p>
<p>What the field buys is not size but <strong>separation</strong>, for one purpose no absolute number can serve: telling a year in which everyone fell from a year in which only Euskadi did. Read absolutely, Euskadi lost 0.62 marks in 2025 and that looks like a Basque problem. Read against the field, which lost 0.65 in the same sitting, there is nothing Basque in 2025 at all, and the whole of the anomaly is in 2026. Without the field the two years look like one slide of 2.10 marks; with it, they are one national event followed by one Basque event, and only the second is this office’s to answer.</p>
<p>What the field is <strong>not</strong> is a control group, and the arithmetic should not be allowed to imply otherwise. These nine sat nine different papers, marked to nine different criteria, by nine different sets of correctors. Euskadi is the only community that moved all four reform axes in the direction the orientations ask for (optionality 75 % → 50 %, competency marks 25 % → 62.5 %, substantive context <span class="math inline">\(+50\)</span>, contextualised marks <span class="math inline">\(+75\)</span>); Castilla-La Mancha is the only other that both cut choice and raised competency content, and it cut contextualised marks by 45 points while doing so; Cataluña moved the competency share the other way; three communities moved on no axis but the contextualised share; and Asturias, which rose <span class="math inline">\(+1.13\)</span>, sits outside the structural optionality band altogether at 100 % [Ch. 11]. Across the nine, the further a paper moved toward the competency model the further its mean fell (<span class="math inline">\(r = -0.70\)</span>, <span class="math inline">\(p = 0.035\)</span>) — but Euskadi is the extreme point on both axes and dropping it leaves <span class="math inline">\(r = -0.40\)</span>, <span class="math inline">\(p = 0.33\)</span>, so that is one community making the point rather than eight agreeing.</p>
<p>The practical consequence is a range. Against all eight other communities the Basque-specific component is <span class="math inline">\(-1.65\)</span>; against the six whose papers barely moved, <span class="math inline">\(-1.95\)</span>; against nothing at all, <span class="math inline">\(-1.48\)</span>. It is somewhere in <span class="math inline">\([-1.95, -1.48]\)</span>, and it cannot be narrowed because nobody has calibrated these nine papers against each other. That is data request 9.</p>
</section>
<section id="is-the-1.65-físicas-or-euskadis" class="level3">
<h3 class="anchored" data-anchor-id="is-the-1.65-físicas-or-euskadis">Is the 1.65 Física’s, or Euskadi’s?</h3>
<p>The budget is computed on Física alone, so it cannot distinguish two situations that call for different responses: something that happened to the <em>Física paper</em>, or something that happened to <em>Euskadi</em> — its cohort, its tribunals, its marking — and landed on Física along with everything else.</p>
<p>The subject results separate them without any modelling. EHU published eight subjects; four comparator communities published three of the same ones, giving a balanced five-by-three panel on which the Basque Física change splits into four terms that sum exactly to <span class="math inline">\(-1.48\)</span>.</p>
<div id="tbl-b-subj" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-subj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: The balanced panel behind the split [Ch. 6].
</figcaption>
<div aria-describedby="tbl-b-subj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Community</th>
<th style="text-align: right;">Física</th>
<th style="text-align: right;">Matemáticas II</th>
<th style="text-align: right;">Química</th>
<th style="text-align: right;">Mean of the three</th>
<th style="text-align: right;">Física − own mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>País Vasco</td>
<td style="text-align: right;">-1.48</td>
<td style="text-align: right;">-1.67</td>
<td style="text-align: right;">-0.21</td>
<td style="text-align: right;">-1.12</td>
<td style="text-align: right;">-0.36</td>
</tr>
<tr class="even">
<td>Cataluña</td>
<td style="text-align: right;">+0.80</td>
<td style="text-align: right;">-1.94</td>
<td style="text-align: right;">-0.34</td>
<td style="text-align: right;">-0.49</td>
<td style="text-align: right;">+1.29</td>
</tr>
<tr class="odd">
<td>Madrid</td>
<td style="text-align: right;">+1.10</td>
<td style="text-align: right;">+0.50</td>
<td style="text-align: right;">-0.30</td>
<td style="text-align: right;">+0.43</td>
<td style="text-align: right;">+0.67</td>
</tr>
<tr class="even">
<td>Andalucía</td>
<td style="text-align: right;">+0.17</td>
<td style="text-align: right;">-0.59</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">-0.21</td>
<td style="text-align: right;">+0.38</td>
</tr>
<tr class="odd">
<td>Asturias</td>
<td style="text-align: right;">+1.13</td>
<td style="text-align: right;">+0.10</td>
<td style="text-align: right;">+0.28</td>
<td style="text-align: right;">+0.50</td>
<td style="text-align: right;">+0.63</td>
</tr>
<tr class="even">
<td><strong>Field (four communities)</strong></td>
<td style="text-align: right;">+0.80</td>
<td style="text-align: right;">-0.48</td>
<td style="text-align: right;">-0.15</td>
<td style="text-align: right;">+0.06</td>
<td style="text-align: right;">+0.74</td>
</tr>
</tbody>
</table>
<p>Change in the subject mean, 2025 to 2026, in marks out of ten. The last two columns are the terms of the additive split: a community’s mean over the three subjects, and how far its Física sits from that mean.</p>
</div>
</figure>
</div>
<div id="tbl-b-split" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[24,12,64]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: The exact split of the <span class="math inline">\(-1.48\)</span> [Ch. 6].
</figcaption>
<div aria-describedby="tbl-b-split-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 12%">
<col style="width: 64%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th style="text-align: right;">Marks</th>
<th>What it is</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Field core</td>
<td style="text-align: right;"><span class="math inline">\(+0.06\)</span></td>
<td>what the three shared subjects did in the four comparators</td>
</tr>
<tr class="even">
<td>Field Física premium</td>
<td style="text-align: right;"><span class="math inline">\(+0.74\)</span></td>
<td>Física above its own community’s mean in all four; the mean of <span class="math inline">\(+0.38\)</span> to <span class="math inline">\(+1.29\)</span></td>
</tr>
<tr class="odd">
<td><strong>Euskadi-common</strong></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{-1.18}\)</span></td>
<td>what moved all of Euskadi’s quantitative subjects together</td>
</tr>
<tr class="even">
<td><strong>Física-specific</strong></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{-1.10}\)</span></td>
<td>what is left for the Física paper</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Add the two Euskadi terms and Euskadi’s Física sits <strong>2.28 marks below what these four comparators’ Física did</strong> — the four-community analogue of the <span class="math inline">\(-1.65\)</span>, larger because these four are among the communities that rose most, and no more a control than the nine are. What the split adds is the proportion: <strong>slightly more than half of that gap, 1.18 of 2.28, is not Física’s.</strong> In the same sitting, at the same university, under the same marking specification, Matemáticas II lost 1.67 marks — more than Física — while Química (<span class="math inline">\(-0.21\)</span>), Biología (<span class="math inline">\(+0.15\)</span>) and Lengua Castellana (<span class="math inline">\(+0.03\)</span>) did not follow.</p>
<p>That changes what the 2027 Física paper can be expected to fix. Rewriting it addresses the <span class="math inline">\(-1.10\)</span>. It does not touch the <span class="math inline">\(-1.18\)</span>, which is invisible to anything decided inside one subject’s <em>ponencia</em>, and which the Matemáticas II coordination is presumably looking at from its own side without either group seeing the shared term. <strong>The first operational consequence of this briefing is therefore that Física and Matemáticas II should be looked at together, and that is a decision for this office rather than for either ponencia.</strong></p>
<p>One caution: the comparator set is four communities and three subjects because that is all that was published by mid-September, and each of those communities changed its own papers too. A symmetric analysis of variance over all five leaves the Física-specific residual at <span class="math inline">\(-0.88\)</span> rather than <span class="math inline">\(-1.10\)</span>; the conclusion — that the Euskadi-wide term is of the same order as the Física-specific one — holds either way.</p>
</section>
<section id="what-can-be-subtracted-and-what-cannot" class="level3">
<h3 class="anchored" data-anchor-id="what-can-be-subtracted-and-what-cannot">What can be subtracted, and what cannot</h3>
<div id="tbl-b-components" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[27,10,14,22,27]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Components of the Basque-specific 2026 change [Ch. 6].
</figcaption>
<div aria-describedby="tbl-b-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 22%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th style="text-align: right;">Marks</th>
<th>Range</th>
<th>Status</th>
<th>What would identify it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Common to the country</td>
<td style="text-align: right;"><span class="math inline">\(+0.17\)</span></td>
<td>—</td>
<td>observed</td>
<td>already separated</td>
</tr>
<tr class="even">
<td>Choice removed, net of the field’s own cuts</td>
<td style="text-align: right;"><span class="math inline">\(-0.20\)</span></td>
<td><span class="math inline">\(-0.10\)</span> to <span class="math inline">\(-0.27\)</span></td>
<td>quantified (modelled)</td>
<td>option take-up and per-option means</td>
</tr>
<tr class="odd">
<td>Cohort: Basque PISA decline in excess of Spain’s</td>
<td style="text-align: right;"><span class="math inline">\(-0.12\)</span></td>
<td><span class="math inline">\(\pm 0.11\)</span> (sampling error only)</td>
<td>quantified (modelled)</td>
<td>nothing inside the PAU; it is an outside measure</td>
</tr>
<tr class="even">
<td>Paper content and reading load</td>
<td style="text-align: right;">—</td>
<td>—</td>
<td><strong>not identified</strong> (the two are one signal, <span class="math inline">\(r = +0.79\)</span>); the <em>cause</em> of the length is now measured, and it is the itemisation, not the competency items</td>
<td>sub-task marks</td>
</tr>
<tr class="odd">
<td>Marking severity (penalties, voided sections)</td>
<td style="text-align: right;">—</td>
<td>bounded: <span class="math inline">\(0.65\)</span> to <span class="math inline">\(0.96\)</span> of the Física-specific <span class="math inline">\(-1.10\)</span></td>
<td><strong>sufficient, not identified</strong></td>
<td>the penalty ledger crossed with each script’s mark, and the 2026 band table</td>
</tr>
<tr class="even">
<td>Tribunal severity and spread</td>
<td style="text-align: right;">—</td>
<td>—</td>
<td><strong>not identified</strong></td>
<td>Física by tribunal</td>
</tr>
<tr class="odd">
<td>Newly examined topics</td>
<td style="text-align: right;">—</td>
<td>—</td>
<td><strong>not identified</strong> (bounded: optional in June)</td>
<td>option take-up</td>
</tr>
<tr class="even">
<td>Who sat the exam</td>
<td style="text-align: right;">—</td>
<td>—</td>
<td><strong>not identified</strong> (bounded small)</td>
<td>enrolment and the 2025-26 school marks</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Two rows changed again in the seventh round, and one of them changed for a reason that is not about marking at all. The <strong>reading-load</strong> row is unchanged in what it claims — the paper really is 39 per cent longer to read, and length really does track the fall across the nine communities — but its <em>cause</em> is no longer what this briefing said. Splitting both papers’ statements into narrative, demand text and printed prices shows the contextual narrative at 71 words a printed statement in 2025 and <strong>70 in 2026</strong>, while the demand text more than doubled from 88 to 181 and the printed prices went from nothing to 17. The 2026 criteria itemise each apartado into sub-items of 0.25, and a paper marked that way must print each quantum’s demand and each quantum’s price. The length is the price of that decision (<a href="../chapters/16-paradigm.html">Ch. 16</a>). It matters here because the two causes are differently actionable: the competency requirement is imposed, the itemisation is local. The <strong>marking</strong> row tightens: only 14 to 19 of a script’s 27 to 32 sub-items can attract a unit, prefix or rounding error, so the fitted intensity restated in countable currency is 0.67 penalties on every numerical answer of every script; and the linguistic channel, which this briefing twice called an unmodelled understatement, is capped by the criteria at 1.00 and fitted at 0.04.</p>
<p>The marking row changed status in the fifth and sixth rounds and is worth reading in full rather than from the table. What changed in 2026 was not markers becoming harsher on the same scale but a change of <strong>regime</strong>: a defect that until 2025 cost the part of the sub-task depending on it now costs that part <em>and</em> <span class="math inline">\(-0.10\)</span>, uncapped, and a grave error voids the whole apartado. Put the published 2025 distribution through that regime and the four published 2026 figures come out together, on about twelve deductions per script (<a href="../chapters/06-interpretation.html#penalty-regime">Ch. 6</a>). But that model gives every candidate the same twelve, and when the penalties are allowed to fall unevenly — which is what anybody would expect — the regime is worth <strong>less</strong>, because a deduction removes a full <span class="math inline">\(0.10\)</span> only where <span class="math inline">\(0.10\)</span> is left and the zero floor absorbs the rest of any penalty aimed at weak work. Flat and equal is therefore the <em>most expensive</em> way to spend a fixed number of penalties, over every reading in which the weaker candidates collect more than their share. At twelve deductions the regime carries <span class="math inline">\(0.96\)</span> marks read flat and <span class="math inline">\(0.89\)</span> to <span class="math inline">\(0.65\)</span> read as a distribution: 87 % down to 59 % of the Física-specific <span class="math inline">\(-1.10\)</span> (<a href="../chapters/06-interpretation.html#penalty-shape">Ch. 6</a>). <strong>So this row is a ceiling and a floor rather than an estimate</strong>, and the difference between them — a fifth to nearly half a mark — stays with the rows above and below it. One unpublished table, the 2026 grade bands, would close the interval: refitted to everything that <em>is</em> published, the readings differ on the share at nine or above from 0.3 % to 6.1 %.</p>
<p>Two components can be quantified, and both have to be expressed as differences <em>from the field</em>, because the quantity they are subtracted from is one. <strong>Choice</strong>: removing the option from two of the four exercises is worth <span class="math inline">\(-0.26\)</span> by simulating both Basque formats on the same population and items; the other eight communities cut optionality by 6.25 points on average, and whatever that cost is already inside the <span class="math inline">\(+0.17\)</span>, so the part that belongs here is about <strong><span class="math inline">\(-0.20\)</span></strong>. <strong>Cohort</strong>: the Basque PISA decline in excess of Spain’s — 13.6 of the 21.0 points — is worth about <strong><span class="math inline">\(-0.12\)</span></strong> for one PAU year. Together <strong><span class="math inline">\(-0.31\)</span></strong>, under a fifth of the Basque-specific fall. Both are modelled magnitudes under stated assumptions, not measurements: their quoted ranges are sensitivities to one assumption each, and the cohort’s <span class="math inline">\(\pm 0.11\)</span> covers PISA’s sampling error and nothing else.</p>
<p>The other <strong><span class="math inline">\(-1.33\)</span> — four fifths — is not attributed to anything</strong>, and the reason is structural rather than a gap in the work: paper content, reading load, marking severity and syllabus exposure all leave the same trace in a mean. Length and competency content are one signal measured twice (<span class="math inline">\(r = +0.79\)</span> across eight communities), and the cross-community relation between length and grade change, taken literally, would assign 2.3 marks to the Basque paper’s 45 % lengthening — more than the entire Basque-specific fall, which is itself the reason not to take it literally.</p>
<p><strong>Four fifths of what happened is therefore a bundle, not a mystery.</strong> It has four named candidates, each with a different remedy, and one dataset — marks at the level of the sub-task — would go a long way towards separating them, though not perfectly: a section voided by a grave error and a sub-task nobody could start both appear as a zero on the same sub-task.</p>
</section>
<section id="marking-severity-the-timing-fits-and-one-version-of-it-survives" class="level3">
<h3 class="anchored" data-anchor-id="marking-severity-the-timing-fits-and-one-version-of-it-survives">Marking severity: the timing fits, and one version of it survives</h3>
<p>2026 was the second year in which the linguistic component — 0.2 of a point for grammar, spelling and presentation — and the seven minor-error deductions of the marking specification were in force, and the first in which correctors had already applied them once. The seven are <span class="math inline">\(-0.10\)</span> each and are written for numerical work: units, a vector arrow missing from a vector, a vector arrow on a scalar, intermediate rounding beyond 5 %, a wrong SI prefix, a factor of ten, a transcription error.</p>
<p>The hypothesis that a rule applied cautiously in year one is applied in full in year two predicts little in 2025 and a step in 2026. <strong>That is exactly the shape of the mark budget</strong>: the Basque-specific component is <span class="math inline">\(+0.03\)</span> in 2025 and <span class="math inline">\(-1.65\)</span> in 2026. The timing fits, and that should be on the record.</p>
<p>The eight-subject table then separates two versions of it, because they predict different things.</p>
<div id="tbl-b-severity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-severity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: The 2026 Basque subject changes grouped by which marking rules can reach them [Ch. 6].
</figcaption>
<div aria-describedby="tbl-b-severity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 25%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Basque subject</th>
<th style="text-align: right;">Change 2025→2026</th>
<th>Family</th>
<th style="text-align: center;">Reached by the 0.2 linguistic component</th>
<th style="text-align: center;">Reached by the seven minor-error rules</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Física</td>
<td style="text-align: right;">-1.48</td>
<td>quantitative</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td>Matemáticas II</td>
<td style="text-align: right;">-1.67</td>
<td>quantitative</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="odd">
<td>Química</td>
<td style="text-align: right;">-0.21</td>
<td>quantitative</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">yes</td>
</tr>
<tr class="even">
<td>Historia de España</td>
<td style="text-align: right;">-0.83</td>
<td>verbal / other</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td>Euskara II</td>
<td style="text-align: right;">-0.48</td>
<td>verbal / other</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td>Hª Filosofía</td>
<td style="text-align: right;">-0.29</td>
<td>verbal / other</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td>Biología</td>
<td style="text-align: right;">+0.15</td>
<td>verbal / other</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="even">
<td>Lengua Castellana</td>
<td style="text-align: right;">+0.03</td>
<td>verbal / other</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">no</td>
</tr>
<tr class="odd">
<td><strong>Quantitative mean</strong></td>
<td style="text-align: right;"><strong>-1.12</strong></td>
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td><strong>Verbal mean</strong></td>
<td style="text-align: right;"><strong>-0.28</strong></td>
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td><strong>Gap</strong></td>
<td style="text-align: right;"><strong>-0.84</strong></td>
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Both families are examined in the same sitting at the same university, under the same marking specification and in the same second year of it — but by each subject’s own correctors and on each subject’s own candidates, so this is not a within-person comparison. A marking change written into the shared specification and applied across the board would move both columns together; the gap is what such a change cannot produce.</p>
</div>
</figure>
</div>
<p>A <strong>general</strong> severity effect — spelling, presentation, “this year we apply the criteria in full” — reaches every subject that asks a candidate to write, which all eight of these do, and should move all eight together. They did not: the spread is 1.82 marks, and of the three subjects where written language is most exposed two rose (Lengua Castellana <span class="math inline">\(+0.03\)</span>, Biología <span class="math inline">\(+0.15\)</span>) while Euskara II fell <span class="math inline">\(-0.48\)</span>. Whatever is common to all eight is at most the verbal mean of <span class="math inline">\(-0.28\)</span> — on the condition that the 2026 verbal papers were no easier than their predecessors, which is not known, since part of that <span class="math inline">\(-0.28\)</span> is the cohort and part each subject’s own paper. <strong>On that condition a general severity effect accounts for at most a fifth of Física’s 1.48, and probably much less.</strong></p>
<p>A <strong>quantitative-specific</strong> severity effect is a different proposition, and the pattern fits it: the deductions can only reach Física, Química and Matemáticas II, and those three fell 0.84 marks further than the other five. The fit is not strong evidence — Química fell only 0.21, so the effect would not be uniform over the subjects it can reach, and Física and Matemáticas II share long symbolic derivations and a 2026 format change as well as the deductions. Eight subjects in one year is a pattern with a prediction attached, not a test.</p>
<p><strong>The test is cheap and the data already exist.</strong> The linguistic component and the seven deductions are recorded separately when applied. A tally — how many scripts lost the 0.2, how many <span class="math inline">\(-0.10\)</span> penalties per script and of which type, in Física, Matemáticas II, Lengua Castellana and Euskara II, in 2025 and in 2026 — turns the hypothesis into two cross-tabulations. It collects nothing new and can be answered from inside the university. It is <strong>data request 3</strong>, and it is the only decisive item on that list obtainable in days rather than months.</p>
<p>One design consequence does not wait for the answer. The 2026 Basque paper raised the competency-coded share of its expected marks from 25 % to 62.5 %, the largest such move among the nine. Competency items ask for a calculation <em>and</em> an argument, so they are exposed to the linguistic component and the numerical deductions at once, where a bare calculation is exposed only to the second. If the deductions bite harder on that compound surface, the format change and the second year of full application are not two hypotheses but one — and nothing published can separate them, because both happened in Euskadi in June 2026 and in no other community.</p>
</section>
</section>
<section id="the-shape-of-the-collapse" class="level2">
<h2 class="anchored" data-anchor-id="the-shape-of-the-collapse">The shape of the collapse</h2>
<p>Euskadi publishes four summary numbers; the two Canarian universities publish full histograms and are the closest empirical picture of the same event [Ch. 4].</p>
<div id="tbl-b-canarias" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-canarias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: The Canarian histograms, from the ULL and ULPGC dashboards (official).
</figcaption>
<div aria-describedby="tbl-b-canarias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>University, June</th>
<th style="text-align: right;">Exams</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">% &lt; 2</th>
<th style="text-align: right;">% &lt; 5</th>
<th style="text-align: right;">% in [5, 6)</th>
<th style="text-align: right;">% ≥ 9</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ULL 2024</td>
<td style="text-align: right;">731</td>
<td style="text-align: right;">5.60</td>
<td style="text-align: right;">10.5</td>
<td style="text-align: right;">36.8</td>
<td style="text-align: right;">17.5</td>
<td style="text-align: right;">9.8</td>
</tr>
<tr class="even">
<td>ULL 2025</td>
<td style="text-align: right;">796</td>
<td style="text-align: right;">4.92</td>
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">46.6</td>
<td style="text-align: right;">16.2</td>
<td style="text-align: right;">8.9</td>
</tr>
<tr class="odd">
<td>ULL 2026</td>
<td style="text-align: right;">683</td>
<td style="text-align: right;">4.08</td>
<td style="text-align: right;">25.2</td>
<td style="text-align: right;">61.5</td>
<td style="text-align: right;">11.9</td>
<td style="text-align: right;">3.1</td>
</tr>
<tr class="even">
<td>ULPGC 2024</td>
<td style="text-align: right;">796</td>
<td style="text-align: right;">6.15</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: right;">32.0</td>
<td style="text-align: right;">12.6</td>
<td style="text-align: right;">16.1</td>
</tr>
<tr class="odd">
<td>ULPGC 2025</td>
<td style="text-align: right;">758</td>
<td style="text-align: right;">5.25</td>
<td style="text-align: right;">14.0</td>
<td style="text-align: right;">45.4</td>
<td style="text-align: right;">13.3</td>
<td style="text-align: right;">12.5</td>
</tr>
<tr class="even">
<td>ULPGC 2026</td>
<td style="text-align: right;">712</td>
<td style="text-align: right;">4.41</td>
<td style="text-align: right;">22.6</td>
<td style="text-align: right;">57.2</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">4.9</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ul>
<li><strong>Canarias 2026 is the Basque twin</strong>: ULL 4.08 / 38.5 % pass / 25.2 % below 2; ULPGC 4.41 / 42.8 % / 22.6 % — against Euskadi’s 3.99 / 39.8 % / 24.5 % at or below 2.</li>
<li><strong>Both moved along the locus.</strong> Across the 187 region-years the pass rate and the top-band share are near-deterministic functions of the mean (<span class="math inline">\(r = 0.974\)</span> and <span class="math inline">\(0.961\)</span>), and both Canarian cohorts sit on that relation; on the measure least dominated by the level they sit slightly above it. Nothing thinned the top relative to the middle. That is evidence against a compositional explanation, and it does not distinguish a harder paper from uniformly stricter marking.</li>
<li><strong>The pass-line bunching thinned at the ULL</strong> — scripts in <span class="math inline">\([5,6)\)</span> from 17.5 % (2024) to 11.9 % (2026), worth about 5.6 points of pass rate — and did not move at the ULPGC (12.6 → 12.8 %). Whether EHU rounds at the threshold at all is not published.</li>
<li><strong>For Euskadi the shape is modelled, not observed.</strong> A Beta fitted to the published mean, pass rate and zero count gives a 2026 density with a mode near 2.5 and a median of 3.8, 14.6 % of scripts at 7 or above (30 % in 2025) and 2.1 % at 9 or above (5.9 %). Three caveats, and the third was learned the hard way. The fit under-predicts the published pass rate by 4.7 points, so every tail share read off it is pessimistic by about that much. The continuous part is zero at the origin while 3.2 % of scripts did score exactly zero, which the model carries as a separate point mass. And <strong>that 2.1 % is a two-parameter curve’s extrapolation above a region where nothing was measured</strong>: it is what a smooth distribution implies, not what Euskadi observed, and the sixth round found this dossier quoting it elsewhere as though it were published. A model of the marking regime, fitted to the same four figures, puts 0.3 % there instead (<a href="../chapters/06-interpretation.html#penalty-shape">Ch. 6</a>). Two models can agree on everything published and disagree by a factor of eight on this — and across the seven readings of the marking regime the same band runs from 0.3 % to 6.1 %, a factor of twenty-three — which is why the band table is now a request in its own right and why no tail share above eight should be quoted from this fit without the word modelled attached. The observed fail share needs no model at all: it is <strong>60.2 %</strong>, the complement of the published pass rate, which is close to the ULL’s observed 61.5 %.</li>
</ul>
</section>
<section id="inside-the-basque-system" class="level2">
<h2 class="anchored" data-anchor-id="inside-the-basque-system">Inside the Basque system</h2>
<p><strong>Subjects.</strong> The damage is confined to the science-technical block [Ch. 5]. Euskadi 2025 → 2026: <strong>Física <span class="math inline">\(-1.48\)</span>, Matemáticas II <span class="math inline">\(-1.67\)</span></strong>, Historia <span class="math inline">\(-0.83\)</span>, Euskara II <span class="math inline">\(-0.48\)</span>, Hª Filosofía <span class="math inline">\(-0.29\)</span>, Química <span class="math inline">\(-0.21\)</span>, Biología <span class="math inline">\(+0.15\)</span>, Lengua Castellana <span class="math inline">\(+0.03\)</span>. Cataluña shows the mirror image with the same authority and cohort (Física <span class="math inline">\(+0.80\)</span>, Matemàtiques <span class="math inline">\(-1.94\)</span>); Madrid rose in both; Andalucía split. Against Euskadi’s own 2015–2019 norms, Matemáticas II, Química and Biología sat <span class="math inline">\(+0.1\)</span> to <span class="math inline">\(+1.6\)</span> above through 2021–2024 and at <span class="math inline">\(+0.27\)</span>, <span class="math inline">\(-0.01\)</span> and <span class="math inline">\(+0.31\)</span> in 2025, while <strong>Física was the only Basque science subject clearly below its norm in 2025 (<span class="math inline">\(-0.39\)</span>)</strong> — a year before the 2026 event, and the year after the 2024 shape step.</p>
<p><strong>School marks.</strong> The Inspectorate’s <em>Resultados escolares 2024-25</em> gives 2º Bachillerato Física: <strong>4 541 students, 98.1 % passed, mean 7.09</strong>. Only 45–48 % of them sit PAU Física, presumably the half that needs the weighting; even that self-selected half scored 1.6 points below its school mark in 2025 and, if school marks did not move, 3.1 points below in 2026. The school pass rate is 98 %, the exam pass rate was 40 %.</p>
<div id="fig-b-school" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b-school-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig10_school_vs_pau.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b-school-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The same subject measured three times: school marks of the 2024-25 cohort, PAU Física 2025 and PAU Física 2026. The cohorts are offset by one year, and the school figure covers all 4 541 students while the PAU figures cover the 2 066–2 189 who sat it.
</figcaption>
</figure>
</div>
<p><strong>Participation.</strong> Presentation among those enrolled ran 64–84 % from 2017 (84.3 % in 2025); 2026 enrolment is unpublished, so the 5.6 % fall in candidates cannot be split into enrolment and abstention. Nationally the Física population grew 30 % over the decade while take-up — the share of PAU candidates sitting Física — moved only from 0.222 to 0.240, and within a community take-up is unrelated to the mean (<span class="math inline">\(r = -0.10\)</span>, <span class="math inline">\(p = 0.34\)</span>).</p>
</section>
<section id="the-papers" class="level2">
<h2 class="anchored" data-anchor-id="the-papers">The papers</h2>
<p><strong>One finding in this section was corrected in the seventh round, and it is the one most often quoted from this briefing.</strong> The Basque 2026 paper is 39 per cent longer to read than the 2025 one, and across the nine communities length is the strongest single correlate of the change in the mean (<span class="math inline">\(r = -0.905\)</span>). Both of those stand. What does not stand is the account of <em>why</em> the Basque paper is long. Splitting both papers’ statements into the narrative and context the competency form requires, the text that states what to do, and the printed prices, and normalising per printed statement because 2025 printed seven and 2026 six: <strong>the narrative is unchanged — 71 words a statement against 70 — while the demand text more than doubled, 88 against 181, and the printed prices went from nothing to 17.</strong> The 2026 criteria itemise each apartado into sub-items of 0.25, and a paper marked that way has to print each quantum’s demand and each quantum’s price. The length is the cost of the itemisation, not of the competency items (<a href="../chapters/16-paradigm.html">Ch. 16</a>, <a href="../chapters/06-interpretation.html#exposure-and-the-third-channel">Ch. 6</a>). It matters for what follows because the two causes are differently actionable: the competency requirement is imposed from outside and cannot be declined, while the itemisation is a local decision, taken to protect candidates, which can be revisited at the cost of the protection.</p>
<p>Every exercise and option of the eighteen ordinary papers of 2025 and 2026 in the nine communities was coded on the EHU competency criteria (146 items). A blind second coder repeated the exercise: <span class="math inline">\(\kappa = 0.76\)</span> on the competency flag, 0.83–1.00 on drawing, graph reading, evaluation and explanation, 0.76 on application and 0.70 on the three-level context code. Every direction of change 2025 → 2026 is identical under both coders. Separately, the structural claims were verified against the thirty-two archived PDFs [Ch. 11, Ch. 13].</p>
<div id="tbl-b-papers" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[24,12,20,26,18]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-papers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Structure and competency content of the eighteen papers [Ch. 11].
</figcaption>
<div aria-describedby="tbl-b-papers-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Community</th>
<th style="text-align: right;">Δ mean</th>
<th style="text-align: right;">Optional %</th>
<th style="text-align: right;">Competency-style points, % of expected</th>
<th style="text-align: right;">Obligatory competency points</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Asturias</td>
<td style="text-align: right;"><span class="math inline">\(+1.13\)</span></td>
<td style="text-align: right;">100 → 100</td>
<td style="text-align: right;">0 → 0</td>
<td style="text-align: right;">0 → 0</td>
</tr>
<tr class="even">
<td>Madrid</td>
<td style="text-align: right;"><span class="math inline">\(+1.05\)</span></td>
<td style="text-align: right;">75 → 75</td>
<td style="text-align: right;">0 → 0</td>
<td style="text-align: right;">0 → 0</td>
</tr>
<tr class="odd">
<td>Castilla-La Mancha</td>
<td style="text-align: right;"><span class="math inline">\(+0.94\)</span></td>
<td style="text-align: right;">100 → 70</td>
<td style="text-align: right;">0 → 20</td>
<td style="text-align: right;">0 → 2.0</td>
</tr>
<tr class="even">
<td>Cataluña</td>
<td style="text-align: right;"><span class="math inline">\(+0.80\)</span></td>
<td style="text-align: right;">50 → 50</td>
<td style="text-align: right;">75 → 38</td>
<td style="text-align: right;">5.0 → 0</td>
</tr>
<tr class="odd">
<td>C. Valenciana</td>
<td style="text-align: right;"><span class="math inline">\(+0.51\)</span></td>
<td style="text-align: right;">85 → 80</td>
<td style="text-align: right;">15 → 0</td>
<td style="text-align: right;">1.5 → 0</td>
</tr>
<tr class="even">
<td>Andalucía</td>
<td style="text-align: right;"><span class="math inline">\(+0.17\)</span></td>
<td style="text-align: right;">60 → 75</td>
<td style="text-align: right;">0 → 0</td>
<td style="text-align: right;">0 → 0</td>
</tr>
<tr class="odd">
<td>Extremadura</td>
<td style="text-align: right;"><span class="math inline">\(-0.82\)</span></td>
<td style="text-align: right;">75 → 75</td>
<td style="text-align: right;">0 → 0</td>
<td style="text-align: right;">0 → 0</td>
</tr>
<tr class="even">
<td>Canarias</td>
<td style="text-align: right;"><span class="math inline">\(-0.83\)</span></td>
<td style="text-align: right;">100 → 70</td>
<td style="text-align: right;">0 → 0</td>
<td style="text-align: right;">0 → 0</td>
</tr>
<tr class="odd">
<td><strong>País Vasco</strong></td>
<td style="text-align: right;"><span class="math inline">\(\mathbf{-1.48}\)</span></td>
<td style="text-align: right;"><strong>75 → 50</strong></td>
<td style="text-align: right;"><strong>25 → 62.5</strong></td>
<td style="text-align: right;"><strong>2.5 → 5.0</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ul>
<li><strong>Five of the six rising communities did not increase the competency content of their paper.</strong> The sixth, Castilla-La Mancha, added one obligatory contextualised item (0 → 20 %) and rose <span class="math inline">\(+0.94\)</span> — which is the single most instructive data point in the set, because it moved on that axis and on no other.</li>
<li><strong>The Basque paper is the only one that changed genre</strong>, and it moved on four axes at once: competency-style content 25 → 62.5 % of expected points, obligatory competency points 2.5 → 5, optionality 75 → 50 %, and a granular sub-task format with the highest count of marking criteria per item of the eighteen (2.67; Cataluña 2.33).</li>
<li><strong>Cutting choice does not by itself set the direction.</strong> Three communities cut optionality by 25 points or more: Castilla-La Mancha and Canarias by 30, Euskadi by 25. Two fell; Castilla-La Mancha rose.</li>
<li><strong>Reading load.</strong> Counting statement text only, the Basque paper lengthened <strong>45 %</strong>, from 1 335 to 1 940 words — against a median of about 1 200 across the eight communities with extractable papers, and a range from 899 (Asturias) to 1 628 (Cataluña). Across those eight the correlation with the grade change is <span class="math inline">\(r = -0.905\)</span> (<span class="math inline">\(p = 0.002\)</span>). Three cautions, all material: it leads the contextualised-points measure only narrowly (<span class="math inline">\(-0.86\)</span>), with which it is collinear at <span class="math inline">\(+0.79\)</span>; the Basque paper is the leverage point, at <span class="math inline">\(+45\)</span> % against a next-largest <span class="math inline">\(+19\)</span> %; and the hypothesis was generated by the coordinator from his own paper, so it is exploratory whatever its <span class="math inline">\(p\)</span>-value.</li>
</ul>
<p><strong>Were the nine sitting comparable exams?</strong> Measured against the three structural criteria as the EHU coordination applies them — optionality 50–85 %, at least 70 % open response, at least one obligatory contextualised item — eight of the nine 2026 papers comply and one does not: <strong>Asturias, which rose <span class="math inline">\(+1.13\)</span>, has 100 % optionality and no obligatory item at all</strong>. Open response separates nobody: on the reading made here none of the 146 items uses a closed format, which is a judgement from the papers rather than a coded variable. A standardised index of how far each paper moved from its own 2025 predecessor — optionality, competency marks, substantive context, contextualised marks — puts <strong>Euskadi first at <span class="math inline">\(+1.76\)</span> SD, more than a full standard deviation clear of the second</strong>; three communities moved on no axis but the contextualised share, and none of the nine is at zero on all four [Ch. 11].</p>
<p>The natural conclusion — that the other communities’ 2026 rises are partly an artefact of papers that did not change — is the right direction and it is not established here. What is established is narrower and still decisive for how the field number should be read: <strong>the nine did not sit the same kind of exam, so the field is a comparison and not a control.</strong> Whether every community was <em>required</em> to move as Euskadi moved cannot be answered from this study’s sources: the text of RD 534/2024 and the Ministry and CRUE orientations were not retrievable during the data hunt and are not in the source registry, so no claim of non-compliance by anybody is made or implied. That gap is data request 9, and it is the difference between “Euskadi did what was required and others did not” and “Euskadi did more than was required” — a compliance question and a design choice respectively, with very different consequences for 2027.</p>
<p><strong>The Basque paper in its own history</strong> [Ch. 12]. Four formats since 2010: two whole options A/B to 2019; the COVID “four-of-eight” 2020–2024; the 2025 paper (four problems of 2.5, one obligatory competency block, no theory); the 2026 paper (two obligatory competency exercises, two with a choice). From 2012 to 2024 all 104 theory questions reproduced verbatim a title from a closed official list of 22, sent to teachers and correctors with its development guide, worth 40 % of the marks. Of the modern-physics problems set in 2010–2024, 14 of 15 were the photoelectric effect. Spherical mirrors were first set in June 2025; standing waves with sound levels and carbon-14 dating in June 2026; a mass spectrometer, obligatory, in July 2026. Marking went from qualitative rules (2012–2024) to first numerical penalties (2025) to a printed <span class="math inline">\(-0.1\)</span> list with symbolic-first, grave errors that may void a section and 0.25-point sub-items (2026). None of those rules is unique — Canarias applies the same list and tightened it the same way, and fell; Andalucía prints a near-identical one and rose; Valencia requires symbolic-first and rose. By simulation, choice alone was worth <span class="math inline">\(+1.24\)</span> under the 2020–24 format, <span class="math inline">\(+0.79\)</span> under 2025 and <span class="math inline">\(+0.53\)</span> under 2026.</p>
</section>
<section id="the-hypotheses-with-verdicts" class="level2">
<h2 class="anchored" data-anchor-id="the-hypotheses-with-verdicts">The hypotheses, with verdicts</h2>
<div id="tbl-b-hyp" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[24,14,62]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-hyp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Ranking: H1b and H2 together at the front and not separable on published aggregates; H1c plausible behind them; H3 unresolved and testable; H5 background; H1a a 2025 coincidence; H4 unsupported inside the PAU; H6 unsupported <a href="../chapters/06-interpretation.html">Ch. 6</a>.
</figcaption>
<div aria-describedby="tbl-b-hyp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 14%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th>Hypothesis</th>
<th>Verdict</th>
<th>Grounds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>H1a The competency model <strong>as a national frame</strong></td>
<td>Describes 2025 at most; does not explain 2026</td>
<td>Applied in all 17 communities both years; 14/17 fell in 2025 with Euskadi milder; 6 of 9 rose in 2026. 2025 was also the end of a subject-general plateau and cannot be separated from it. The only systematic rating of PAU papers’ competency orientation (Universitat Jaume I, six communities, 2015–2025, in <em>The Conversation</em>; primary article not located) places País Vasco and Cataluña among the <em>most</em> competency-oriented before the reform; Cataluña rose.</td>
</tr>
<tr class="even">
<td>H1b Not the model — <strong>this conversion, at this speed</strong></td>
<td>First-order candidate; the strongest surviving explanation of 2026</td>
<td>Reworded on the Catalan archive: Cataluña has examined with real settings and explicit justification demands in every year since 2020 and did not collapse; halving its competency marks in 2026 did not move it against the field. The frame was national; the implementation was not. On a reform-intensity index from four independent axes (optionality withdrawn, competency marks, substantive context, contextualised marks) Euskadi is first of nine at <span class="math inline">\(+1.76\)</span>, the next community at <span class="math inline">\(+0.39\)</span>. Five of the six communities that <em>rose</em> carry negative indices; <span class="math inline">\(r = -0.70\)</span>, <span class="math inline">\(p = 0.035\)</span> across the nine, falling to <span class="math inline">\(r = -0.40\)</span>, <span class="math inline">\(p = 0.33\)</span> without Euskadi — the relation <em>is</em> Euskadi. One community implemented the frame completely and alone.</td>
</tr>
<tr class="odd">
<td>H1c Fifteen years of a predictable paper, and two courses to retune</td>
<td>Plausible, unmeasured, not separable from H1b — and the only candidate that predicts a topic pattern</td>
<td>40 % of the marks came from a closed list for fifteen years; only 22 titles were ever set across 120 slots; optionality was 100 %. Fourteen of fifteen modern-physics problems were photoelectric and fission and fusion were theory titles only, until 2026 set them as problems. The exam had been the curriculum. The schools were told — announced 2024, with 2024–25 and 2025–26 designated transitional — so this is practice, not information: an announcement does not create example banks, mock papers or teaching fluency. Cataluña had no such equilibrium to undo. Unlike its rivals it predicts a topic pattern, which sub-item marks would test.</td>
</tr>
<tr class="even">
<td>H2 The 2026 Basque paper <strong>as a format</strong> — length, optionality, genre</td>
<td>Consistent with everything; first-order variable</td>
<td>Set apart from H1b: reading load <span class="math inline">\(+45\)</span> %, to about 1 430 words of statement; choice halved, two of four problems carrying none (<span class="math inline">\(-0.26\)</span> by simulation); the only paper in the set that changed genre. The whole distribution displaced; damage confined to Física and Matemáticas II; the Catalan mirror image.</td>
</tr>
<tr class="odd">
<td>H3 Tribunals marked more severely</td>
<td>Possible, unmeasured, acknowledged by EHU</td>
<td>The rector reported “significant variation between panels” in Física; the 6 July deck gave tribunal ranges for three other subjects and not for Física. The whole-cohort shape says severity, if present, was general rather than confined to a few panels. Only the tribunal table settles it.</td>
</tr>
<tr class="even">
<td>H4 A weaker or differently composed cohort</td>
<td>Weak inside the PAU; real outside it</td>
<td>Presentation fell 5.6 %; the same students held Química and Biología; take-up flat; the Canarian cohorts sit on the locus. But PISA shows a decade-long Basque decline that the PAU sees only in Física and only from 2025.</td>
</tr>
<tr class="odd">
<td>H5 Weighting rules make Física dispensable</td>
<td>Plausible slow driver, not a 2026 trigger</td>
<td>The Canarian coordinators’ hypothesis for their own decline; fits a slow erosion better than a 1.5-point fall.</td>
</tr>
<tr class="even">
<td>H6 Language or network bias</td>
<td>No evidence either way for Física</td>
<td>Only the Euskara II bias analysis was run; the 2010–2022 differences are small and of both signs.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="pisa-2025-and-the-2027-estimate" class="level2">
<h2 class="anchored" data-anchor-id="pisa-2025-and-the-2027-estimate">PISA 2025 and the 2027 estimate</h2>
<p>PISA is the one instrument that measures these students and is marked outside the Basque system. A standing Basque advantage in science became a deficit a decade ago: <span class="math inline">\(+6.2\)</span>, <span class="math inline">\(+6.4\)</span> and <span class="math inline">\(+9.2\)</span> points above Spain in 2006, 2009 and 2012; then a fall of 22.6 points between 2012 and 2015 while Spain fell 3.7, and no recovery. <strong>PISA 2025, published on 8 September 2026, is the cohort that sits the PAU in 2027 and is the weakest recorded</strong>: Basque science 458.5 against Spain 477.1 and the OECD 481.9, a gap of <span class="math inline">\(-18.6\)</span> (one standard error 4.7), with the Basque share at proficiency levels 5–6 falling from 3.32 % to 1.83 %.</p>
<div id="fig-b-2027" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b-2027-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig23_pau2027.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b-2027-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: <strong>a</strong> — the Basque series with two scenarios for 2027; the bar is the year-to-year term, not a prediction interval. <strong>b</strong> — the one estimated cohort term against the dispersion it must be read through, and against what 2026 actually did.
</figcaption>
</figure>
</div>
<p>Converting that into a PAU estimate is arithmetic, and the arithmetic is the finding. The Basque PISA fall of 21 points is 0.23 of a student standard deviation; transferred one-for-one to the PAU and prorated over the two years between the 2025 and 2027 cohorts it is a <strong>cohort term of <span class="math inline">\(-0.36\)</span> marks</strong>, or <span class="math inline">\(-0.18\)</span> measured from 2026. Three conventions sit inside that number and should travel with it: the transfer is one-for-one because nothing in the data rejects it; the PAU standard deviation of 2.343 comes from the Comunitat Valenciana’s published figures, the only ones available; and the PISA standard deviation of about 90 is Spain’s.</p>
<div id="tbl-b-2027" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-b-2027-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Two scenarios for 2027 (modelled).
</figcaption>
<div aria-describedby="tbl-b-2027-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>If the 2027 paper resembles</th>
<th style="text-align: right;">Cohort term</th>
<th style="text-align: right;">Central estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>the 2025 paper</td>
<td style="text-align: right;"><span class="math inline">\(-0.36\)</span></td>
<td style="text-align: right;"><strong>5.11</strong></td>
</tr>
<tr class="even">
<td>the 2026 paper</td>
<td style="text-align: right;"><span class="math inline">\(-0.18\)</span></td>
<td style="text-align: right;"><strong>3.81</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>PAU 2027 is not something PISA predicts; it is something the 2027 paper and its marking decide.</strong> The two scenarios differ by 1.3 marks; the cohort contributes a third of a mark. Two practical uses: assume an intake slightly weaker than 2025’s and considerably weaker than the decade’s average, and set the paper with that in mind rather than against a remembered cohort; and when the 2027 result arrives, about <span class="math inline">\(-0.36\)</span> is the part that should not be attributed to the paper.</p>
<section id="can-a-rate-of-decay-be-projected" class="level3">
<h3 class="anchored" data-anchor-id="can-a-rate-of-decay-be-projected">Can a rate of decay be projected?</h3>
<p>The coordination has asked whether the cohort decline can be turned into a <em>rate</em>, so that a PAU year could be anticipated before it is sat. Four answers, in order.</p>
<div id="fig-b-cohortrate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-b-cohortrate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../plots/fig28_cohort_rate.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-b-cohortrate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: <strong>a</strong> — the change in PISA science per cohort-year between consecutive rounds. <strong>b</strong> — how much of a shift in the whole population reaches a self-selected upper fraction, under a fixed ability bar and under a fixed share. <strong>c</strong> — what the cohort term is worth against what the paper is worth, one year out.
</figcaption>
</figure>
</div>
<p><strong>The rate is not a slope.</strong> Between consecutive PISA rounds the Basque change per cohort-year runs <span class="math inline">\(+0.01\)</span>, <span class="math inline">\(+3.65\)</span>, <span class="math inline">\(-7.53\)</span>, <span class="math inline">\(+1.44\)</span>, <span class="math inline">\(-1.97\)</span>, <span class="math inline">\(-6.99\)</span> points — a spread of 11.2 points a year around a mean of <span class="math inline">\(-1.90\)</span>. Two of the six intervals carry almost the whole decline and three are flat or positive. A line fitted through them would have a slope, and quoting it would put an honest interval around the wrong model. The cohort that sat PAU 2026 was fifteen in spring 2024, between rounds, so PISA never measured it at all: the cohort term used above interpolates, and assumes the fall was spread evenly over three cohorts.</p>
<p><strong>A constant within-cohort degradation is invisible, and that is the right answer rather than a failure.</strong> Write the PAU mean as <span class="math inline">\(s[A(c,15) + G(c)] + \mathrm{sel}(c) + \mathrm{paper}(y) + \mathrm{marking}(y)\)</span>, with <span class="math inline">\(G\)</span> the gain or loss over the three school years. PISA delivers <span class="math inline">\(A(c,15)\)</span> and nothing about <span class="math inline">\(G\)</span>, which enters every year-to-year difference alongside the paper term — the largest and least measured term in the dossier. A <span class="math inline">\(G\)</span> that is <em>constant</em> cancels in every difference: it is invisible precisely because it is irrelevant to the question the office faces, which is why one year differs from the next. A <span class="math inline">\(G\)</span> that is <em>changing</em> would matter, and would show as the PAU falling faster than PISA for matched cohorts. It falls more slowly (<span class="math inline">\(-0.157\)</span> against <span class="math inline">\(-0.245\)</span> SD per decade in Euskadi, difference <span class="math inline">\(p = 0.67\)</span>) — no support for acceleration, and at four to six points per series no refutation either.</p>
<p><strong>The motivated/unmotivated split is real, and in 2026 it runs the wrong way for dilution.</strong> If more candidates sit Física without needing the mark, the mean falls with nobody’s ability changing. In 2026 it cannot have happened: 2 066 sat Física against 2 189 in 2025, 5.6 % fewer. On the assumption most favourable to the dilution story — that the ones who stayed away were the weakest — the 2026 group should have scored <strong>0.29 marks higher</strong> on an unchanged paper. The composition change is a credit against the fall, not a part of it. (2025 is the opposite case, 22.4 % more candidates with a mean 0.62 lower; and the budget assigns 2025 almost wholly to the national component in any case.)</p>
<p><strong>How much of a population shift reaches the candidates</strong> depends on how selection works, and the two natural rules differ by a factor of four: 0.23 of the shift under a fixed ability bar, exactly 1.00 under a fixed share. The evidence points at the second — a falling population under a fixed bar should produce falling take-up, and take-up instead drifts slightly up (0.222 in 2015 to 0.240 in 2025, <span class="math inline">\(r = -0.096\)</span>, <span class="math inline">\(p = 0.34\)</span>) — and independently, the Basque PISA fall is a location move rather than a collapse of the top: the level 5–6 share went 3.32 % → 1.83 % where a uniform shift of the whole distribution predicts 1.92 %, a discrepancy of just under five per cent of the predicted share. So the one-for-one conversion used above is defensible, but it is the <em>top</em> of the range: the cohort term is an upper bound in magnitude and could be as small as <span class="math inline">\(-0.03\)</span> a year.</p>
<p><strong>What follows for practice.</strong> A cohort projection is real, is worth about a fifth of a mark a year, and is swamped by the choice of paper: one standard deviation of paper-to-paper variation is 0.85, nearly five times the cohort term, and the 95 % band one year out is 1.68, roughly nine times it. It belongs in the office’s expectations and not in its targets. If the 2027 mean comes in half a point below 2026, nothing about the cohort will have been demonstrated; if two points above, nothing will have been refuted.</p>
<p><strong>What would give a rate</strong> is not PISA, which measures every three years and stops at fifteen. It is a yearly census measure of Basque fifteen-year-olds, bracketed at the other end by the school marks of the same cohort at eighteen — which EHU already holds paired with the PAU mark for every candidate, and which this study has for one year only (7.09 against 5.47 in 2025). That pairing over several cohorts is the design that separates a cohort arriving weaker from a cohort being taught and examined differently. It is <strong>data request 8</strong>.</p>
</section>
</section>
<section id="what-the-evidence-does-not-establish" class="level2">
<h2 class="anchored" data-anchor-id="what-the-evidence-does-not-establish">What the evidence does not establish</h2>
<p>The dossier was audited twice, on 19 and 20 September: every script re-run from the raw sources, every number recomputed independently by readers working only from the files, the exam papers re-read as PDFs, all 25 figures checked against their data, and the reasoning read step by step. The second audit corrected the first, which had reported three corrections it had not applied. Everything above is the audited version [Ch. 13].</p>
<p>What remains genuinely open:</p>
<ul>
<li><strong>H2 against H3 cannot be separated from published data.</strong> A harder paper and uniformly stricter marking leave the same whole-cohort signature.</li>
<li><strong>Three quarters of the Basque-specific fall is unattributed</strong>, among four named candidates that the published aggregates cannot prise apart.</li>
<li><strong>The 2026 Basque distribution is modelled.</strong> Only the observed histogram would say whether it, like the Canarian cohorts, moved without reshaping.</li>
<li><strong>Whether 2024 and 2026 are one mechanism or two</strong> is undecided. A compression at the top in 2024 and a collapse of the level in 2026 are compatible with a single slow change in what the marking rewards, and equally compatible with two unrelated events.</li>
<li><strong>The Euskadi-common <span class="math inline">\(-1.18\)</span> has no candidate explanation at all.</strong> It is larger than the Física-specific term, it moved Matemáticas II further than Física, and nothing in this dossier isolates it. It is not the Física paper, because Química and Biología sat the same tribunals and did not follow.</li>
<li><strong>The two versions of the severity hypothesis are not separated.</strong> The subject pattern excludes a general effect as the main cause and is consistent with a numerical-deduction effect; consistency over eight subjects in one year is not a test, and the deduction tally is.</li>
<li><strong>The within-cohort term cannot be identified</strong> from PISA and the PAU together, at any sample size, because it enters every difference alongside the paper term. Only paired school and PAU marks over several cohorts would bound it.</li>
<li><strong>Several figures are press-sourced</strong> (Extremadura 5.27; Asturias’s headline and subject values; the EHU July figures; the Catalan revision requests) and should be confirmed before being quoted onward.</li>
</ul>
</section>
<section id="data-to-request-and-what-each-would-separate" class="level2">
<h2 class="anchored" data-anchor-id="data-to-request-and-what-each-would-separate">Data to request, and what each would separate</h2>
<p>Ordered by how much of the unattributed <span class="math inline">\(-1.33\)</span> each would resolve, not by how easy it is to obtain. Items 3, 8 and 9 are new since the first version of this briefing.</p>
<ol type="1">
<li><strong>Sub-task marks for a stratified sample of 2026 scripts</strong> (say 300, across tribunals): the mean and distribution of marks on each numbered sub-task of each exercise and option. <em>Separates all four</em> unattributed components at once, because each leaves a different signature — marks lost in the obligatory competency exercises rather than the options (content); in the explain-and-evaluate sub-tasks rather than the calculations (genre); through accumulated <span class="math inline">\(-0.1\)</span> penalties and voided sections (marking); only among those who chose the new options (exposure).</li>
<li><strong>Física by tribunal, 2025 and 2026</strong>: <span class="math inline">\(n_j\)</span>, <span class="math inline">\(\bar{x}_j\)</span>, <span class="math inline">\(s_j\)</span> and the school composition of each tribunal’s scripts. EHU computed this and published the equivalent for three other subjects. <em>Separates</em> tribunal severity, and shows whether what is visible in 2026 was building in 2025.</li>
<li><strong>The deduction tally, 2025 and 2026, for Física, Matemáticas II, Lengua Castellana and Euskara II</strong>: how many scripts lost the 0.2 linguistic component, and how many <span class="math inline">\(-0.10\)</span> minor-error deductions were applied per script, by type. <em>Separates</em> general marking severity from the quantitative-specific kind. <strong>This is the cheapest decisive request on the list</strong>: it collects nothing new, the four subjects are already marked, and the comparison the coordination wants falls out of two cross-tabulations. If one item can be obtained quickly and from inside the university, it is this one.</li>
<li><strong>The full Física histogram for 2024, 2025 and 2026</strong>, in one-point bands with the zero and ten counts. <em>Separates</em> location from shape in 2026 — the classification this study could not make — and tests the 2024 compression directly.</li>
<li><strong>Option take-up in 2026</strong>: how many chose each of 3a/3b and 4a/4b, and the mean of each. <em>Separates</em> syllabus exposure from paper difficulty, and measures the realised choice premium against the simulated <span class="math inline">\(-0.26\)</span>.</li>
<li><strong>July 2026 Física</strong>: presented, passed, mean. <em>Separates</em> whether the June pitch was that paper or the 2026 marking.</li>
<li><strong>Revision statistics for Física 2026</strong>. <em>Separates</em> marking severity weakly but cheaply.</li>
<li><strong>School mark and PAU mark, paired, for every Física candidate of the last five cohorts</strong>, with sex, language and territory, and the enrolment figures published until 2022. <em>Separates</em> two things: who sat the exam, which is currently bounded rather than measured; and, over cohorts, the within-cohort term <span class="math inline">\(G\)</span> — the only instrument available for it, since the school mark and the PAU mark are two measurements of the same students weeks apart against two different standards.</li>
<li><strong>The other eight communities’ 2026 papers and marking criteria with their published means</strong>, and the text that fixes the structural criteria nationally, if it exists. <em>Separates</em> nothing inside Euskadi, but decides how much weight the field comparison can carry. Until it is settled, the <span class="math inline">\(-1.65\)</span> is a comparison with communities that did something different, not with a control group.</li>
<li><strong>The record of the correctors’ meeting held before the 2026 sitting</strong>: agenda, attendance and the criteria document circulated. <em>Separates</em> nothing by itself, but it is what turns the account of the regime change from testimony into record. It costs nothing to retrieve.</li>
<li><strong>The 2026 grade-band table for Física</strong> — the shares in <span class="math inline">\([0,5)\)</span>, <span class="math inline">\([5,6)\)</span>, <span class="math inline">\([6,7)\)</span>, <span class="math inline">\([7,8)\)</span>, <span class="math inline">\([8,9)\)</span> and <span class="math inline">\([9,10]\)</span>, the same table published every year through 2025. <em>Separates</em> how the penalties were spread across candidates, and with it how much of the fall the marking can be held to account for. Seven readings of the same regime, each refitted on its own parameters, match all four published figures and differ on the share at or above nine by a factor of twenty-three — 0.3 % if the penalties fell evenly on everybody, 6.1 % if they concentrated on the weakest — which is the difference between the marking accounting for 87 % of the Física-specific fall and 59 % of it. <strong>This is the cheapest request on the list</strong>: the table is a by-product of a tabulation already run and it was routine until last year. The <span class="math inline">\(2.09\)</span> % this dossier quotes for that band is its own smooth-curve extrapolation and is labelled modelled throughout; it is not a substitute.</li>
</ol>
<p><strong>If request 1 is refused as too laborious</strong>, the substitute is a blind re-marking of a stratified sample of 2026 scripts by a second panel: it costs marking time instead of clerical time and it answers requests 1 and 2 together. <strong>If request 2 is refused</strong>, requests 4 and 7 together give a weaker version of the same answer. Nothing substitutes for all three. <strong>Request 3 is the exception to the ordering</strong> — it is decisive for one component and obtainable within days, so it should be made first whatever else is agreed. <strong>Request 11 is the second exception</strong>, for the same reason and at even lower cost: it is one table that already exists, and it settles a question on which two readings of the same marking regime differ by a factor of twenty-three.</p>
</section>
<section id="design-levers-for-2027-ordered-by-evidence-and-cost" class="level2">
<h2 class="anchored" data-anchor-id="design-levers-for-2027-ordered-by-evidence-and-cost">Design levers for 2027, ordered by evidence and cost</h2>
<p>None of these is a recommendation to abandon the competency model, which the evidence does not indict: the most competency-oriented papers in Spain before the reform — Cataluña’s and Euskadi’s own, on the one systematic rating available — sit in communities that went opposite ways in 2026, and Cataluña’s decade of fully contextualised papers is in the one that rose.</p>
<ol type="1">
<li><strong>Record the paper’s parameters before the sitting</strong> and read the result against them: statement length per exercise, competency share, optional share, penalty rules, topics examined, and the PISA cohort term (<span class="math inline">\(-0.36\)</span>). Costs nothing, requires no new belief, and is what makes 2027 interpretable whatever it produces. <em>Evidence: not needed — this is measurement, not a hypothesis.</em></li>
<li><strong>Treat Física and Matemáticas II as one problem.</strong> More than half of the Basque-specific fall is a term the two share, and neither <em>ponencia</em> can see it from inside its own subject: Matemáticas II fell 1.67 on the same cohort and the same tribunals. A joint reading of the two subjects’ 2026 results — and, when it arrives, of the deduction tally for both — is the cheapest way to find out whether the shared term is the cohort, the marking regime, or the simultaneous format change in two quantitative subjects. <em>Evidence: the exact subject split, which is arithmetic rather than a model; what the shared term</em> is <em>remains open.</em></li>
<li><strong>Keep a monitoring set</strong>: mean, pass rate, band shares, and each subject’s mean against its own 2015–2019 norm, computed per tribunal. The subject-against-own-norm comparison is what showed that Física alone was below norm in 2025; the band shares are what would have shown the 2024 compression at the time. <em>Evidence: strong — both findings came from these statistics.</em></li>
<li><strong>Set and record a target statement length — and decide where the words come from, which is a separate decision and the harder one.</strong> The 2026 statement was 45 % longer than 2025’s and the longest of the sixteen papers whose text could be extracted; the 2026 median across those is about 1 200 words and the 2025 Basque paper was 1 335. A target near the Basque paper’s own 2025 length — say 1 300–1 400 words for the whole statement — is the defensible starting band, and it is a bookkeeping target rather than a finding. <strong>What the seventh round adds is that the slack is not where this briefing previously implied it was.</strong> Per printed statement the contextual narrative is already at 70 words and has not grown since 2025; the growth is 93 words a statement of demand text and 17 of printed prices, both of which exist because the marking is itemised into quanta of 0.25 and printed on the paper. Four routes, three of which this dossier can price in words and none in marks: compress the narrative (there is not 470 words of slack in it); flatten two levels of demand back to one (cheapest, and it returns partial credit to the corrector’s discretion); itemise in the criteria as now but print only the apartado and its total (the only route that separates the reading cost from the protection, and nobody has tested whether candidates use the printed weights); or leave the length alone and cap the deductions instead, which is item 8. <em>Evidence: the strongest cross-community association in the study by a short head (<span class="math inline">\(r = -0.905\)</span> against <span class="math inline">\(-0.86\)</span> for contextualised points), and the weakest causally — it is post-hoc, collinear with competency content, and leveraged by the Basque paper itself. The decomposition of the statement, by contrast, is a direct measurement of the Basque papers themselves and is corroborated independently by the coordination’s own reconstruction, which prices the itemisation step at 66 words on one problem.</em></li>
<li><strong>Restore a choice inside the obligatory competency exercises</strong> — two contexts, the same <em>saber básico</em> — rather than restoring optionality elsewhere. The two simulated formats differ by 0.26 of expected mark; a third format with a choice inside the obligatory exercises was not simulated, so that figure is an indication of the size of the lever and not a prediction for it. <em>Evidence: a simulation of the actual formats, plus the coincidence of the most generous choice rule with the highest means in the series. Note that cutting choice did not set the direction: Castilla-La Mancha cut it by more and rose.</em></li>
<li><strong>Publish which <em>saberes</em> can carry a problem in 2027, with model items.</strong> For fifteen years modern physics meant the photoelectric effect; in 2026 three topics were examined for the first time. Opening the syllabus is legitimate; opening it unannounced in the same year as everything else is not what the record recommends. <em>Evidence: the inventory of 146 problems, plus the coordinator’s account of the restriction.</em></li>
<li><strong>Pace the deployment: change one axis a year and announce it.</strong> The one paper that moved on four axes at once fell furthest; the 2025 break taken alone was absorbed better than the Spanish average. <em>Evidence: n = 1 — and the count of axes is four on this study’s own coding, three on an earlier one — which is why it sits seventh rather than first despite being the most plausible recommendation in the list. 2028 is the year the model is to be fully deployed.</em></li>
<li><strong>Decide the marking questions explicitly, and count the deductions first.</strong> The tally of request 3 comes before any decision here, because it says whether the second year of the criteria was in fact stricter and whether it was stricter in the same way for a physics script as for a language script. Then three questions the seventh round makes concrete. <strong>Whether the <span class="math inline">\(-0.10\)</span> deductions should stay uncapped</strong>, when the linguistic penalties in the same criteria are capped at 1.00 and every other community that specifies a cap applies one to the numerical deductions too — Andalucía at <span class="math inline">\(-0.25\)</span> per apartado, Extremadura at 1.00, Canarias at 20 % of the section until it removed the cap in 2026. <strong>Whether a penalty of <span class="math inline">\(0.10\)</span> belongs in a scheme built on a quantum of <span class="math inline">\(0.25\)</span></strong>, since one deduction takes a sub-item to 0.15 and no script is on the grid after the first. And <strong>whether the deductions should fall on half the paper</strong>: only 14 to 19 of a script’s 27 to 32 sub-items can attract a unit, prefix or rounding error, so the uncapped penalties land on the numerical part — which is precisely the part the itemisation was introduced to make forgiving. Then also: whether grave-error clauses that void a whole section are applied uniformly across tribunals (the tribunal table will show it), and whether borderline rounding is wanted — at the ULL its thinning was worth about 5.6 points of pass rate, while the ULPGC shows no such bunching at all, and whether EHU rounds at the threshold is not published. <em>Evidence: no single rule is indicted; their joint introduction in one year is.</em></li>
<li><strong>Calibrate against a target distribution and pre-test.</strong> The Ministry cube gives a full band distribution for every subject, community and year; the 2017–2024 Basque structure outside the COVID peak is <span class="math inline">\([0,5)\)</span> ≈ 30 %, <span class="math inline">\([9,10]\)</span> ≈ 16 %. A pre-test on 40–60 Bachillerato students from two or three centres, sat under exam conditions on a paper that will not be used, gives a usable mean to within about half a point and a clear read on whether the paper can be finished. <em>Evidence: the practice exists informally in other communities’ ponencias; its effect here is untested.</em></li>
<li><strong>Second marking and external review</strong> of the paper before the sitting, on the Galician 2027 model (peer review of papers, double marking), with Rasch equating of tribunals as the statistical complement. <em>Evidence: one Galician announcement and one methodological literature; no effect measured in this data.</em></li>
<li><strong>The timetable, which stopped being a free parameter when it was moved.</strong> This item previously read that Física sits last in Canarias, whose coordinators name it as a factor, and that the Basque timetable is a free parameter, on the evidence of one set of minutes from another community. The two EHU calendars have since been compared and they are not the same. Física’s own slot did not move — last of its day in both years — but <strong>Matemáticas II came out of the Wednesday morning slot into the slot immediately before it</strong>, forty-five minutes ahead, so that for the first time the two heaviest quantitative papers were sat back to back. The four subject changes partition along that pairing exactly: the adjacent pair fell <span class="math inline">\(-1.67\)</span> and <span class="math inline">\(-1.48\)</span>, the pair displaced to Tuesday moved <span class="math inline">\(-0.21\)</span> and <span class="math inline">\(+0.15\)</span>. Two decisions for 2027 cost nothing and remove the confound: do not schedule Matemáticas II and Física consecutively, and do not schedule Física in the slot after the subject that competes with it for the second weighted mark. <em>Evidence: the two published EHU timetables, which is a documentary fact; the partition they match is two observations against two and is confounded with difficulty, so it justifies a scheduling decision and not an attribution.</em></li>
<li><strong>Ask the admissions office what the weighting table is doing to effort.</strong> The rule is printed at the head of every page of the UPV/EHU table — <em>“Se utilizarán las 2 calificaciones que sean más favorables para el estudiantado”</em> — so the return on Física is a step, not a slope. Física weights 0.2 in 28 of the 37 relevant degrees, which reads as demand and is the reverse: <strong>26 of those also weight Matemáticas II at 0.2 and 19 weight Física, Matemáticas II and Química all three at 0.2</strong>. Matemáticas II is compulsory in the access phase and carries forward, so one of the two slots is filled before any elective is chosen; the second is contested between Química — sat the day before Física — and Física itself. In the health-sciences degrees Biología and Química weight 0.2 and Física 0.1, so a medicine-bound candidate cannot bring Física into the best two at all. This selects the <em>strong</em> candidate as the one who can afford to stop, and is the only mechanism in the dossier that predicts a change of shape rather than of level — which is the 2024 signature, the one event here that has never carried a mechanism. The bound is computable from published tables and is worth commissioning. <em>Evidence: the weighting table itself for the structure, which is documentary; the 2024 correspondence is a match of shape and not a test, and nothing published records effort.</em></li>
</ol>
<p><strong>What this needs from the office.</strong> Items 1 and 3 are decisions for the coordination alone and can be taken now. Item 2 needs the office, because no single <em>ponencia</em> can convene it. Items 4 to 8 belong in the 2027 coordination instructions and therefore have to be settled before those instructions go to schools — which, on the 2026 calendar, means before the end of the autumn term. Items 9 to 12 need the admissions office: a pre-test needs permission and centres, double marking needs budget, the timetable is set centrally, and the weighting bound of item 12 needs the admissions data. And the data requests are the office’s to make of EHU; nothing in the first three levers is blocked by them, but the choice between remedies in items 4 to 8 is — and request 3, the deduction tally, is both the cheapest and the one that would most change which of those remedies is right.</p>
</section>
<section id="sources-and-reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="sources-and-reproducibility">Sources and reproducibility</h2>
<p>The dossier archives 166 source files with their hashes: the EHU decks and annual reports, the Ministry EPAU cubes 2015–2025, the Basque Inspectorate’s school results, the transcribed dashboards of ULL, ULPGC and UCLM (recorded as read, without file hashes), the 2025–2026 papers of nine communities with the corrector documents that exist for seven of them, the complete EHU archive 2010–2026, the official theory list, and the INEE PISA tables 2006–2025. Every number in this briefing is produced by a script in <code>scripts/</code> from those files and can be regenerated with one command; the two audits and their layer reports are in <code>logs/</code>. The figures are reproduced as generated, with English labels.</p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/15-synthesis-es.html" class="pagination-link" aria-label="Síntesis (castellano)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Síntesis (castellano)</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/14-briefing-es.html" class="pagination-link" aria-label="Informe (castellano)">
        <span class="nav-page-text">Informe (castellano)</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Independent analysis prepared 18–19 September 2026, audited 19 and 20 September · all figures reproducible from <code>scripts/</code></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Data: EHU, SIIU/EPAU, Generalitat de Catalunya, GVA, Junta de Andalucía, CM, Uniovi, UCLM, ULL, ULPGC, UNIZAR, UPNA, UMU, UC, CiUG, UR</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>