"""Keep the per-page comment threads and the site's comment links in step.

Every page of the site has one standing issue thread in a private companion
repository, so that a remark can be left against the page it concerns without
putting it in the site's own repository. This script is the only place that
mapping is maintained:

    python3 comment_threads.py            report, and regenerate comments.html
    python3 comment_threads.py --create   also open threads for new pages

Everything site-specific lives in comment-threads.json beside _quarto.yml, so
this file is identical across the sites that use it:

    repo     the private repository holding the threads
    site     the published base URL, or null for a site read only locally
    label    a label to put on new threads, or null
    threads  the page-to-issue map, maintained here

The generated partial is comments.html, which _quarto.yml includes after the
body of every page. A page with no thread yet still gets a link — to the issue
list rather than to a thread — so a chapter added between runs is never left
without somewhere to go.

Creating threads needs the gh CLI authenticated against an account with write
access to the notes repository. Nothing else here touches the network.
"""

import argparse
import json
import pathlib
import re
import subprocess
import sys


def project_root():
    """The directory holding _quarto.yml, found by walking up from this file.

    Lets the script sit in scripts/ on one site and at the root of another.
    """
    for candidate in pathlib.Path(__file__).resolve().parents:
        if (candidate / "_quarto.yml").exists():
            return candidate
    raise SystemExit("no _quarto.yml above this script — is it inside a Quarto project?")


ROOT = project_root()
MAP_PATH = ROOT / "comment-threads.json"
PARTIAL_PATH = ROOT / "comments.html"


def load_map():
    if not MAP_PATH.exists():
        raise SystemExit(f"{MAP_PATH} is missing; it carries the repo and the thread map")
    with MAP_PATH.open() as fh:
        return json.load(fh)


def save_map(data):
    with MAP_PATH.open("w") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def page_title(path):
    """The title: line of a .qmd, which is what the thread is named after."""
    for line in path.read_text().splitlines():
        if line.startswith("title:"):
            return line[len("title:"):].strip().strip('"')
    return path.stem


def discover_pages():
    """Every rendered page, as (html key, thread prefix, title, url path)."""
    pages = [("index.html", "index", page_title(ROOT / "index.qmd"), "")]
    for qmd in sorted((ROOT / "chapters").glob("*.qmd")):
        number = re.match(r"(\d+[a-z]?)", qmd.stem)
        prefix = f"ch{number.group(1)}" if number else qmd.stem
        pages.append(
            (f"chapters/{qmd.stem}.html", prefix, page_title(qmd), f"chapters/{qmd.stem}.html")
        )
    return pages


HEADER_PUBLISHED = "**Page:** [{title}]({url})"
HEADER_LOCAL = "**Page:** {title} — `{path}`\n\n_This site is read locally and is not published._"

ISSUE_BODY = """{header}

This is the standing thread for that page. Leave anything here — a remark, a \
criticism, a question, or a paragraph you want written and have not written yet.

Label it so it is clear what you expect to happen:

- `to-complete` — a gap meant to become text on the page
- `correction` — something there is wrong
- `question` — needs settling before anything changes
- `decided` — settled, kept for the record

Quote the sentence you mean. The page is rewritten often, so a quote survives \
where a position does not.

Close the thread only when the page no longer needs anything; otherwise leave \
it open and let the comments accumulate."""


def create_issue(data, title, url_path):
    if data.get("site"):
        base = data["site"].rstrip("/")
        header = HEADER_PUBLISHED.format(title=title, url=f"{base}/{url_path}")
    else:
        header = HEADER_LOCAL.format(title=title, path=url_path or "index.html")

    command = ["gh", "issue", "create", "--repo", data["repo"], "--title", title,
               "--body", ISSUE_BODY.format(header=header)]
    if data.get("label"):
        command += ["--label", data["label"]]

    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"gh issue create failed for {title!r}:\n{result.stderr}")
    return int(result.stdout.strip().rsplit("/", 1)[-1])


PARTIAL = """<!-- Generated by comment_threads.py — do not edit by hand.
     Adds the "Comment on this page" link that points at this page's standing
     thread in the private notes repository. Regenerate after adding a chapter. -->
<style>
  #quarto-margin-sidebar .toc-actions {{
    border-top: 1px solid rgba(128, 128, 128, 0.25);
    margin-top: 1em;
    padding-top: 0.75em;
  }}
  #quarto-margin-sidebar .toc-actions ul {{ display: block; padding-left: 0; margin-bottom: 0; }}
  #quarto-margin-sidebar .toc-actions ul li {{ padding-right: 0; }}
  .nav-footer-center .toc-actions {{ padding-top: 0; }}
</style>
<script>
(function () {{
  var REPO = {repo!r};
  var THREADS = {threads};

  function threadKey() {{
    // Works for a published path and for a local file:// path alike.
    var m = window.location.pathname.match(/chapters\\/([^\\/]+)\\.html$/);
    return m ? "chapters/" + m[1] + ".html" : "index.html";
  }}

  var thread = THREADS[threadKey()];
  // A page added since the last run has no thread yet; send the reader to the
  // issue list rather than nowhere.
  var href = thread
    ? "https://github.com/" + REPO + "/issues/" + thread + "#new_comment_field"
    : "https://github.com/" + REPO + "/issues";
  var label = thread ? "Comment on this page" : "Open the notes";

  var block = document.createElement("div");
  block.className = "toc-actions";
  var link = document.createElement("a");
  link.href = href;
  link.target = "_blank";
  link.rel = "noopener";
  link.className = "toc-action";
  link.title = {tooltip!r};
  link.innerHTML = '<i class="bi bi-chat-left-text" role="img" aria-label=""></i>' + label;
  var item = document.createElement("li");
  item.appendChild(link);
  var list = document.createElement("ul");
  list.appendChild(item);
  block.appendChild(list);

  // Beside the reader's eye while reading; the footer only if there is no
  // margin sidebar on this page.
  var toc = document.querySelector("#quarto-margin-sidebar nav#TOC");
  if (toc && toc.parentNode) {{
    toc.parentNode.insertBefore(block, toc.nextSibling);
  }} else {{
    var footer = document.querySelector(".nav-footer-center");
    if (footer) {{ footer.innerHTML = ""; footer.appendChild(block); }}
  }}
}})();
</script>
"""


def write_partial(data):
    threads = {key: entry["issue"] for key, entry in sorted(data["threads"].items())}
    PARTIAL_PATH.write_text(PARTIAL.format(
        repo=data["repo"],
        threads=json.dumps(threads, indent=4),
        tooltip=data.get("tooltip", "Leave a remark (private)"),
    ))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--create", action="store_true",
                        help="open a thread for any page that has none")
    args = parser.parse_args()

    data = load_map()
    missing = [p for p in discover_pages() if p[0] not in data["threads"]]

    for key, prefix, title, url_path in missing:
        thread_title = f"{prefix} · {title}"
        if args.create:
            number = create_issue(data, thread_title, url_path)
            data["threads"][key] = {"issue": number, "title": thread_title}
            print(f"opened #{number}  {thread_title}")
        else:
            print(f"no thread: {key}  ({thread_title})")

    if args.create and missing:
        save_map(data)

    write_partial(data)
    print(f"{len(data['threads'])} page(s) linked; {len(missing)} without a thread"
          f"{' — run with --create' if missing and not args.create else ''}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
